### ISSUE TITLE
Trying a browser example but not working

### ISSUE THREAD

**Issue by questsin** [mtth/avsc#102]
//I download the zip package. I want to run your library inside a browser.
> npm install
>cd /etc/browser
>browserify avsc.js -o avsc-bundle.js
//include the bundle in a script command and then call the example 

const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: {type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});
const buf = type.toBuffer({kind: 'CAT', name: 'Albert'}); // Encoded buffer.
const val = type.fromBuffer(buf); // = {kind: 'CAT', name: 'Albert'}

//but get an error code from the browser
Uncaught ReferenceError: avro is not defined
    at tests-avsc.js:75
(anonymous) @ tests-avsc.js:75

//any help would be appreciated?
running older build from 3.0 and it is working hotlinked off of gitgub

**Comment by mtth** [comment]
Since you're bundling the script separately, I think you'll need to add the `--standalone/-s` flag  (otherwise the library isn't exported):
```
browserify avsc.js -s avro -o avsc-bundle.js
```

**Comment by questsin** [comment]
Great thanks for the tip.
