### ISSUE TITLE
Enum Symbol Values

### ISSUE THREAD

**Issue by rgarza** [mtth/avsc#103]
Hello, is there a reason for enum types we enforce the name pattern as the only possible values?
if (!isValidName(symbol)) {
      throw new Error(f('invalid %s symbol: %j', this, symbol));
}
i need to have the following possible values:
"symbols": ["C", "F", "N", "3"], the one that throws the error is "3"

Thanks

**Comment by rgarza** [comment]
Nevermind, seems like avro spec says that is the format, 
symbols: a JSON array, listing symbols, as JSON strings (required). All symbols in an enum must be unique; duplicates are prohibited. Every symbol must match the regular expression [A-Za-z_][A-Za-z0-9_]* (the same requirement as for names).

**Comment by mtth** [comment]
Right. In case you're curious, one of the motivations for this is to allow native compilation of Avro enums (for example they need to be a [valid Java identifier](http://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.8)).

**Comment by rgarza** [comment]
Is there a way to convert from string to a "enum" type?, for example if i have in Java

enum Strings {
        STRING_ONE("ONE"), STRING_TWO("TWO");
        private final String stringValue;
        Strings(final String s) { stringValue = s; }
        public String toString() { return stringValue;
     }
var Strings = {
    STRING_ONE: "ONE",
    STRING_TWO: "TWO"
};
and i get an object with a value of "TWO" convert it to STRING_TWO with avsc?

**Comment by mtth** [comment]
You can do that; you just need to implement a custom [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) that'll translate between the two representations. For example, if you just want to prefix values with `STRING_`, you'd write something like:

```javascript
class StringEnum extends avro.types.LogicalType {
  _fromValue(val) {
    // This function gets called to convert Avro's value into the representation you want.
    return val.slice(7); // For example, you can strip the `STRING_` prefix.
  }
  _toValue(any) {
    // This function gets called to convert your representation into a valid Avro value.
    return 'STRING_' + any; // Add the prefix back.
  }
}
```

And you'd then use it as:

```javascript
// Here we instantiate only this enum but it'd work too if it was deeply nested.
const type = avro.Type.forSchema({
  type: 'enum',
  symbols: ['STRING_A', 'STRING_2'],
  logicalType: 'stringEnum', // Apply our custom type.
}, {logicalTypes: {stringEnum: StringEnum}});

console.log(type.isValid('A')); // true
console.log(type.isValid('2')); // true (magic!)
console.log(type.isValid('3')); // false
```

You can implement arbitrary logic in the logical type, not just remove a prefix like the snippet above. For example you could have a mapping between names. Take a look at the logical types documentation linked above, hopefully that combined with the snippets here will be enough to get you started.

**Comment by rgarza** [comment]
Thanks, i think this will do!!
