### ISSUE TITLE
LogicalTypes in BlockDecoder

### ISSUE THREAD

**Issue by rgarza** [mtth/avsc#105]
BlockDecoder is not using the logicalTypes defined for the type, add an option to pass in the logical Types.

**Comment by mtth** [comment]
Hey @rgarza, it's actually supported via the [`parseHook`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) option (see also the example a little below; this lets us decouple the decoder's options from `Type.forSchema`'s):

```javascript
const decoder = new avro.streams.BlockDecoder({
  parseHook: (schema) => {
    return avro.Type.forSchema(schema, {logicalTypes});
  }
});
```

**Comment by rgarza** [comment]
Ahh, makes sense, thank you
