### ISSUE TITLE
toJSON / fromJSON

### ISSUE THREAD

**Issue by questsin** [mtth/avsc#109]
//trying to save toBuffer /fromBuffer for testing
//when trying to save to a string and reading it back as JSON, getting an error
// doing it at run time works :(

const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: {type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});

const buf = type.toBuffer({kind: 'CAT', name: 'Albert'}); // Encoded buffer = {"type":"Buffer","data":[0,12,65,108,98,101,114,116]}.
const val = type.fromBuffer(buf); // = {kind: 'CAT', name: 'Albert'}

type.fromBuffer({"type":"Buffer","data":[0,12,65,108,98,101,114,116]})

avsc-bundle.js:7860 Uncaught TypeError: this.buf.slice is not a function
    at Tap.readString (avsc-bundle.js:7860)
    at StringType._read (avsc-bundle.js:5130)
    at RecordType.readRecord$ [as _read] (eval at RecordType._createReader (avsc-bundle.js:6330), <anonymous>:6:8)
    at readValue (avsc-bundle.js:6866)
    at RecordType.Type.fromBuffer (avsc-bundle.js:4673)
    at <anonymous>:1:6

**Comment by mtth** [comment]
`type.fromBuffer` expects a `Buffer` as input; it looks like you're passing in a buffer's JSON representation instead. The following should work:

```javascript
const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: {type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});

// JSON representation of your buffer.
const obj = {"type":"Buffer","data":[0,12,65,108,98,101,114,116]};
// Transform it back into an actual `Buffer.
const buf = Buffer.from(obj);
// Which we can now deserialize.
const val = type.fromBuffer(buf);
```

**Comment by questsin** [comment]
Class Buffer dosnt seem to exit :(

**Comment by mtth** [comment]
It looks like you're running your code on the client side: you'll need to either expose the `Buffer` constructor from your module or include it via another script ([here](https://github.com/feross/buffer)'s the library, which should be bundled by default when you use `browserify`).

**Comment by questsin** [comment]
Worked. Thanks.. great library!!
