### ISSUE TITLE
handle type of union with nested types in schema 

### ISSUE THREAD

**Issue by sandeepgoyalgit** [mtth/avsc#110]
I have avro object "avroObject" which I have to convert back to Json object, at server side it was formed using nested avro objects

// main avro schema
{
  "type": "record",
  "namespace": "**com.company.space.avro.resources**",
  "name": "Message",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "**com.company.space.avro.uuid**"
      ],
      "default": null
    },
    {
      "name": "subject",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "modifiedBy",
      "type": [
        "null",
        "**com.company.space.avro.uuid**"
      ],
      "default": null
    }
  ]
}

// nested  avro schema : **com.company.space.avro**
{
  "type": "fixed",
  "namespace": "**com.company.space.avro**",
  "name": "uuid",
  "size": 16
}

I am facing issue while defining its Schema to use to get json back  //type.fromBuffer(avroObject)
how to use avro.Type.forSchema({.......})

I tried with following schema which does not worked:
{
  "type": "record",
  "namespace": "com.company.space.avro.resources",
  "name": "Message",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        {
		  "type": "fixed",
		  "size": 16
	}
      ],
      "default": null
    },
    {
      "name": "subject",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "modifiedBy",
      "type": [
        "null",
        {
		  "type": "fixed",
		  "size": 16
	}
      ],
      "default": null
    }
  ]
}

Could you help what's the right way to use nested types in schema

**Comment by sandeepgoyalgit** [comment]
I was able to handle nested types by using :

const registry = {};
// Define a type separately.
const fooType = avro.parse({
    "type": "fixed",
    "namespace": "com.company.space.avro.",
    "name": "uuid",
    "size": 16
}, {"registry": registry, "wrapUnions": false});
// Then reference it.
const fooMapType = {
    "type": "record",
    "namespace": "com.company.space.avro.resources",
    "name": "Message",
    "fields": [
        {
            "name": "id",
            "type": [
                "null",
                "com.company.space.avro.uuid"
            ],
            "default": null
        },
        {
            "name": "subject",
            "type": [
                "null",
                "string"
            ],
            "default": null
        },
        {
            "name": "modifiedBy",
            "type": [
                "null",
                "com.company.space.avro.uuid"
            ],
            "default": null
        }
    ]
};

var type = avro.Type.forSchema(fooMapType, {"registry": registry, "wrapUnions": false});

I am able to create new sample object using type.random, which further propely converts to avro and vice versa. Howerever when I get avro object with same schema I get the below error.
Tried to verify with type.isValid(avroObject), which returned true.
![image](https://cloud.githubusercontent.com/assets/25321865/26302233/9464cb08-3eb1-11e7-9a58-6ce73aabe1f8.png)

Seems to be issue with uuid object, that fixedTypeed object under unions are supposed to be handled in special way?

**Comment by mtth** [comment]
Your understanding of the registry is correct.

There isn't any special handling required for fixed types inside unions. I think the error comes from the fact that `type.isValid` expects a _decoded_ value (usually not a `Buffer`, except for `bytes` and `fixed` types), whereas `type.fromBuffer` expects an _encoded_ value (always a `Buffer`). These values are usually different: in your case, if you have a union around a `fixed` type, the `fixed`'s encoding will be prefixed by the branch's index when encoded as a union.

Where do you get your data from? Are you trying to encode or decode the value?

**Comment by sandeepgoyalgit** [comment]
I have tried collect all facts in the attached image:
![image](https://cloud.githubusercontent.com/assets/25321865/26337257/6b0e48bc-3f45-11e7-8001-7c4a2a34380d.png)

As you said `type.fromBuffer` expects an _encoded_ value (always a `Buffer`). I tried to pass `this.result`(which is of type `ArrayBuffer`) directly to `type.fromBuffer` but that's  also gives error.

Data is being sending from web service endpoint, we are consuming it at clientside using websockets.

**Comment by mtth** [comment]
It looks like your encoded data doesn't match your declared type. Have you been able to decode it outside of this piece of code? Are you sure none of the encodings are corrupting the data? The fact that `fromBuffer` gives different error messages for the two arrays is odd.
