### ISSUE TITLE
Invalid enum index error

### ISSUE THREAD

**Issue by sushantbs** [mtth/avsc#111]
Hi,

This is most likely not a bug with avsc.

I am using `avsc` to read messages being consumed from kafka-node. These messages are produced by a Java service and the encoded message looks something like this

``
'�\u0001\u000bcontentType\u0000\u0000\u0000>"application/x-java-object;type=com.dbs.tup.avro.Notification"\u0001\u000179cc5530-2b7d-4843-b47e-6ed8370ef95�\u0001\u0002\u0001daniellimj�\u0000\u0001OTC Trade Idea: sfd has been publishe�\u0001NEW_OTC_TRADE_IDEA_MESSAG�\u0001\u0001\u0000\u0001\u0000java.util.ArrayLis�\u0001\u0001\u0001\u0001com.dbs.tup.avro.PermissionFilte�\u0001\u0001\u0002\u0001PBIC,PBFXIC,PBRM,PBARM,TPCIC,TPCRM,TPCAR�\u0000\u0001�ͱ��W\u0001Trade Complet�'
``

When I try to deserialize this message (after converting it to a Buffer), I get `Invalid enum index` error for the first field provided in the the schema (which is an enum).

I have a sample JSON at my end that I can convert to buffer and then decode back from the buffer using the same avro schema so I don't think the problem is with the schema or the way I'm consuming it. 

Seems to me that at the producer end, the object being converted is a Java object (should ideally be a JSON, right?) and that is why I'm unable to decode it in node. I can see the text `application/x-java-object` and `java.util.ArrayList` in the encoded message which is why I have come to this conclusion.

Do you have any suggestions about what I can do at my end to work around this?

Great work by the way. Love the simplicity!

**Comment by mtth** [comment]
The encoding above doesn't look like valid Avro binary data. It seems the producer is using some other type of serialization, perhaps the default Java mechanism; do you have any control over that code?

**Comment by sushantbs** [comment]
Unfortunately, no. 

After a few days of trying different options, we have been unable to deserialize the message being produced by the Java service. Node has been dropped :(

Thanks for your help, and keep up the great work.

**Comment by mtth** [comment]
No worries, thanks for the update.
