### ISSUE TITLE
Unable to open output files in Spark and XML SPY

### ISSUE THREAD

**Issue by johnwalker2000** [mtth/avsc#113]
I need some help with the code below.  I am 99% sure I am doing something wrong but I am having trouble finding a solution.  I have tried many variations on the code below with no success.  I am trying to generate a file that successful opens in other tools that read AVRO files.  When I run the code below a file generates that this node package can read but it fails to open in Spark 2.1 and XML SPY.  I can submit the SPARK error log if it helps.  Also when I try in an open source java program I get the error: "You must enter a valid Record Layout Name".   I am running node 6.9.4.

Is it something in regards to the compression option?

Thank you very much!

`
var avro = require('avsc');

var file = './testOutput.avro';
var count = 10;

var str = { firstName:'Jim', lastName:'Test'};

  var type = avro.Type.forValue(str);
  var encoder = avro.createFileEncoder(file, type);
  while (count--) {
    encoder.write(type.random());
  }
  encoder.end();`

**Comment by mtth** [comment]
My guess is that the decoding library expects a name in the record's definition, can you try one of the options in https://github.com/mtth/avsc/issues/108#issuecomment-302436388 ?

**Comment by johnwalker2000** [comment]
Thank you!  Very helpful.
