### ISSUE TITLE
Problems with field names containing spaces

### ISSUE THREAD

**Issue by lilloraffa** [mtth/avsc#114]
Hi,

there is a strange behavior when the field names contains spaces. For example, let's suppose I've a data set with the following schema: 
INPUT: `{"kind": "DOG", "name": "Beethoven", "age": 4}`

This will generate the associated avro schema prfectly: 
OUTPUT: `{"type":"record","fields":[{"name":"kind","type":"string"},{"name":"name","type":"string"},{"name":"age","type":"int"}]}` .  

Wherease, if one (or more) of the fields contains a space, the generated avro schema think of data as there was only one field of type map...
INPUT: `{"kind b": "DOG", "name": "Beethoven", "age": 4}`
OUTPUT: `{"type":"map","values":["string","int"]}`

I guess it is a bug, but wanted to double check with you first. In case it is a bug, can you point me to the part of code where this is handle so I can try to fix it? Thanks a lot!
Raffaele

**Comment by mtth** [comment]
Hey @lilloraffa, that's actually WAI. Avro records aren't allowed to have fields with spaces in their name (see the [specification](https://avro.apache.org/docs/1.8.0/spec.html#names)), the type inference therefore falls back to using a map (where keys are allowed to be arbitrary strings).

**Comment by lilloraffa** [comment]
Thanks Mtth!
