### ISSUE TITLE
createFileEncoder doesn't allow append, 

### ISSUE THREAD

**Issue by sbansal6** [mtth/avsc#115]
-- Should we able to pass in file options like flag:'a' for append mode
-- createWriteStream as now has hardcoded options :( 

/** Writable stream of records to a local Avro file. */
function createFileEncoder(path, schema, opts) {
  var encoder = new containers.streams.BlockEncoder(schema, opts);
  encoder.pipe(fs.createWriteStream(path, **{defaultEncoding: 'binary'}**));
  return encoder;
}

**Comment by mtth** [comment]
Just use the `BlockEncoder` directly. `createFileEncoder` is meant as a convenience for the most common use-case so it doesn't expose all options.
