### ISSUE TITLE
string deserialized as sequence of ascii values instead of string

### ISSUE THREAD

**Issue by bvdeenen** [mtth/avsc#116]
I've added an avro container sample file, that deserializes correctly with avro-1.8.1 using the commandline tool:
```
jar avro-tools-1.8.1.jar tojson --pretty sample.avro
{
  "contactHistory" : [ {
    "attachments" : [ ],
    "caseId" : "jsedpy",
    "caseType" : "plh",
    "contactPerson" : {
      "customerId" : "aopjvwkmkpkbyl",
  ...
```
If I use the same schema, with the same binary data in `avsc` (installed via npm), I see the strings in my nested items being deserialized incorrectly.
![image](https://user-images.githubusercontent.com/47788/27866612-57ba26ea-6197-11e7-8d2a-34f48fd44a5a.png)

I would to help improve avsc, and wouldn't mind having a go at fixing the issue. 

[avro-sample.zip](https://github.com/mtth/avsc/files/1124769/avro-sample.zip)

**Comment by bvdeenen** [comment]
I found the solution.

Line 572 of utils.js should be 
`return (new TextDecoder("utf-8")).decode(buf.slice(pos, pos+len));`

**Comment by bvdeenen** [comment]
I've opened a [pull request](https://github.com/mtth/avsc/pull/117)  that fixes the issue:

![image](https://user-images.githubusercontent.com/47788/27868823-3dc49f8e-619e-11e7-9f53-5576942ebd7d.png)

**Comment by mtth** [comment]
Closing (see https://github.com/mtth/avsc/pull/117).
