### ISSUE TITLE
JSON representation with "left-out" optional fields fails Avro Schema

### ISSUE THREAD

**Issue by kdallmeyer-sr** [mtth/avsc#118]
I don't know if this is an intentional feature or not but I think a usability improvement to the library would be to support JSON objects that leave out optional fields.  Here is an example.

Schema:
```js
var schema = {
  "type" : "record",
  "name" : "Demo",
  "namespace" : "com.shoprunner.data.demo",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "count",
    "type" : [ "null", "int" ]
  }, {
    "name" : "price",
    "type" : [ "null", "float" ]
  } ]
};
```
Then I construct a minified version of that object in Javascript:
```js
var data = { name: "Ken" };
```
I would like to represent that data in the Demo schema but it fails validation.
```js
var buf = schema.toBuffer(data);
// Error: invalid ["null","int"]: undefined

var isValid = schema.isValid(data);
// Return: false
```
Using a full object works.  But setting the fields with null, seems like work that probably doesn't need to be necessary.
```js
data = { name: "Ken", count: null, price: null };
isValid = schema.isValid(data);
// Return true
```

Is there a way to do this easily?

**Comment by mtth** [comment]
You can. Right now the field is nullable but not optional, if you add defaults it'll do what you want:

```javascript
var schema = {
  "type" : "record",
  "name" : "Demo",
  "namespace" : "com.shoprunner.data.demo",
  "fields" : [ {
    "name" : "name",
    "type" : "string"
  }, {
    "name" : "count",
    "type" : [ "null", "int" ],
    "default": null // Here
  }, {
    "name" : "price",
    "type" : [ "null", "float" ],
    "default": null  // And here
  } ]
};
```

**Comment by loganbfisher** [comment]
I am doing the exact same thing as above and am still getting that error.  Any other reason this might not work?

```
{
      "type": "record",
      "name": "CreatedVendorDeployment",
      "namespace": "parkhub.vendor.deployment",
      "doc": "Vendor Deployment Schema",
      "fields": [
        {
          "name": "deploymentId",
          "type": "string"
        },
        {
          "name": "vendorId",
          "type": "string"
        },
        {
          "name": "type",
          "type": "string"
        },
        {
          "name": "collectorId",
          "type": "string"
        },
        {
          "name": "relayId",
          "type": "string"
        },
        {
          "name": "emitterId",
          "type": "string"
        },
        {
          "name": "created",
          "type": ["null", "string"],
          "default" : null
        },
        {
          "name": "updated",
          "type": ["null", "string"],
          "default" : null
        }
      ]
    }
```

**Comment by mtth** [comment]
@loganbfisher - Which version of `avsc` are you using? Can you share a snippet of failing code?

**Comment by shivaganesh2232** [comment]
@mtth I have the similar issue but i am attempting through avro-tools-1.8.2 jar. Below is the exception and json schema. Please suggest your idea of parsing the optional fields if you have any.

Exception in thread "main" org.apache.avro.AvroTypeException: Expected field name not found: photo

- -
- -
"fields": [
          {
            "name": "member_id",
            "type": "long",
            "default": 0
          },
          {"name": "photo", "type": ["null", "string"], "default": null},   // <-- issue here
          {
            "name": "member_name",
            "type": "string",
            "default": "NONE"
          }
        ]
- -
- -

**commands used**: java -jar avro-tools-1.8.2.jar fromjson --schema-file meetup_rsvp_avrosc.avsc meetup_rsvp.json > meetup_rspv.avro

**Comment by clymbon** [comment]
mtth wrote:

> You can. Right now the fields are nullable but not optional, if you add defaults it'll do what you want:

That works.  But I have the reverse problem.  When deserializing, is there a way to avoid creating all those "null" fields?  I'm working with a very large AVRO schema.  This is something that originally started as an XML schema that has been transformed into AVRO.  It contains many, many fields, almost all of which are optional.  This works for serialization, and creates a relatively compact encoding. The problem is that when I deserialize into javascript, I get a very large javascript object, containing many, many, null fields.  Functionally, this can work, but I'm afraid it's going to cause performance problems.  

I'm not sure there's any way around this.  I want something like: "default":undefined, but I don't think AVRO schema supports this.  

Any suggestions?

**Comment by vinay0628** [comment]
> mtth wrote:
> 
> > You can. Right now the fields are nullable but not optional, if you add defaults it'll do what you want:
> 
> That works. But I have the reverse problem. When deserializing, is there a way to avoid creating all those "null" fields? I'm working with a very large AVRO schema. This is something that originally started as an XML schema that has been transformed into AVRO. It contains many, many fields, almost all of which are optional. This works for serialization, and creates a relatively compact encoding. The problem is that when I deserialize into javascript, I get a very large javascript object, containing many, many, null fields. Functionally, this can work, but I'm afraid it's going to cause performance problems.
> 
> I'm not sure there's any way around this. I want something like: "default":undefined, but I don't think AVRO schema supports this.
> 
> Any suggestions?

@clymbon 
You able to avoid the null fields during de-serialization? If so, can you please suggest me.

**Comment by clymbon** [comment]
No, when I deserialize I get a JavaScript oblect with all the properties defined, with a value of "null".  That's not what I want.  In my opinion, AVRO should have a way to encode "undefined" or "does not exist".  That would be quite powerful.

Duncan

Sent with BlackBerry Work (www.blackberry.com)
________________________________

**Comment by vinay0628** [comment]
Agreed! Hopefully something comes in future versions/releases.
