### ISSUE TITLE
Cannot reproduce output as presented for custom long types

### ISSUE THREAD

**Issue by arpitjain099** [mtth/avsc#122]
In the wiki for part https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types, it says that:
const obj = new Long(buf);
const encoded = type.toBuffer(obj); // == buf
const decoded = type.fromBuffer(buf); // == obj (No precision loss.)

However, while reproducing using the commands given in the document, comparing console.log(encoded===buf) returns false (opposite to what is reported in the spec document). Similarly, console.log(decoded==obj) returns false (opposite to what is reported in the spec document)

P.S. I tried the implementation with module, 'int-64', and also with module 'long'.

**Comment by mtth** [comment]
It looks like the example was off, here's an updated version that works:

```javascript
const Long = require('long');
const avro = require('avsc');

const longType = avro.types.LongType.__with({
  fromBuffer: (buf) => {
    return new Long(buf.readInt32LE(), buf.readInt32LE(4));
  },
  toBuffer: (n) => {
    const buf = Buffer.alloc(8);
    buf.writeInt32LE(n.getLowBits());
    buf.writeInt32LE(n.getHighBits(), 4);
    return buf;
  },
  fromJSON: Long.fromValue,
  toJSON: (n) => { return +n; },
  isValid: Long.isLong,
  compare: (n1, n2) => { return n1.compare(n2); },
});

const type = avro.Type.forSchema('long', {registry: {'long': longType}});
const encoded = type.toBuffer(Long.fromString('9007199254740995'));
const decoded = type.fromBuffer(encoded);

console.log(decoded.toString()); // === '9007199254740995'
```

I updated the documentation too, thanks for reporting!
