### ISSUE TITLE
Update wiki benchmark

### ISSUE THREAD

**Issue by Akkuma** [mtth/avsc#123]
I ran the benchmark locally and the numbers presented on the wiki seem to be very misleading compared to the current performance compared to the other serialization formats

```
decode "Coupon"
avsc x 822,220 ops/sec ±2.32% (84 runs sampled)
flatbuffers x 989,465 ops/sec ±1.54% (86 runs sampled)
json x 403,648 ops/sec ±1.58% (85 runs sampled)
msgpackLite x 101,653 ops/sec ±1.93% (83 runs sampled)
protobufjs x 1,260,483 ops/sec ±1.52% (83 runs sampled)
protocolBuffers x 913,593 ops/sec ±1.62% (85 runs sampled)
schemapack x 1,403,498 ops/sec ±0.89% (91 runs sampled)
encode "Coupon"
avsc x 488,029 ops/sec ±5.09% (69 runs sampled)
flatbuffers x 220,290 ops/sec ±1.66% (86 runs sampled)
json x 350,408 ops/sec ±2.15% (81 runs sampled)
msgpackLite x 125,635 ops/sec ±2.84% (78 runs sampled)
protobufjs x 768,672 ops/sec ±1.50% (89 runs sampled)
protocolBuffers x 404,623 ops/sec ±3.53% (78 runs sampled)
schemapack x 882,167 ops/sec ±0.87% (91 runs sampled)
```

**Comment by mtth** [comment]
Recent versions of node have a different performance profile than the one used when I wrote the wiki; I've added an explicit mention of this in the document, pointing to the benchmarking script. Note that the numbers are actually still reasonably representative of JSON/MessagePack/PSON relative speeds (basically anything but the Protobuf library which much got faster in recent versions).

I also just noticed that some of the benchmarking code is incorrect/outdated (for example `flatbuffers` is skipping a few fields, making it faster than it should be), I'll update it along with the documentation when I have a chance to go through it.
