### ISSUE TITLE
Problems decoding with fromBuffer

### ISSUE THREAD

**Issue by joelnet** [mtth/avsc#125]
I'm having problems decoding data. I am having these problems in Chrome and Edge Curiously, this works fine in Firefox.

Here's an example, I took from the README, the only change I made was to add `breed`.

```
const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    { name: 'kind', type: { type: 'enum', symbols: ['CAT', 'DOG'] } },
    { name: 'name', type: 'string' },
    { name: 'breed', type: 'string' },
  ],
});

const buf = type.toBuffer({ kind: 'CAT', name: 'Albert', breed: 'Scottish Fold' }); // Encoded buffer.
const val = type.fromBuffer(buf); // = {"kind":"CAT","name":"\u0000\fAlbert\u001aScottish Fold","breed":"\u0000\fAlbert\u001aScottish Fold"} 
```

Base64 of buf is `AAxBbGJlcnQaU2NvdHRpc2ggRm9sZA==`

All environments produce the same Base64 string, but Firefox is the only environment that decodes it properly.

If I change the code to use the buffer package from npm, things work proper.

```
const Buffer = require('buffer').Buffer;
const buf = type.toBuffer({ kind: 'CAT', name: 'Albert', breed: 'Scottish Fold' }); // Encoded buffer.
const base64 = buf.toString('base64');
const val = type.fromBuffer(Buffer.from(base64, 'base64')); // = {kind: "CAT", name: "Albert", breed: "Scottish Fold"}
```

This also works:
```
const Buffer = require('buffer').Buffer;
const buf = type.toBuffer({ kind: 'CAT', name: 'Albert', breed: 'Scottish Fold' }); // Encoded buffer.
const val = type.fromBuffer(Buffer.from(buf)); // = {kind: "CAT", name: "Albert", breed: "Scottish Fold"}
```

**Comment by mtth** [comment]
That's odd. Can you share the code that you used to build the page (including any webpack, browserify scripts) to help me reproduce the issue locally?

**Comment by joelnet** [comment]
Ok, I spend a few minutes looking into this. I was able to boil it down to the minimum to reproduce here: https://github.com/joelnet/avsc-issue-125

Here's what I was able to find:
* It doesn't work with `webpack-dev-server`.
* It works fine with `webpack`.
* It works with both if I use the `buffer` package.

There's something about `webpack-dev-server` that runs differently than `webpack`.

**Comment by joelnet** [comment]
The hint I needed was in what I wrote above.

I was using the globally installed `webpack-dev-server` which was version 1.14.1. After adding version 2.7.1 to the devDependencies, things started working. I removed my globally installed version to eliminate future confusion.

Cheers!

**Comment by mtth** [comment]
Thanks for the update @joelnet. Nice investigation, I'm glad you found the fix!
