### ISSUE TITLE
Failed to properly encode avro file with snappy compression

### ISSUE THREAD

**Issue by plamen-paskov** [mtth/avsc#126]
I have the following code that i want to run in the browser but i receive an error: 

```javascript
const avro = require('avsc');
var snappy = require('snappy');

var events = {
    events: [{
        "event": "event1",
        "app": "app1"
    }, {
        "event": "event2",
        "app": "app1"
    }]
};

const type = avro.Type.forSchema({
    "type": "record",
    "name": "BatchEvent",
    "namespace":"avro",
    "fields": [
        {
            "name": "events",
            "type" : {
                "type": "array",
                "items": {
                    "name": "Event",
                    "namespace":"avro",
                    "type": "record",
                    "fields": [
                        {
                            "name": "event",
                            "type": "string"
                        },
                        {
                            "name": "app",
                            "type": "string"
                        }
                    ]
                }
            }
        }
    ]
} );
var encoder = avro.createBlobEncoder(type, {
    codecs: {
        snappy: snappy.compress
    },
    codec: "snappy",
    writeHeader: true
}).on('data', function (a) {
    console.log('testtt')
});
encoder.write(events);
```

This code is compiled with browserify with the following command:

browserify avro.js -o avro-test.js

And this is the html file that include avro-test.js

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="avro-test.js"></script>
</head>
<body>

</body>
</html>
```

Unfortunately when i open the html page i get the following error and i cannot figure out what's the problem:

```
avro-test.js:21491 Uncaught TypeError: exists is not a function
    at Function.getRoot (avro-test.js:21491)
    at bindings (avro-test.js:21393)
    at Object.<anonymous> (avro-test.js:21509)
    at Object.60.../../../../../../usr/local/lib/node_modules/browserify/node_modules/is-buffer/index.js (avro-test.js:21564)
    at s (avro-test.js:1)
    at avro-test.js:1
    at Object.48.avsc (avro-test.js:13114)
    at s (avro-test.js:1)
    at e (avro-test.js:1)
    at avro-test.js:1
getRoot @ avro-test.js:21491
bindings @ avro-test.js:21393
(anonymous) @ avro-test.js:21509
60.../../../../../../usr/local/lib/node_modules/browserify/node_modules/is-buffer/index.js @ avro-test.js:21564
s @ avro-test.js:1
(anonymous) @ avro-test.js:1
48.avsc @ avro-test.js:13114
s @ avro-test.js:1
e @ avro-test.js:1
(anonymous) @ avro-test.js:1
```

This path looks weird : ../../../../../../usr/local/lib/node_modules/browserify/node_modules/is-buffer/index.js
I tried the hello world example provided by browserify and i don't see any reference to this file and this force me to think that it's somehow related to avsc. Maybe i'm doing something wrong ? Any help is appreciated!

Thanks

**Comment by plamen-paskov** [comment]
I found that this error is triggered because of the snappy plugin. Can you point me how to snappy compress the data?

**Comment by mtth** [comment]
This doesn't look like an `avsc` issue, the `snappy` library won't work in the browser (it uses a native addon), you might want to try [`snappyjs`](https://github.com/zhipeng-jia/snappyjs) instead. To help you handle CRC handling ([required by Avro](https://avro.apache.org/docs/1.8.0/spec.html#snappy)), I've just added an example using snappy in the [API Wiki](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts); porting it to `snappyjs` or any other equivalent library should be straightforward.
