### ISSUE TITLE
make a bin/avro-cli tool similar to java version avro-tools ?

### ISSUE THREAD

**Issue by c0b** [mtth/avsc#130]
with this library, it's easy to make a CLI script to play with avro files, convert between different block compression, and dump schema from avro file, and dump avro files in json format, for such small task a CLI script would be very handy, would you like to make one? or I have a very simple script can start with, would you like such a PR?

Similar to https://mvnrepository.com/artifact/org.apache.avro/avro-tools

```console
$ java -jar .../path/to/avro-tools-1.8.2.jar
Version 1.8.2
 of Apache Avro
Copyright 2010-2015 The Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).
----------------
Available tools:
          cat  extracts samples from files
      compile  Generates Java code for the given schema.
       concat  Concatenates avro files without re-compressing.
   fragtojson  Renders a binary-encoded Avro datum as JSON.
     fromjson  Reads JSON records and writes an Avro data file.
     fromtext  Imports a text file into an avro data file.
      getmeta  Prints out the metadata of an Avro data file.
    getschema  Prints out schema of an Avro data file.
          idl  Generates a JSON schema from an Avro IDL file
 idl2schemata  Extract JSON schemata of the types from an Avro IDL file
       induce  Induce schema/protocol from Java class/interface via reflection.
   jsontofrag  Renders a JSON-encoded Avro datum as binary.
       random  Creates a file with randomly generated instances of a schema.
      recodec  Alters the codec of a data file.
       repair  Recovers data from a corrupt Avro Data file
  rpcprotocol  Output the protocol of a RPC service
   rpcreceive  Opens an RPC Server and listens for one message.
      rpcsend  Sends a single RPC message.
       tether  Run a tethered mapreduce job.
       tojson  Dumps an Avro data file as JSON, record per line or pretty.
       totext  Converts an Avro data file to a text file.
     totrevni  Converts an Avro data file to a Trevni file.
  trevni_meta  Dumps a Trevni file's metadata as JSON.
trevni_random  Create a Trevni file filled with random instances of a schema.
trevni_tojson  Dumps a Trevni file as JSON.
```

**Comment by mtth** [comment]
If the script is lightweight and seems useful, I'm happy to add it to `etc/scripts`. A more involved tool would probably be best distributed as a separate package (for example to avoid pulling in its dependencies into the core library).

**Comment by c0b** [comment]
my goal is to make the avro-cli tool package and prefer to install globally, then it will be a handy tool to manipulate avro files available to system wide; not planning to implement all options of java version avro-tools; but a few extra options I think is necessary but do not want to touch java code

to be feature complete, it will inevitably require `'snappy'` and an argument processing package (like yargs or commander, choose one with minimum dependency);
so looks like isn't a well match inside this package here, but a separate package may be better.
