### ISSUE TITLE
encoder.end() issues

### ISSUE THREAD

**Issue by christian2345** [mtth/avsc#131]
Hi Matt,

great package you put together, I love it. 2 questions, though.

1) for the container file **decoder**, there is an event defined - .on('data',....) - which allows to pick up data after they have been decoded. I would need to copy a container file after it has been written, but a first test of <encoder>.end().on('finish',....) threw an error.  Is there a way to have the .end() function thenable or or promisified or a declared event to continue after write complete?

2) What I'd really like to do, put the encoded file into an AWS S3 bucket. Writing to local storage and then (after completion) calling S3.putObject(...) would be a possibility, but it would be *far more* convenient if a call like AVRO.createFileEncoder('uri',avro_type) was possible. is there a possibility to tweak the current implementation or would this require new magic?

anyway, thanks for the good work.
Chris

**Comment by mtth** [comment]
Hey @christian2345,

1. The `.end` method is part of the built-in [stream API](https://nodejs.org/api/stream.html), so it's probably best not to change its behavior. You can still have events happen after the stream ends though, you just need to register them before:

  ```javascript
  decoder
    .on('finish', onFinish) // `onFinish` will run only when the stream ends.
    .end();
  ```

2. `createFileEncoder` is just a convenience method for creating a [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts) and piping it to a file. In your case, it sounds like you could just create a `BlockEncoder` directly and pipe its results to an S3 write stream. I'm not familiar with S3's API but it looks like there's an [`upload`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) method just for this:

```javascript
const encoder = new avro.streams.BlockEncoder(someType);
s3.upload({Body: encoder}); // Upload the encoded bytes directly to S3.
encoder.write(someValue); // Write some data.
encoder.end(); // Finish the upload.
```

**Comment by christian2345** [comment]
Hi Matt,

 

Thanks, this is what I was looking for.

In fact, I was checking API documentation, but I did not find the .on(‘finish’,…) method.

Funny enough, providing a function to .end(myfunction) would execute this function also at the end.

 

But your hint about using BlockEncoder is what I am actually looking for, thanks.

 

Best regards

Chris

**Comment by mtth** [comment]
Great, glad to hear it worked out.
