### ISSUE TITLE
decode - decoding a "bad" message

### ISSUE THREAD

**Issue by FuzzOli87** [mtth/avsc#132]
Hello,

I have a question about the behavior of the decode method. I'm currently attempting to "catch" a message that does not match the schema fields at all.

When attempting to encode, I get an error if the message I'm trying to encode does not match the type for a field. 

However, when I'm decoding, it seems to just decode and take a guess as to how to do it. Even if the field names don't match at all.

```
const avro = require('avsc');

function serializeMessageToSchemaRegistryAvro(message, type, startingLength) {
  const length = startingLength || 1024;
  const buf = Buffer.alloc(length);

  buf.writeInt32BE(1, 1);

  const pos = type.encode(message, buf, 0);

  if (pos < 0) {
    // The buffer was too short, we need to resize.
    const newStartingLength = length - pos;

    return serializeMessageToSchemaRegistryAvro(message, type, newStartingLength);
  }

  return buf.slice(0, pos);
}

const typeOne = avro.Type.forSchema({
  type: 'record',
  name: 'ConsumerIntegrationOriginal',
  namespace: 'test.schema',
  fields: [
    {
      name: 'name',
      type: 'int'
    },
    {
      name: 'age',
      type: 'string'
    },
    {
      name: 'time',
      type: 'long'
    }
  ]
});

const typeTwo = avro.Type.forSchema({
  type: 'record',
  name: 'ConsumerIntegration',
  namespace: 'test.schema',
  fields: [
    {
      name: 'namez',
      type: 'int'
    },
    {
      name: 'agez',
      type: 'int'
    },
    {
      name: 'timez',
      type: 'long'
    }
  ]
});

const message = {
  name: 1,
  time: Date.now(),
  age: '12'
};

const encodedMessage = serializeMessageToSchemaRegistryAvro(message, typeOne);

const decoded = typeTwo.decode(encodedMessage, 0);

console.log('decoded', decoded);

```

Is this correct behavior? Am I just not using the right method or am I missing something?

**Comment by mtth** [comment]
Avro encoded data doesn't contain any type information at all (to keep it as compact as possible) so decoding can't perform the same validation as encoding. Decoding will often fail when reading using the wrong schema but not always as you've noticed.

A common pattern to work around this is to prefix the encoded data with a schema identifier or even include the schema entirely if you are serializing in batch (this is the approach used by [container files](https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files)).

**Comment by FuzzOli87** [comment]
@mtth I'm using this within the Schema Registry world and I believe that the current serializing implementation for it is doing the very thing you're talking about. Including the schema information with each message. Which now brings up a potential issue if I'm decoding an avro message from the Confluent SerDes in the node application. 

I'll do some research and come back with findings! Thanks!
