### ISSUE TITLE
benchmarked with fastavro

### ISSUE THREAD

**Issue by yiga2** [mtth/avsc#135]
Not an issue rather a question - how does avsc compare to fastavro for encoding (only) ?

Performance is key when dealing with AWS Lambda or Google/Azure Functions as operations must complete within 5 or 9 min.

**Comment by mtth** [comment]
`avsc` will be faster than `fastavro`; the magnitude of the speedup will mostly depend on your schema and somewhat on your setup. Here are a few sample benchmark results for encoding [various schemas](https://github.com/mtth/avsc/tree/master/etc/schemas) using node `8.9.1` and python `2.7.14`:

```
library           node-avsc        python-fastavro
                        ops      %             ops     %
schema
Cake.avsc          174151.0  100.0         11186.0   6.0
Coupon.avsc        397997.0  100.0         36503.0   9.0
HistoryItem.avsc   504043.0  100.0         23539.0   5.0
Human.avsc         528227.0  100.0         60597.0  11.0
Person.avsc        965030.0  100.0         99668.0  10.0
User.avsc          298920.0  100.0         11061.0   4.0
```

The `ops` column represents the number of encodings per second and the second column the speed relative to the fastest library; so for example `fastavro` is 5% as fast as `avsc` for the `HistoryItem` schema and overall it looks like `avsc` is 10 to 20 times faster than `fastavro`.

Finally, the README in the [benchmark folder](https://github.com/mtth/avsc/tree/master/etc/benchmarks/avro-serialization-implementations) has instructions on how to run the benchmarks yourself if you'd like to do so.

**Comment by yiga2** [comment]
Wow - impressive. I read about spavro too.

My knowledge is limited to Python but will consider hire a node js expert
here. Indeed my avro encoding is meant to run on the fly as a cloud
function, which times out after 5min. Depending on size of computing and
file, this may be a bottleneck using Python.

**Comment by mtth** [comment]
Sounds good. With `avsc` this should be very achievable: encoding throughput on the examples above is ~1GiB per minute.
