### ISSUE TITLE
Error on Quickstart guide

### ISSUE THREAD

**Issue by metint** [mtth/avsc#138]
Regarding the following code example at the very end of the page https://github.com/mtth/avsc/wiki/Quickstart

```javascript
// Similarly, an HTTP client:
const client = service.createClient({transport: function (cb) {
  return http.request({method: 'POST', port: 8080})
    .on('response', function (res) { cb(null, err); })
    .on('error', cb);
}});
```

I believe `cb(null, err)` should be `cb(null, res)`. Since I am new to both javascirpt and avro, it took several hours for me to find the error. Correcting the example might help the others.

Thanks for the library by the way.

**Comment by mtth** [comment]
The error is fixed now - thank you for the heads up!
