### ISSUE TITLE
Some mandatory fields in schema definitions are not checked 

### ISSUE THREAD

**Issue by sebpiq** [mtth/avsc#139]
Avro spec specifies that `record` type **must** have a `name` field. Should `Type.forSchema` throw an error with the following schema (taken from the `README`) : 

```javascript
// This schema is not valid as name field is missing on the record
const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: {type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});
```

**Comment by mtth** [comment]
This is actually WAI. The default behavior is to allow "anonymous types" under the assumption that many users of this library will not be familiar with Avro's specification but will be looking for a good JavaScript serialization library, for which these names aren't required.

You can enable a stricter, specification-compliant, parsing via the `noAnonymousTypes` option of [`Type.forSchema`](https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts). (Having this be the default would also have been a valid option--we could debate whether the ease of convenience is worth the inconsistency--but the current behavior will have to stay at least until the next major release.)

**Comment by sebpiq** [comment]
I would at least mention this in the README, this came as a surprise for us when we tried to interact with a Java application that was using an avro serializer enforcing Avro compliance
