### ISSUE TITLE
serialization of arbitrary data ?

### ISSUE THREAD

**Issue by kapouer** [mtth/avsc#14]
I read avro is supposed to work with a schema. But can it (de)serialize arbitrary objects like json do ?

**Comment by mtth** [comment]
You do need a schema. If by arbitrary objects you mean arbitrary structure then yes (as long as you have a matching schema), if you mean arbitrary classes (e.g. `Buffer`s, `Date`s, custom constructors etc.) then yes as well with [logical types](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) (which is actually tricky to do correctly with JSON).

**Comment by mtth** [comment]
@kapouer - Was there a specific use-case you had in mind?

**Comment by kapouer** [comment]
Yes, Inter Process Communication ! But it seems avro is not made for that.

**Comment by mtth** [comment]
[It actually is](https://avro.apache.org/docs/current/spec.html#Protocol+Declaration). I'm still figuring out how to best integrate this (see https://github.com/mtth/avsc/issues/9). Which transport would you use to communicate between processes? [`Socket`](https://nodejs.org/api/net.html#net_class_net_socket)s?
