### ISSUE TITLE
Incomplete error messages

### ISSUE THREAD

**Issue by joaomilho** [mtth/avsc#140]
So when missing a field one would get

```
Error: invalid "string": undefined
        at throwInvalidError (.../node_modules/avsc/lib/types.js:2911:9)
        at StringType.Object.<anonymous>.StringType._write (.../node_modules/avsc/lib/types.js:1035:5)
      ...
```

It would be quite helpful to include the name of the missing field and more info to spot the problem faster.

Thanks!

**Comment by mtth** [comment]
It's too expensive to keep enough information for this during encoding (it'd slow it down by an order of magnitude). The recommended pattern is to use [`type.isValid`](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts) with a custom error hook (for example [this one](https://gist.github.com/mtth/fe006b5b001beeaed95f#file-collect-js)) to produce detailed errors where required; for example you could wrap some call-sites with:

```javascript
let buf;
try {
  buf = type.toBuffer(val);
} catch (err) {
  err.paths = type.isValid({errorHook: collectInvalidPaths}); // From the gist above.
  throw err; // Or add custom pretty-printing logic for the paths.
}
```

**Comment by joaomilho** [comment]
Amazing, will try it out!

**Comment by joaomilho** [comment]
FYI works beautifully. We'll probably publish a package for dealing with confluent stuff soon that depends on avsc and uses that error treatment. Will let you know.

**Comment by joaomilho** [comment]
This is our first step, FYI https://github.com/tulios/kafkajs
