### ISSUE TITLE
Error: invalid {"type":"map","values":"string"}

### ISSUE THREAD

**Issue by jackhickey** [mtth/avsc#141]
Hello, I've a question/issue regarding map.

I have a schema which contains:

`
              {
                "name": "someName",
                "type": {
                  "type": "map",
                  "values": {
                    "type": "string",
                    "avro.java.string": "String"
                  },
                  "index": true
                },
                "default": []
              }
`

which fails to parse with the follow error: Error: invalid {"type":"map","values":"string"}.

This seems to function in java libraries but not with avsc.

I thought initially it was an issue with avro.java.string but I have an array which uses it similarly without a problem.

`              {
                "name": "someArray",
                "type": {
                  "type": "array",
                  "items": {
                    "type": "string",
                    "avro.java.string": "String"
                  },
                  "index": true
                },
                "default": []
              }`

Is this an issue with my schema or a bug?

**Comment by mtth** [comment]
The default value in your schema is invalid for a map field (see [the examples in the specification](https://avro.apache.org/docs/1.8.2/spec.html#schema_record)). It will work if you switch to `"default": {}`.

**Comment by jackhickey** [comment]
Thank you, well spotted.
