### ISSUE TITLE
Question about custom type hook example

### ISSUE THREAD

**Issue by FuzzOli87** [mtth/avsc#142]
Hello, 

You wrote an example in this issue:
https://github.com/mtth/avsc/issues/69

```
/** Generate a type hook to apply the custom logical type above to all unions. */
function createTypeHook() {
  const visited = [];
  return (attrs, opts) => {
    if (attrs instanceof Array && !~visited.indexOf(attrs)) {
      visited.push(attrs);
      return new CustomUnionType(attrs, opts);
    }
  };
}
```

Why are we doing the bit where we are monitoring the "visited" array for attrs that have run through?

**Comment by mtth** [comment]
Hey @FuzzOli87, this to avoid infinite recursions. Type hooks get called each time a type is instantiated; so in this example it gets called again for `attrs` inside of the `CustomUnionType`. The reason `avsc` doesn't do this check automatically is that there's no obvious way to do so: if `attrs` is reassigned (for example to add a field to a record), the check would have to be different. Does this make sense?
