### ISSUE TITLE
Date?

### ISSUE THREAD

**Issue by JesterXL** [mtth/avsc#147]
How do I get `Date` 's to work? I tried:

```json
{  
   "name":"date",
   "type":"int",
   "logicalType": "date"
}
```

And then:
```json
{  
   "name":"date",
   "type":"long",
   "logicalType": "date"
}
```

But the JSON compile to buffer keeps failing. I've seen various blogs that show `Date.now()` to get the milliseconds since epoch, but... that's not a Date. I was under the assumption you could take JSON, a schema, and compile to Buffer, but for Date's, it looks like I might have to parse them to AVRO parseable first for the dates, and the reverse when getting them out of a Buffer?

**Comment by mtth** [comment]
I think [this example](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) is exactly what you're looking for.

**Comment by JesterXL** [comment]
Dude, you are the man, thanks a lot!
