### ISSUE TITLE
isValid does not specify error fields when setting noUndeclaredFields to true

### ISSUE THREAD

**Issue by nabeelz6** [mtth/avsc#148]
Hi,

I'm using [isValid](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts) method to verify JSON before attempting to encode avro. The method works well for fields that ARE defined in the avro schema (i.e. returns mismatches); however, it doesn't indicate which fields are undeclared if I set `noUndeclaredFields` option to true and test a JSON with some fields that do not exist in the schema. All I get back inside `errorHook`  for 'path' is name of my Avro record which had the additional field(s) and a 'type' of Object, but no field names. 

Is there a way to see the exact field names inside 'path' which weren't specified when I call isValid?

Thanks!

**Comment by mtth** [comment]
Hey @nabeelz6. The `errorHook` exposes both the type and mismatched value; so you should be able to recover the information you like with a custom hook. Here's an example showing how it could work:

```javascript
const avro = require('avsc');

/** Hook which logs any mismatches, including extra record fields.*/
function errorHook(path, any, type) {
  let msg = `[${path.join('.')}]\t`;
  if (type.typeName === 'record')) {
    if (any !== null && typeof any == 'object') {
      const declared = new Set(type.fields.map(f => f.name));
      const extra = Object.keys(any).filter(n => !declared.has(n));
      msg += `extra fields (${extra.join(', ')})`;
    } else {
      msg += `not an object: ${any}`;
    }
  } else {
    msg += `not a valid ${type}: ${JSON.stringify(any)}`;
  }
  // Here, we just print the mismatches. It would be straightforward to return
  // them instead too (for example using a custom error).
  console.error(msg);
}

// A simple example to get some output.
const type = avro.parse(`array record { int foo; string bar; }`);
const invalidVal = [
  {foo: 1, bar: 'hi', baz: 'should not be there'}, // Invalid (extra field).
  {foo: 2, bar: 'hey'}, // Valid item.
  {foo: 3, bar: 3} // Invalid (wrong type for bar).
];
type.isValid(invalidVal, {errorHook, noUndeclaredFields: true});
```

If you run it, you'll see:

```
[0]         extra fields (baz)
[2.bar]     not a valid "string": 3
```

**Comment by nabeelz6** [comment]
Thanks @mtth for the quick response. That did the trick!
