### ISSUE TITLE
Error with logicalType

### ISSUE THREAD

**Issue by may-2015** [mtth/avsc#15]
**I tried run tis code:**

var avsc = require('avsc');
var utils = require('./node_modules/avsc/lib/utils.js');

var schema = {
  name: 'Transaction',
  type: 'record',
  fields: [
    {name: 'amount', type: 'int'},
    {name: 'time',  type: 'long', logicalType: 'timestamp-millis'}
  ]
};

var LogicalType = avsc.types.LogicalType;

function DateType(attrs, opts) {
	LogicalType.call(this, attrs, opts, [LongType]); // Require underlying `long`.
}
util.inherits(DateType, LogicalType);

DateType.prototype._fromValue = function (val) { return new Date(val); };
DateType.prototype._toValue = function (date) { return +date; };

var type = avsc.parse(schema, {logicalTypes: {'timestamp-millis': DateType}});

var transaction = {
  amount: 32,
  time: new Date('Thu Nov 05 2015 11:38:05 GMT-0800 (PST)')
};

var buf = type.toBuffer(transaction);
console.log("Buffer", buf);
var date = type.fromBuffer(buf).time; // `Date` object.
console.log("Oject", date);

**and get:**

C:\Program Files\Emscripten\emscripten\1.34.1\tests\may\test>node testLogicalTyp
e.js
C:\Program Files\Emscripten\emscripten\1.34.1\tests\may\test\node_modules\avsc\l
ib\schemas.js:2166
  throw new Error(f('invalid %s: %j', type, val));
        ^
Error: invalid "long": "2015-11-05T19:38:05.000Z"
    at throwInvalidError (C:\Program Files\Emscripten\emscripten\1.34.1\tests\ma
y\test\node_modules\avsc\lib\schemas.js:2166:9)
    at LongType._write (C:\Program Files\Emscripten\emscripten\1.34.1\tests\may\
test\node_modules\avsc\lib\schemas.js:477:5)
    at RecordType.writeTransaction [as _write] (eval at <anonymous> (C:\Program
Files\Emscripten\emscripten\1.34.1\tests\may\test\node_modules\avsc\lib\schemas.
js:1611:10), <anonymous>:5:6)
    at RecordType.Type.toBuffer (C:\Program Files\Emscripten\emscripten\1.34.1\t
ests\may\test\node_modules\avsc\lib\schemas.js:247:8)
    at Object.<anonymous> (C:\Program Files\Emscripten\emscripten\1.34.1\tests\m
ay\test\testLogicalType.js:31:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**What am I doing wrong?**

**Comment by mtth** [comment]
There was a typo in the documentation, the schema should be:

```javascript
var schema = {
  name: 'Transaction',
  type: 'record',
  fields: [
    {name: 'amount', type: 'int'},
    {name: 'time', type: {type: 'long', logicalType: 'timestamp-millis'}}
  ]
};
```

(The annotation should be on the type, not the field.)

Thanks for catching this!
