### ISSUE TITLE
forSchema throw "null" : "null" 

### ISSUE THREAD

**Issue by erdem333** [mtth/avsc#152]
Hello, 

I'm using this module to get encode my avro formated data. So I have the schema and try 
```
const v1 = avro.Type.forSchema(
 {
        'type': 'record',
        'name': 'xxxRecord',
        'namespace': 'test.data',
        'fields': [
          {
            'name': 'xxx',
            'type': 'long'
          },
          {
            'name': 'values',
            'type': {
              'type': 'array',
              'items': {
                'type': 'record',
                'name': 'xxxValues',
                'namespace': 'xxx.values',
                'fields': [
                  {
                    'name': 'yyy',
                    'type': [
                      'null',
                      'string'
                    ]
                  },
                  {
                    'name': 'ccc',
                    'type': [
                      'null',
                      'string'
                    ],
                    'default': 'null'
                  },
                  {
                    'name': 'ddd',
                    'type': [
                      'null',
                      'string'
                    ]
                  },
                  {
                    'name': 'fff',
                    'type': [
                      'null',
                      'string'
                    ]
                  },
                  {
                    'name': 'eee',
                    'type': [
                      'null',
                      'double'
                    ]
                  }
                ]
              }
            }
          }
        ]
      }
)
```
I got an error with 

> failed with Error: invalid "null": "null"

**Comment by mtth** [comment]
Default values are interpreted as JSON, so right now `ccc` has as default value the _string_ `'null'`, which isn't a valid value of type `null`. If you remove the quotes (`'default': null`), it should work as expected.

**Comment by erdem333** [comment]
Still doesn't work. I changed the `ccc` object to

```
{
                    'name': 'ccc',
                    'type': [
                      'null',
                      'string'
                    ],
                    'default': null
},
```
And get now 

> failed with Error: trailing data

>

**Comment by mtth** [comment]
Then it's likely one of three things is happening:

+ `m.message.value` contains more data than just the encoded value (for example, messages from Kafka typically [include a prefix](https://github.com/mtth/avsc/issues/22#issuecomment-166670111), or you might have more than one encoded value in the buffer).
+ The encoded value doesn't match your schema.
+ The buffer contains corrupt data (perhaps from an encoding error upstream).

It's hard to say for sure without knowing more about how the input data is generated. Unless you're able to decode it with another Avro library, it's probably not an issue with `avsc`.
