### ISSUE TITLE
limitation on string length

### ISSUE THREAD

**Issue by Rawan-Ramadan** [mtth/avsc#157]
I am having a simple schema like this 
```
const schema = {
  type: 'record',
  name: 'message',
  fields: [
    {name: 'id', type: 'int'},
       {name: 'description', type: 'string'},
  ],
};
const type = avsc.Type.forSchema(schema);
```
this works fine as long as the string is really short but once the number of characters slightly increase, it gives me an error.
 the the message is sent by another java module through kafka and if I tried to consume it using that java module it's de-serialized  properly but when I try to read it in my node module using 
` type.fromBuffer(buffer)`
it gives me 
RangeError: out of range index at node_modules\avsc\lib\utils.js
   ` this.buf.utf8Slice(pos, pos + len));`
So is there a limitation on the number of characters of the string type ? and how to fix such issue ?

**Comment by mtth** [comment]
How long are the strings that fail? The only relevant limit I'm aware of is that node buffers can contain at most ~1GiB. Can you share a sample failing data/schema combination?

**Comment by Patafix** [comment]
I have the exact same bug
