### ISSUE TITLE
potential precision loss

### ISSUE THREAD

**Issue by edi-bice** [mtth/avsc#159]
I keep getting 

Error: potential precision loss
    at LongType._read (/home/ebice/precog-rest/node_modules/avsc/lib/types.js:883:11)

even after following the instructions in Custom Long Types.

Here's my code

`var registry = {};

// https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types
const Long = require('int64-native');
const longType = avro.types.LongType.__with({
  fromBuffer: (buf) => { return new Long('0x' + buf.toString('hex')); },
  toBuffer: (n) => { return Buffer.from(n.toString().slice(2), 'hex'); },
  fromJSON: (obj) => { return new Long(obj); },
  toJSON: (n) => { return +n; },
  isValid: (n) => { return n instanceof Long; },
  compare: (n1, n2) => { return n1.compare(n2); }
});
const i64LongType = avro.Type.forSchema('long', {registry: {'long': longType}});

var BillyBob = avro.parse('./billybob.avsc', {registry: registry});`

**Comment by mtth** [comment]
The last line in your snippet uses an empty registry:

```javascript
var registry = {};

// https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types
const Long = require('int64-native');
const longType = avro.types.LongType.__with(/* ... */);

// This type can be used to serialize a single long using full precision.
const i64LongType = avro.Type.forSchema('long', {registry: {'long': longType}});

// This next type however can't: `registry` is empty.
var BillyBob = avro.parse('./billybob.avsc', {registry: registry});`
```

It looks like you'll just need to update the last line to be:
```javascript
var BillyBob = avro.parse('./billybob.avsc', {registry: {'long': longType}});`
```

**Comment by edi-bice** [comment]
Ah, okay for some reason I thought forSchema was doing just that. I guess it's not updating the registry.
