### ISSUE TITLE
push data in array of schema (stream)

### ISSUE THREAD

**Issue by poyaz** [mtth/avsc#160]
Hello

i have this schema:

`
{
    "type": "record",
    "fields": [
        {
            "name": "rowCount",
            "type": "int"
        },
        {
            "name": "fields",
            "type": {
                "type": "array",
                "items": {
                    "type": "record",
                    "fields": [
                        {
                            "name": "name",
                            "type": "string"
                        },
                        {
                            "name": "dataTypeID",
                            "type": "int"
                        }
                    ]
                }
            } 
        },
        {
            "name": "rows",
            "type": { 
                "type": "array",
                "items": {
                    "type": "array",
                    "items": [
                        "int",
                        "string"
                    ]
                }
            }
        }
    ]
}
`

and i want use **avro.createFileEncoder** to write stream or create write stream in http response

**First Question (writable):**
how can i push my data (select from database with stream) in schema keys **rows**?

like:
```
let encoder = avro.createFileEncoder('./file.avro', myAboveSchema);

// Stream data receive form database
// like encoder.write([3001, 'Ana']);
data.on('data', (row) => encoder.write(row.id, row.name));

encoder.end();
```

Sample data:

`
{
    rowCount: 11,
    fields: [
        {name: 'id', dataTypeID: 1},
        {name: 'name', dataTypeID: 2}
    ],
    rows: [
        [1, 'Alex'],
        [2, 'Taylor'],
        [3, 'Robert'],
        ...,
        [3000, 'Emma']
    ]
}
`

-----------------------------------

**Second question (readable): **

How to parse when receive large data (send request for give above data) in readable stream and use data?

**Comment by mtth** [comment]
Hi @pooya-az. Before getting into encoding and decoding, it looks like the record declared by your schema represents a collection of rows so you'd need to accumulate all rows in the `rows` field before encoding the record. Something like:

```javascript
const record = {rowCount: 0, fields: [], rows: []};
data // Your readable stream from the database IIUC.
  // Append each row to the record's `fields` and `rows` (assuming this is what you
  // want; feel free to adapt).
  .on('data', (row) => {
    record.fields.push({dataTypeID: row.id, name: row.name});
    record.rows.push([row.id, row.name]);
    record.rowCount++;
  })
  // When done, process the record.
  .on('end', () => {
    // Do some processing using `record`, for example write to an encoder, see just below.
  });
```

Now if you'd like to encode these records and write them to an HTTP response, you'll need to know what format the server expects. Assuming it expects an [Avro container file](https://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) you can use a [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts) as follows (this is what `createFileEncoder` uses under the hood):

```javascript
const req; // Your HTTP request.
// Create an encoder using your schema.
const encoder = new avro.streams.BlockEncoder(schema);
// Wire in the encoder to the HTTP request.
encoder.pipe(req);
// Now you can write the records described above to this encoder:
encoder.write({recordCount: 1, rows: [[1, 'foo']], fields: []});
encoder.write({recordCount: 2, rows: [[2, 'bar'], [3, 'baz']], fields: []});
// When done.
encoder.end();
```

To decode received data, assuming it's also in block container format, you can use a [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) very similarly:

```javascript
const res; // The HTTP response.
const decoder = new avro.streams.BlockDecoder();
res.pipe(decoder);
decoder.on('data', (record) => { console.log(record); }); // Or any other processing logic.
```

Hope this helps.

**Comment by pooya-az** [comment]
Ty for help me.

One question more, Can i push data to just **rows** in encoder format?

------------------------------
**Sample**

I know that's the problem, but I want something like this
```
const encoder = new avro.streams.BlockEncoder(schema);
encoder.write({recordCount: 3, rows: [[1, 'foo']], fields: []});
// My plan to push in rows
encoder.write.rows([2, 'bar']);
encoder.write.rows([3, 'baz']);

encoder.end();
```

**Comment by mtth** [comment]
You can if you update your schema to represent a single row. For example if you change it to:

```javascript
const rowSchema = {
  "type": "array",
  "items": { "type": "array", "items": [ "int", "string" ] }
};
```

Then you can achieve what you mention:

```javascript
const encoder = new avro.streams.BlockEncoder(rowSchema);
encoder.write.rows([2, 'bar']);
encoder.write.rows([3, 'baz']);
```

Note that since this changes the storage format, you'll likely have to also update the code which reads these files.
