### ISSUE TITLE
Resource pooling

### ISSUE THREAD

**Issue by stelcheck** [mtth/avsc#165]
Greetings,

I would love to be able to do resource pooling when using this library. More specifically:

  1. When encoding, to provide my own buffer to encode to
  2. When decoding, to provide my own object instance to write attributes to

I get the impression that the former may be doable by using `.encode` directly, but I do not see a mean to specify an object to decode onto.

**Comment by mtth** [comment]
Hi @stelcheck. You're exactly right, [`encode`](https://github.com/mtth/avsc/wiki/API#typeencodeval-buf-pos) will let you provide your own buffer to encode the data into. There isn't an equivalent when decoding since object creation in JavaScript is extremely fast (adding new fields to an existing object actually [slows down most runtimes](https://gist.github.com/twokul/9501770)); was there a particular use-case you had in mind?

**Comment by stelcheck** [comment]
Basically games. We have a game whereupon reception of messages, we want to update existing fields with the content of a message without having to create a new message instance (to avoid triggering GC every so often).

**Comment by mtth** [comment]
Decoding will end up creating garbage anyway (both by necessity if your type has arrays of different lengths for example and also for internal bookkeeping). I'd be surprised if this optimization had a material impact on GC pauses but you can try it relatively simply if your data is flat:

```javascript
/** Decode a _flat record_ into an existing object. */
function decodeInto(recordType, obj, buf, pos) {
  for (const field of recordType.fields) {
    if (pos < 0) {
      throw new Error('invalid buffer');
    }
    const {offset, value} = field.type.decode(buf, pos);
    obj[field.name] = value; // Overwrite `obj`'s previous value for the field.
    pos = offset;
  }
}
```

If your data is nested, it'll require a bit of work to extend the approach above (in particular, you'll have to decide how to handle any arrays and maps).

**Comment by stelcheck** [comment]
Interesting - I'll try that out and re-open the issue if I have any further questions or ideas.

Thank you for your help!
