### ISSUE TITLE
Upgraded from 5.1.1 to 5.2.3 - Now getting 'getUnderlyingType' does not exist on type 'LogicalType'

### ISSUE THREAD

**Issue by damonwildercarr** [mtth/avsc#166]
Apologies if this was covered previously. 

Here are the errors:

ERROR in src/app/pdpackage/avroparser/logicaltypes.ext.ts(19,28): error TS2339: Property 'getUnderlyingType' does not exist on type 'LogicalType'.
src/app/pdpackage/avroparser/logicaltypes.ext.ts(39,28): error TS2339: Property 'getUnderlyingType' does not exist on type 'LogicalType'.
src/app/pdpackage/avroparser/logicaltypes.ext.ts(70,28): error TS2339: Property 'getUnderlyingType' does not exist on type 'LogicalType'.
src/app/pdpackage/avroparser/logicaltypes.ext.ts(86,28): error TS2339: Property 'getUnderlyingType' does not exist on type 'LogicalType'.

This is the logical type definition:

----------------------------------------------

/* jshint node: true */

'use strict';

import * as avro from 'avsc';
import * as util from 'util';

const numOfMSInDay = 24 * 60 * 60 * 1000;
const epoch = new Date(1970, 1, 1, 0, 0, 0, 0).valueOf();

export class IsoDateTimeType extends avro.types.LogicalType {

    _fromValue(val) {

        const type = super.getUnderlyingType();

        if (val === undefined || val === null) {
            return undefined;
        }

        if (avro.Type.isType(type, 'long')) {
            return new Date(epoch + val);

        } else if (avro.Type.isType(type, 'string')) {
            return new Date(val);

        } else {
            return undefined;

        }
    }

    _toValue(date) {

        const type = super.getUnderlyingType();

        const d = date as Date;

        if (avro.Type.isType(type, 'long')) {
            return d.valueOf();

        } else if (avro.Type.isType(type, 'string')) {

            if (d.toISOString) { // did we successfully cast the string to a date?
                return d.toISOString();
            } else {             // if not we just return the string
                return d;
            }
        } else {
            return undefined;
        }
    }

    _resolve(type) {

        if (avro.Type.isType(type, 'long', 'string', 'logical:isodatetime')) {
            return this._fromValue;
        }
    }
}

export class IsoDateType extends avro.types.LogicalType {

    _fromValue(val) {

        const type = super.getUnderlyingType();

        if (val === undefined || val === null) {
            return undefined;
        }

        if (avro.Type.isType(type, 'int')) {
            const ms = (+val * numOfMSInDay);
            return new Date(epoch + ms);
        } else if (avro.Type.isType(type, 'string')) {
            return new Date(val);
        } else {
            return undefined;
        }
    }
    _toValue(date) {
        const type = super.getUnderlyingType();

        if (date === undefined || date === null) {
            return undefined;
        }

        const d = date as Date;

        if (avro.Type.isType(type, 'int')) {
            return Math.floor(d.valueOf() / numOfMSInDay);
        } else if (avro.Type.isType(type, 'string')) {
            const mm = d.getMonth() + 1;
            const dd = d.getDate();
            return (d.getFullYear().toString() + (mm > 9 ? '' : '0') + mm + (dd > 9 ? '' : '0') + dd) as string;
        } else {
            return undefined;
        }
    }
    _resolve(type) {
        if (avro.Type.isType(type, 'int', 'string', 'logical:isodate')) {
            return this._fromValue;
        }
    }
}

**Comment by damonwildercarr** [comment]
I believe I figured it out. I simply had to change all the instances of:

const type = super.getUnderlyingType();

to

const type = this.underlyingType;

Let me know if I missed something.

**Comment by mtth** [comment]
Yes, that's it. Thanks for bringing this up, I updated the [gists](https://gist.github.com/mtth/1aec40375fbcb077aee7) to avoid any confusion.
