### ISSUE TITLE
Schema Evolution with Renamed fields

### ISSUE THREAD

**Issue by dinesh-nadar** [mtth/avsc#169]
Below is a brief description of my issue

*Version being used* - 5.2.3

# Schema Description and Read/Write Action

```
const avro = require('avsc')

const personV1 = {
  name: 'PersonV1',
  type: 'record',
  fields: [{ name: 'name', type: 'string' }]
}
const personV5 = {
  name: 'PersonV5',
  type: 'record',
  fields: [{ name: 'address', type: 'string'}]
}

const writerV5 = () => {
  const personV5Type = avro.Type.forSchema(personV5)
  const randomPersonV5 = personV5Type.random()
  return personV5Type.toBuffer(randomPersonV5)
}
const readerV1 = buf => {
   const personV1Type = avro.Type.forSchema(personV1)
   return personV1Type.fromBuffer(buf)
}

const person = readerV1(writerV5())
console.log(person)
```

# Expected Result
Per my understanding of [Schema Evolution in Avro](https://avro.apache.org/docs/current/spec.html#Schema+Resolution), above code should result in an error given `if the reader's record schema has a field with no default value, and writer's schema does not have a field with the same name, an error is signalled.`

# Actual Result
Above Code runs with no issues and the `address` field in `personV5` is translated into the `name` field for `personV1`

Please let me know if you have any questions or you would need any more details!

**Comment by mtth** [comment]
Hi @dinesh-nadar, binary encoded Avro data don't have any information about the schema used to produce them; it's therefore impossible to know that the buffer produced by `writerV5` came from `personV5`. `personV1` and `personV5` happen to be binary-compatible so decoding works here but in general it will fail with a corrupt or truncated data error.

The correct way to handle schema evolution is always to create a resolver. If you run `personV1Type.createResolver(personV5Type)`, it will fail as expected with an error (not only is the `name` field missing a default, the record itself is missing an alias).
