### ISSUE TITLE
Problems accessing toBuffer from a schema loaded from an AVDL

### ISSUE THREAD

**Issue by appsolutegeek** [mtth/avsc#182]
Hi,

Can anyone help ?

I found an example for creating a buffer using a schema. This seems to work as I would expect.

  var obj = {"f1":"value1"};
  var schemaA = avro.parse({"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]});
  var dataA = schemaA.toBuffer(obj);
The above example's schema is a json file, I actually already have an avdl that has been provided to me. The file is valid. So I try the following

avro.assembleProtocol('./admin_events.avdl', function (err, protocol) {
  const service = avro.Service.forProtocol(protocol);

  let schemaB = avro.parse(service.getSchema());
  var dataB = schemaB.toBuffer(obj);
But this throws

  var dataB = schemaB.toBuffer(obj);
                      ^

TypeError: schemaB.toBuffer is not a function
So although SchemaA and SchemaB look similar in construct, the SchemaB doesn't have the toBuffer.

Can anyone else, I just need to be able to using the avdl file as these are provided to me.

Any help really appreciated

Thanks

**Comment by appsolutegeek** [comment]
Maybe I am calling it wrong ?

Basically I have an AVDL file, I also tried to convert it to a AVPR file and do the same but no luck.

**Comment by mtth** [comment]
Protocols are used to implement [services](https://github.com/mtth/avsc/wiki/Quickstart#services), which is what `avro.parse` returns when you give it an `.avpr` file (or the output of `assembleProtocol`. Each service _contains_ types, which you can use for decoding and encoding (though typically, you would just use the service's RPCs which take care of this).

You can access a service's types via its [`type`](https://github.com/mtth/avsc/wiki/API#servicetypename) and [`types`](https://github.com/mtth/avsc/wiki/API#servicetypes) attributes; for example:

```js
const service = avro.parse('my-service.avpr');
const type = service.type('my.RecordType'); // Any typed declared in the protocol.
const buf = type.toBuffer(foo); // Etc.
```

**Comment by appsolutegeek** [comment]
Hi,

Thanks for the reply. My AVPR files are provided to me from a 3rd party and they don't contain functions so I can't use the createServer etc.

I followed your example above but couldn't get it to work. I will place my real avdl here 

@namespace("com.example.admin")
protocol UserGroup {

/**
A code reprsenting the event Category
*/
  enum Category {
    ADMIN, WHATEVER
  }

```
/**
A code reprsenting the event type
*/
  enum EventCode {
    USER_GROUP_CREATED
  }

/**
An event containing information about the created user group
 */
  record UserGroupCreated {
    Category category = "ADMIN";
    EventCode eventCode = "USER_GROUP_CREATED";
    string eventDescription;
    long timestamp;

    string userId;
    string userGroupId;
  }
}

```

The only thing I am wanting to do is basically to encode/decode json objects - hence using the schema...

I tried this but service.type return undefined..

```
var avro = require('avsc');
avro.assembleProtocol('./a_events.avdl', function (err, protocol) {
  const service = avro.Service.forProtocol(protocol);

  const type = service.type("UserGroupCreated");
```

Am I doing something wrong ?

Thanks in advance.

**Comment by mtth** [comment]
Your protocol is namespaced under `com.example.admin` so switching to `service.type("com.example.admin.UserGroupCreated")` should work. In the future, in case you're not sure which name to use or which types are available, you can use `service.types()` which will return an object with all the named types declared in `service`.

**Comment by appsolutegeek** [comment]
Thanks for all the help, it's now working great!

I can do that standard toBuffer and fromBuffer and it throws errors if it doesn't conform to the schema.

Thanks once again.
