### ISSUE TITLE
Sending avsc buffer

### ISSUE THREAD

**Issue by bali182** [mtth/avsc#183]
I'm trying to request a very simple piece of avro encoded buffer from an express endpoint. Both sides (both client and server) can encode/decode data locally without any issues, but when trying to decode the data that the server serialized on the client I get raw bytes concatenated for string values. A minimal example

**Server**

```js
const express = require('express')
const avsc = require('avsc')

const Schema = avsc.Type.forSchema({
  type: "record",
  name: "Sample",
  fields: [{
    name: "message",
    type: "string",
  }]
})

const buffer = Schema.toBuffer({ message: 'Hello world!' })

const app = express()
app.get('/', (req, res) => res.status(200).end(buffer, 'binary'))
app.listen(7000, () => console.log('listening'))
```

**Client**

```js
const avsc = require('avsc')

const Schema = avsc.Type.forSchema({
  type: 'record',
  name: 'Sample',
  fields: [{
    name: 'message',
    type: 'string',
  }],
})

// OK, logs "Sample {message: "Hello world!"}"
console.log(Schema.fromBuffer(Schema.toBuffer({ message: 'Hello world!' }))) 

fetch('http://localhost:7000', { method: 'GET', mode: 'cors' })
  .then((res) => res.arrayBuffer())
  .then((arrayBuffer) => new Uint8Array(arrayBuffer, 0, arrayBuffer.byteLength))
  .then((buffer) => Schema.fromBuffer(buffer))
   // Not OK, logs "Sample {message: "72,101,108,108,111,32,119,111,114,108,100,33"}"
  .then((data) => console.log(data))
```

The interesting thing is both the locally serialized buffer, and the one received from the server look exactly the same (content, length, offset):

`Uint8Array(13) [24, 72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33]` 

But one gets deserialized correctly, the other won't. Could you help me see what am I doing wrong here?

**Comment by bali182** [comment]
Found a solution: Instead of using the `UInt8Array` constructor directly, using `Buffer.from(arrayBuffer)` seem to do the trick on the client.

**Comment by mtth** [comment]
You got it :). (`fromBuffer` expects a `Buffer`.)
