### ISSUE TITLE
Unable to edit metadata while writing a file

### ISSUE THREAD

**Issue by prateekkohli21** [mtth/avsc#185]
Hi,

If I serialize the data using Java API, I can add user defined properties in the metadata using the below method as a key value pair:

DatumWriter<GenericRecord> datumWriter = new GenericDatumWriter<GenericRecord>(schema);
DataFileWriter<GenericRecord> dataFileWriter = new DataFileWriter<GenericRecord>(datumWriter);
dataFileWriter.setMeta("schema.version", "v1");

Later I can use dataFileReader.getMetaString to get the value while reading the data file.

Is there any similar method by which I can add a user defined metadata inside the avro data file.
Curently I am using below code to write the data file:

var encoderUser = avro.createBlobEncoder(dataflow.types[10]);
encoderUser.write(validRecord);
encoderUser.end();
encoderUser.on('data', function (obj) {
		saveAs(obj, "simple-use-case.avro");
});

So, in the above code is there any way of writing some metadata as key value pair.

Regards,
Prateek Kohli

**Comment by mtth** [comment]
Hi Prateek, there's no such functionality currently but it does sound useful. I'll add an option to `createBlobEncoder` such that we can persist arbitrary metadata in the container file.

**Comment by prateekkohli21** [comment]
Ok, Thanks :)

**Comment by mtth** [comment]
Released `5.3.0` with a new [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts) `metadata` option which should let you do what you want :).
