### ISSUE TITLE
Decoding/encoding in-browser benchmark

### ISSUE THREAD

**Issue by jadbox** [mtth/avsc#19]

**Comment by mtth** [comment]
This would indeed be good to have. (Assuming you mean adding in-browser benchmarks.)

**Comment by jadbox** [comment]
>> Assuming you mean adding in-browser benchmarks
Yep, that's it

**Comment by mtth** [comment]
I created two browser benchmarks on jsPerf:

+ Decoding - http://jsperf.com/avsc-decode-coupon
+ Encoding - http://jsperf.com/avsc-encode-coupon

Results vary per browser (see the graphs in the benchmarks above) but roughly:

+ `avsc` is almost always faster than JSON (by 10 to 25%).
+ `avsc` is an order of magnitude faster than MessagePack and Protobuf.

**Comment by mtth** [comment]
Added relevant charts and links to the [Benchmarks page](https://github.com/mtth/avsc/wiki/Benchmarks).

**Comment by arminhaghi** [comment]
@mtth any chance you can produce a newer version of the browser benchmark?
