### ISSUE TITLE
Better error message when message fails to validate against the schema

### ISSUE THREAD

**Issue by Guru107** [mtth/avsc#190]
Currently, the error that is thrown when a message fails schema validation, contains just the value and type. E.g `invalid {"type":"array","items":"string"}: undefined`. It does not help in identifying the `key` for which this schema is failing. Adding the key to the error message would help in pinpointing the key.
For example, the error message can be `invalid key: {"type":"array","items":"string"}: undefined`

**Comment by mtth** [comment]
This is by design: the bookkeeping required for more extensive error reporting would slow down encoding. The recommended flow is to use `isValid`; you can take a look at https://github.com/mtth/avsc/issues/140 for more information.
