### ISSUE TITLE
Problems persisting LogicalType when imitating inheritance with @inline

### ISSUE THREAD

**Issue by snggeng** [mtth/avsc#194]
Hi, thanks for all the hard work on this library!

I've encountered some issues when trying to: 
propagate a `LogicalType` from a separate `.avdl` file into another `.avdl` file via `import` using the typehook defined [here](https://gist.github.com/mtth/c0088c745de048c4e466):
Example:
```
// schema/shared.avdl
@namespace("shared")
protocol shared {
  record Event {
    @logicalType("uuid")
    string id;
  }
}

// schema/subclass.avdl
protocol Subclass {
  import idl "shared.avdl";

  record SomeEvent {
    @inline(true)
    shared.Event event;
  }
}
``` 
The above IDL syntax generates the following output after parsing the schema using `avro.parse`:
```
{
"protocol": "Subclass",
      "types": [
        {
          "type": "record",
          "name": "Event",
          "fields": [
            {
              "type": {
                "logicalType": "uuid",
                "type": "string"
              },
              "name": "id"
            }
          ],
          "namespace": "shared"
        },
        {
          "type": "record",
          "name": "SomeEvent",
          "fields": [
            {
              "aliases": [],
              "name": "id",
              "order": "ascending",
              "type": "string"
            },
          ]
       }
     ]
}
```
In the above example my `LogicalType: uuid` gets constructed properly in the `shared` IDL schema, but when it gets parsed via the `typeHook` using `@inline` it loses the `"type": {"logicalType": "uuid","type": "string"}` type and is `"type": "string"` instead. 

I made some modifications to your github gist above to make it work, which I suspect may be the problem:
```
// typeHook function from https://gist.github.com/mtth/c0088c745de048c4e466
// typeHook used to simulate inheritance using @inline in IDL syntax
function typeHook(attrs, opts) {
  if (attrs.type !== 'record') {
    // Inlining only applies to records.
    return;
  }

  var fields = [];
  var namespace = opts.namespace;
  opts.namespace = attrs.namespace || opts.namespace;
  attrs.fields.forEach(function(fieldAttrs) {
    if (!fieldAttrs.type.inline) {
      // Default behavior.
      fields.push(fieldAttrs);

      return;
    }

    var type;
    if (typeof fieldAttrs.type.type === 'string') { /* changed to type.type to get the reference */
      // This is a reference, we must obtain the underlying type.
      var name = fieldAttrs.type.type; /* changed to type.type to get the reference */
      if (name.indexOf('.') !== -1 && opts.namespace) {
        name = opts.namespace + '.' + name;
      }

      type = opts.registry[name];

      if (!type) {
        // Just add the undefined reference so that `parse` can throw an
        // appropriate "undefined type" error.
        fields.push(fieldAttrs);
        return;
      }
    } else {
      type = avro.parse(fieldAttrs.type, opts);
    }

    if (type.typeName !== 'record') {
      throw new Error('only record fields can be inlined');
    }

    type.getFields().forEach(function(inlinedField) {
      // Note that we don't need to check for duplicates here since that will
      // be done by `parse` when it creates the type after the hook returns.
      fields.push({
        aliases: inlinedField.getAliases(),
        default: inlinedField.getDefault(),
        name: inlinedField.getName(),
        order: computeOrder(inlinedField.getOrder()),
        type: inlinedField.getType(),
      });
    });

    function computeOrder(order) {
      // If the inlined field has a descending order, we must "invert" all its
      // fields' orders. Similarly for ignored.
      if (order === 'ignore' || fieldAttrs.order === 'ignore') {
        return 'ignore';
      }
      switch (fieldAttrs.order || 'ascending') {
        case 'descending':
          return order === 'ascending' ? 'descending' : 'ascending';
        case 'ascending':
          return order;
        default:
          throw new Error('invalid order: ' + fieldAttrs.order);
      }
    }
  });

  opts.namespace = namespace;
  attrs.fields = fields;
}
```

For additional reference:
#### Logical Type construction
```
// logical-types.js
'use strict';

const avro = require('avsc');

class Uuid extends avro.types.LogicalType {
  constructor(attrs, opts) {
    super(attrs, opts, [avro.types.StringType]);
    this._validateAttrs(attrs);
  }

  _validateAttrs(attrs) {
    // eslint-disable-next-line
    const isValid = attrs.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);
    if (isValid) {
      this.value = attrs;
      return true;
    } else {
      throw new TypeError(`${attrs} is not of type UUID`);
    }
  }

  _fromValue(val) {
    return val;
  }

  _toValue(uuid) {
    return uuid.toString();
  }

}

module.exports = {Uuid};

```
#### Protocol Assembly
```
// schema/index.js
'use strict';

const avro = require('avsc');
const fs = require('fs');
const path = require('path');

const pathToAvdl = path.join(__dirname, 'subclass.avdl');

const importHook = function(fpath, kind, cb) {
  fpath = path.resolve(fpath);
  cb(null, fs.readFileSync(fpath, {encoding: 'utf8'}));
};

/*
 * the following code is synchronous as readFileSync is used for the hook
 * so `protocol` is guaranteed to be defined
 */
var protocol;
avro.assembleProtocol(pathToAvdl, {importHook}, function(err, p) {
  if (err) {
    err.message += `\n\nLocation: ${err.path}:${err.lineNum}:${err.colNum}\n`;
    err.stack = err.stack.replace(/^.*node_modules.*$\n/gm, '');
    err.stack = err.stack.replace(/^.*module\.js.*$\n/gm, '');
    throw err;
  }

  protocol = p;

});

module.exports = {protocol};
```
#### Service creation
```
// protocol.js
'use strict';

const avro = require('avsc');
const bunyan = require('bunyan');
const schema = require('./schema');
const types = require('./logical-types');

// logger
const log = bunyan.createLogger({
  name: 'avro',
  level: 'debug',
});

// typeHook function used to enable @inline
function typeHook(attrs, opts) { ... } // as above

// create service
const service = avro.Service.forProtocol(schema.protocol, {
  typeHook,
  wrapUnions: 'auto',
  errorStackTraces: true,
  logicalTypes: {
    uuid: types.Uuid,
  },
});

// inspect output
log.info(JSON.stringify(service.protocol, null, 2));
```

Am wondering if I didn't implement it properly, or is `LogicalType` inheritance not supported using `typeHook`s? Tried debugging directly with the source code but am still confused. Would appreciate your input on this issue! Thanks! Let me know if you need more information to reproduce.

**Comment by snggeng** [comment]
Also, I noticed that `avro.parse` is not documented. Has this been deprecated? It's still in the repo, and I couldn't find another function that comes close to what `parse` is doing. Let me know if you need help adding documentation for it, updating the gist examples, or if there is another function I should be using instead of `parse`.

**Comment by mtth** [comment]
Hi @snggeng! Thank you for the detailed information, it looks like there are a few things going on here:

The `@inline` annotation in the IDL spec is on the type rather than the field, which is probably not what you want: it ends up generating a key/value pair similar to `"type": {"type": "shared.Event", "inline": true}` which isn't standard Avro.

The only valid values for `"type"` keys are records with a standard type (`int`, `string`, `record`, etc.) or strings (references to named types); it's a bit confusing since the `"type"` key is overloaded but concretely: `"type": "shared.Event"` is valid, but not `"type": {"type": "shared.Event"}`. Fortunately, the fix is easy here, you just need to move the annotation after the type to fix this: `shared.Event @inline(true) event`. This will generate the following `avsc` protocol:

```js
{
  "protocol": "shared.Events",
  "types": [
    // ...
    {
      "type": "record",
      "name": "SomeEvent",
      "fields": [
        {
          "type": "shared.Event", // Note the reference here, correctly a string.
          "inline": true, // And the annotation directly on the field.
          "name": "event"
        }
      ]
    }
  ]
}
```

After this change, you will be able to use the type hook in [the gist](https://gist.github.com/mtth/c0088c745de048c4e466#file-inline-js) directly and it will correctly inline the parent record's fields. However you will notice that the logical type still doesn't apply: this is because we need to tweak its `_validateAttrs` method.

Right now the method gets called in the constructor, so only once when the type itself is created and `attrs` is equal to the type's _schema_ (so the `attrs.match` call will throw an exception since `attrs` is an object; this exception is what prevents the type from being applied); instead what you probably want is to validate values that to be deserialized/serialized by the type. We can do this just by calling the method in `_fromValue` and `_toValue` instead:

```js
class Uuid extends avro.types.LogicalType {

  constructor(attrs, opts) {
    super(attrs, opts, [avro.types.StringType]);
  }

  _validate(str) {
    // eslint-disable-next-line
    if (typeof str != 'string' ||
        !str.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i)) {
      throw new TypeError(`${attrs} is not of type UUID`);
    }
  }

  _fromValue(val) {
    this._validate(val);
    return val;
  }

  _toValue(str) {
    this._validate(str);
    return str;
  }
}
```

After both these changes, you should see the behavior you want:

```js
const service = avro.Service.forProtocol(protocol, {
  typeHook,
  wrapUnions: 'auto', // (You could omit this, it's the default.)
  errorStackTraces: true,
  logicalTypes: {
    uuid: Uuid,
  },
});

const eventType = service.type('shared.SomeEvent');
// The field is correctly inlined.
console.log(eventType.isValid({id: '5473dfac-81c8-4795-8125-6258c994463e'})); // True!
// And the logical type validates the UUID string as expected.
console.log(eventType.isValid({id: 'abc'})); // False.
```

Hopefully this makes sense; let me know if there is anything I can help clarify.

> Also, I noticed that `avro.parse` is not documented. Has this been deprecated?

Good eye; kind of. This method does too much IMHO and should not be used in production code; I would recommend instead using `assembleProtocol` (or `readProtocol` for simple use-cases), followed by `Type.forSchema`.  I still kept it as a convenience for quick scripts and for backwards compatibility but removed the documentation to reduce its visibility.

**Comment by snggeng** [comment]
Hi @mtth  thank you so much for taking the time to look through this issue and answer my question. It was very helpful! Everything makes sense now that you've explained it so well. 

And I agree, `avro.parse`should not be used in production. Have had no issues using `assembleProtocol` for most cases where I would use `parse` and I'll look into the different use-cases for when I should opt for `readProtocol` + `Type.forSchema` vs `assembleProtocol` while I continue using this library. Thanks again for taking the time to answer my question, I really appreciate it!

**Comment by mtth** [comment]
Glad I could help :).
