### ISSUE TITLE
No way to encode nullable and truly 64-bit longs?

### ISSUE THREAD

**Issue by dvisztempacct** [mtth/avsc#201]
Hi,

I am both an Avro and Avsc noob, so please excuse me if I'm completely wrong! (In fact I would love to hear that I'm completely wrong!)

I've been trying encode a long using npm's `long` package. Following examples in Avsc's documentation, everything works perfectly.

However, when my long is "optional" (by optional here I mean `type:["null","long"],default:null`) there's this extra check that happens in avsc that can bypass the validation and encoding behavior of any custom types in my type registry. Each incoming value to be encoded into an unwrapped union is first checked against this:

https://github.com/mtth/avsc/blob/776d9e65178a152ccb849e07bde7bf8d019152ab/lib/types.js#L3011-L3031

This makes it impossible to, for example, submit a Javascript `object`-typed value for encoding for the "optional long" Avro type, even if the `long` type in my type registry is perfectly capable of handling such a value.

This also means that if I decode an "optional long" and get back an instance of `Long` per my registry's `long` implementation, I won't be able to re-encode the resulting document!

Is there any way to override this behavior?

If not, could this be considered as a valid feature request?

Thanks!

**Comment by mtth** [comment]
Hey @dvisztempacct, thank you for the detailed explanation. This actually wasn't supported but should be starting in `5.4.3`, just released! Let me know if this doesn't fully satisfy your use-case.

**Comment by dvisztempacct** [comment]
Wow that was really fast! Thanks!

I won't have time to test it in the next couple of days but I'll be sure to do so as soon as I can!

**Comment by dvisztempacct** [comment]
Was there an extra step needed to get it to work?

I just tried upgrading and re-ran my existing code and got this error:

`│Error: invalid ["null","abstract:long"]: {"low":10397165,"high":0,"unsigned":false}`

Which looks awfully familiar except for the new `abstract:long` type in there!

Thanks again!

**Comment by dvisztempacct** [comment]
It was just a mistake I made. Thanks for such a prompt fix! Sorry for leaving this thread hanging!
