### ISSUE TITLE
Error RangeError: out of range index

### ISSUE THREAD

**Issue by cmarkowitz88** [mtth/avsc#204]
I'm sure that this specific issue is not an AVSC issue, just my misunderstanding of the library. 
I'm trying to decode a message encoded as an Object Container File. I'm using the blockDecoder and when I attempt to decode the message I'm getting a Error RangeError: out of range index.

 const decoderOptions = {codecs:'null', codec:'null', readerSchema:schema};
        const decoder =  new avro.streams.BlockDecoder(/*decoderOptions*/);
        
        
          decoder.on('metadata', function(metadata: any){
                console.log(metadata);

          });
          decoder.on('data', (data: any) => {console.log(data) });
          decoder.on('error', (error: Error) => console.log(error));
          decoder.on('end', () => console.log("Done"));
    
          try {
            decoder.write(buffer);
            
          } catch (e) {
                console.log(`Error ${e}`)
          }
          decoder.end();

**Comment by cmarkowitz88** [comment]
Adding sample message:
"Objavro.schema�{"type":"record","name":"test","namespace":"test","fields":[{"name":"Id","type":"string"}]}avro.codecnull��L&��a0���984856��L&��a0���"

**Comment by mtth** [comment]
Hey @cmarkowitz88, can you attach a full stack trace and a hex-encoded version of your message? You also shouldn't need to specify any options (or only the `readerSchema` if you are reading with a different schema than the one already encoded in the container file).

**Comment by cmarkowitz88** [comment]
Thanks so much Matthieu. Do u want the acronym encoded message from Kafka in hex?

**Comment by mtth** [comment]
> Now for the BlockDecoder, I was using this as an example and am confused on how it's actually working. What is actually emitting the message to the decoder?

The `.end(buf)` call writes `buf` (a buffer containing an entire object container) to the decoder, then closes it.

> I'm assuming you're asking for the encoded message in hex?

Yes. (Since it's not a text-friendly format, bytes get mangled otherwise.)

The stack trace looks different from the range error in the title; are you `end`ing the decoder multiple times?

**Comment by cmarkowitz88** [comment]
I was calling buffer.write and buffer.end. I removed the additional write call, however I'm still getting the same error. Here's the new stack trace:

RangeError: out of range index
    at Buffer.copy (buffer.js:602:18)
    at Tap.readFixed (node_modules/avsc/lib/utils.js:545:12)
    at Tap.readBytes (node_modules/avsc/lib/utils.js:562:15)
    at BytesType._read (node_modules/avsc/lib/types.js:1097:57)
    at MapType._read (node_modules/avsc/lib/types.js:1801:25)
    at RecordType.readHeader [as _read] (eval at RecordType._createReader (node_modules/avsc/lib/types.js:2248:10), <anonymous>:6:8)
    at BlockDecoder._decodeHeader (/node_modules/avsc/lib/containers.js:177:28)
    at BlockDecoder._write (node_modules/avsc/lib/containers.js:212:13)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)

**Comment by cmarkowitz88** [comment]
I was able to resolve this issue. As I suspected it had nothing to do with the avsc library.
My encoding type on my kafka consumer group was not being set correctly. As a result I believe that the message was being passed as utf8 instead of a buffer.

**Comment by mtth** [comment]
Glad you were able to fix it! Thanks for the follow up.

**Comment by cmarkowitz88** [comment]
Hi Matthieu. Had a question related to using custom long types with a block decoder. Is it possible to use the custom long type with the block encoder? The topic that I'm listening to has multiple schema types. I'm getting a runtime error on one of the schemas that I need to ignore. I wasn't able to figure out a way to 'catch' the error in any of the block encoder emit methods. I would prefer to just ignore those messages, but am not able to catch the error **(Error: potential precision loss
    at LongType._read (node_modules/avsc/lib/types.js:892:11) ... etc)**. I wasn't sure if there was a way to catch the error and ignore it. Otherwise, I suppose I would need to implement the custom long type, even though I don't need to ever read that particular schema. Hopefully that makes sense.

Cheers.

**Comment by mtth** [comment]
You can use a custom long type with a `BlockDecoder` via its `parseHook` option, for example:

```js
const decoder = new avro.streams.BlockDecoder({
  parseHook: attrs => avro.Type.forSchema(attrs, {registry: {'long': myLongType}})
});
```

You can specify a schema parsed with a custom long type directly as first argument to `BlockEncoder` to use it for encoding.

If you don't care about reading these longs, you could just use a type which passes them through in a thin wrapper:

```js
/** Tiny wrapper class. */
class Long { constructor(buf) { this.buf = buf; } }

const myLongType = avro.types.LongType.__with({
  fromBuffer: buf => new Long(buf),
  toBuffer: val => val.buf,
  fromJSON: () => throw new Error('unsupported'),
  toJSON: () =>  throw new Error('unsupported'),
  isValid: val => val instanceof Long,
  compare: () => throw new Error('unsupported')
});
```

if you need to read them I would use a library to do the decoding/encoding for you, for example [this one](https://www.npmjs.com/package/long)

**Comment by RPS044** [comment]
@cmarkowitz88 @arminhaghi @mtth 

please help us and totally stucked. we use node js. we get error: **invalid union index: 4032 [object Object]"**

We are trying to decode the avro encoded messages using node operator.

Code:

const SDK = require("@sap/vflow-sub-node-sdk");
const operator = SDK.Operator.getInstance();

const avro = require('avsc');
const fs = require('fs');
// var unescapeJs = require('unescape-js');

operator.getInPort("input").onMessage((message) => {

//Read Schema
const schema = fs.readFileSync("schema.avsc", "utf-8");
//Parse schema
var type = avro.parse(schema);
//Create Buffer
var buffer = new Buffer.from(message.Body, 'binary');
//Remove magic Bytes and Decode message
try{
var decodedMsg = type.fromBuffer(buffer.slice(5));
operator.getOutPort("output").send(JSON.stringify(decodedMsg));
} catch (error) {
// Should be modified to make more meaningful
operator.getOutPort("error").send(JSON.stringify(error.message+' '+message));
}

});
