### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by Michael03** [mtth/avsc#206]
With the below im getting an error that the name doesn't exist. If i make the message object contain the namespace and do the same when reading it out it works but is that correct? Should i have to specify the namespace in the object im encoding?

```
const Avsc = require("avsc");

const avsc = {
  "type": "record",
  "name": "TestRecord",
 "namespace": "namespace.test",
  "fields": [
    {
      "name": "eventDetails",
      "type": [
        {
          "type": "record",
          "name": "Name1",
          "fields": [
            {
              "name": "NameA",
              "type": "string"
            }
          ]
        },
        {
          "type": "record",
          "name": "Name2",
          "fields": [
            {
              "name": "NameB",
              "type": "string"
            }
          ]
        }
      ]
    },
    {
      "name": "working",
      "type": [
        "string"
      ]
    }
  ]
};

const schema = Avsc.parse(JSON.stringify(avsc));

let message =   {
  eventDetails: {
    Name1: {
      NameA: "Name1AValue",
    }
  },
  working: "workingValue"
};
const buffer = schema.toBuffer(message);
let parsed = schema.fromBuffer(buffer);

console.log(parsed);
console.log(parsed.eventDetails);
console.log(parsed.eventDetails.Name1);
console.log(parsed.eventDetails.Name1.NameA);


```
Error: invalid ["namespace.test.Name1","namespace.test.Name2"]: {"Name1":{"NameA":"Name1AValue"}}

**Comment by mtth** [comment]
Hi @Michael03; yes, you'll need to specify the type's qualified name when it's included in a [wrapped union](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts) (there's a risk that unqualified names would conflict). If you don't have control over your input data, you can use [`clone`](https://github.com/mtth/avsc/wiki/API#typecloneval-opts)'s `qualifyName` option to do it for you:

```js
const invalid = {
  eventDetails: {
    Name1: {
      NameA: "Name1AValue",
    }
  },
  working: "workingValue"
};
const valid = schema.clone(invalid, {qualifyNames: true});
```

**Comment by Michael03** [comment]
Thats great 👍 Im assuming theres nothing to do the reverse when converting the data back to an object?

**Comment by mtth** [comment]
> Im assuming theres nothing to do the reverse when converting the data back to an object?

There isn't anything built-in. You could probably get something working using a [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) but I'm not sure I would recommend it.
