### ISSUE TITLE
Wiki Documentation Updates to Services

### ISSUE THREAD

**Issue by zilkey** [mtth/avsc#227]
In https://github.com/mtth/avsc/wiki/Quickstart there are 3 examples of clients:

- in-memory
- TCP
- HTTP

The in-memory examples work out-of-the-box, but the TCP and HTTP examples are missing the `buffering: true` option.

For HTTP, the example is currently:

```js
// Similarly, an HTTP client:
const client = service.createClient({transport: function (cb) {
  return http.request({method: 'POST', port: 8080})
    .on('response', function (res) { cb(null, res); })
    .on('error', cb);
}});
```

And I believe it should be:

```js
// Similarly, an HTTP client:
const client = service.createClient({buffering: true, transport: function (cb) {
  return http.request({method: 'POST', port: 8080})
    .on('response', function (res) { cb(null, res); })
    .on('error', cb);
}});
```

Similarly, the TCP example shows:

```js
// And create a matching client:
const client = service.createClient({transport: net.connect(24950)});
```

And it appears that should be:

```js
// And create a matching client:
const client = service.createClient({buffering: true, transport: net.connect(24950)});
```

Thanks for the excellent getting started guide!

**Comment by mtth** [comment]
Hi @zilkey, thanks for bringing this to my attention! Your observations are correct, I've updated the Wiki to match.
