### ISSUE TITLE
Unable to read serialized value 

### ISSUE THREAD

**Issue by rhari008** [mtth/avsc#230]
Hi,

I am trying to decode a message received on kafka listener. I had a look at one of the [issues](https://github.com/mtth/avsc/issues/204). My sample message is also pretty much similar to the one mentioned in the issue:

Adding sample message:
"Obj���avro.schema��{"type":"record","name":"test","namespace":"test","fields":[{"name":"Id","type":"string"}]}�avro.codec�null���L&��a0�������984856���L&��a0�����"

However, I am not able to use the decoder. The message received is basically base64 encoded. I decode it and then feed it to the decoder here. However, I get an error "Error: invalid magic bytes". Please could you help?

The kafka consumer has the encoding as encoding: 'buffer'. 

`consumerGroup.on('message', message => {
        console.log("Got this message "+message.value);
        console.log(" =================== ");
        // var base64Value = message.value.replace(/\"/g, "");
         var binary = Buffer.from(message.value, 'base64');
         var buff = Buffer.from(binary, 'binary');
         console.log(buff);
         decoder.on('metadata', function(metadata){
            console.log(metadata);

        });
        decoder.on('data', (data) => {console.log(data) });
        decoder.on('error', (error) => console.log(error));
        decoder.on('end', () => console.log("Done"));

        try {
            // decoder.write(buff);
            decoder.write(buff);
            
        } catch (e) {
                console.log(`Error ${e}`)
        }`

**Comment by mtth** [comment]
Hey. This might be due to an encoding issue upstream; can you share the first few bytes in hex of the _raw_ file (after base 64 decoding)? Valid container files are expected to start with [`4f 62 6a 01`](http://avro.apache.org/docs/current/spec.html#Object+Container+Files) and it looks like your data doesn't.

**Comment by rhari008** [comment]
Hi,

Its just like the one mentioned in the issue: https://github.com/mtth/avsc/issues/204#issuecomment-422946581

**Comment by mtth** [comment]
We can't see the actual bytes there, same as in your original message: non-printable characters are replaced by � so it's unclear what your code actually reads. If you call `.toString('hex')` on the buffer and paste the output here, we'd be able to see exactly what the buffer contains.
