### ISSUE TITLE
undefined null issue verson 5.2 & 5.4

### ISSUE THREAD

**Issue by NSWIDER** [mtth/avsc#231]
In our scenario there are two conflicting lines of code pertaining to default values.  This code is from version 5.4.7
2798  if (value !== undefined) {

1379  if (val === null || wrap === 3) {

if we change 2789 to

 if (value) { 

everything seems to be working.

**Comment by NSWIDER** [comment]
should we set default to null or undefined?

**Comment by mtth** [comment]
You can do both but they mean different things:
 
+ `null` is a valid default (defaults need to be [valid JSON-ish encodings](http://avro.apache.org/docs/current/spec.html#schema_record)), and using it will make the field "optional".
+  `undefined` means that the field has _no_ default (it's equivalent to omitting the key altogether in the schema).

More concretely:

  ```javascript
  const optionalFieldType = Type.forSchema({
    type: 'record',
    name: 'Foo',
    fields: [
      {name: 'foo', type: ['null', 'int'], default: null},
    ],
  });

  console.log(optionalFieldType.isValid({})); // true

  const requiredFieldType = Type.forSchema({
    type: 'record',
    name: 'Foo',
    fields: [
      {name: 'foo', type: ['null', 'int'], default: undefined},
    ],
  });
  
  console.log(requiredFieldType.isValid({})); // false: the field `foo` is missing
  ```

Does this make sense?

**Comment by NSWIDER** [comment]
ok thanks for that info. I think we had to go to undefined because of a default 0 value where type is null.  This works on the java avro.  I guess there is no validation for avro schemas? Here is the setup  that causes the error...
const badDefaultIntegerValue? = Type.forSchema({
  type: 'record',
  name: 'Foo',
  fields: [
    {name: 'foo', type: ['null', 'int'], default: 0},
  ],
});

**Comment by mtth** [comment]
This schema is invalid (and `avsc` will correctly reject it): union defaults should [match the first branch](http://avro.apache.org/docs/current/spec.html#schema_record) but `0` is not a valid `null`. Removing the default will work otherwise you can also fix it just by switching the order of the types in the union:

```javascript
const goodIntegerDefault = Type.forSchema({
  type: 'record',
  name: 'Foo',
  fields: [
    {name: 'foo', type: ['int', 'null'], default: 0}, // Note the order of the types.
  ],
});
```
