### ISSUE TITLE
Complex type using map never decodes

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [mtth/avsc#232]
I am prototyping with AVRO ("avsc": "^5.4.7") testing objects that will have some fields, defined as maps, that will be able to hold variable changing data and the majority that will not. I am able to validate objects and generate file but upon decoding it never gets a response with anything but the schema. Below I have included the schema and code example. I have been looking for some good examples and explanations around the capabilities and limitations of maps and have not found too many so any help is much appreciated.

Originally I was going to use the auto schema generation and found information in another issue around creating a [naming hook](https://github.com/mtth/avsc/issues/108) but that did not work completely in my case. It appeared to call the hook but not all the values I will open another issue around that since it's not exactly relevant to this issue but it was the route I tried first.

**Schema (event.avsc) using map**

````json
{
    "namespace": "event.avro",
    "type": "record",
    "name": "Event",
    "fields" :[
        {"name": "message", "type": "string"},
        {"name": "category", "type":  {"type": "map", "values": "string"}}
    ]
}
````

**Sample Code using map**

````js
const avro = require('avsc');
const fs = require('fs');
const schema = fs.readFileSync("./event.avsc").toString("utf8");
const type = avro.Type.forSchema(JSON.parse(schema));

const value = {
    message: "yeah",
    category: {
        someField: "test",
        anyfield: "test"
    }
};

console.log(type.isValid(value));  //evaluates true

if (fs.existsSync("./object.avro")) {
    fs.unlinkSync("./object.avro");
}

const writer = avro.createFileEncoder("./object.avro", type);

writer.end(value);
writer.destroy();


avro.createFileDecoder('./object.avro')
    .on('metadata', function (type) {
        console.log(type);  //gets called
    })
    .on('data', function (record) {
        console.log(JSON.stringify(record)); //doesn't get called
    })
    .on('error', function (err) {
        console.log("err"); //doesn't get called
    })
    .on('end', function (args) {
        console.log("end"); //gets called
    });
````

**Schema using Wildcard Example**
[Reference: Issue 215](https://github.com/mtth/avsc/issues/215)

````json
{
    "namespace": "event.avro",
    "type": "record",
    "name": "Event",
    "fields" :[
        {"name": "message", "type": "string"},
        {"name": "category", "type":  "wildcard"}
    ]
}
````

**Sample Code with Wildcard Example**
[Reference: Issue 215](https://github.com/mtth/avsc/issues/215)

````js
const avro = require('avsc');
var fs = require('fs');

class WildcardType extends avro.types.LogicalType {
    _fromValue(val) {
        return val;
    }
    _toValue() {
        return {};
    } // Pretend always empty.
}


const wildcard = avro.Type.forSchema({
    type: 'record',
    fields: [],
    logicalType: 'event.avro.wildcard'
}, {
        logicalTypes: {
            wildcard: WildcardType
        }
    });

const schema = fs.readFileSync("./event.wildcard.avsc").toString("utf8");
const type = avro.Type.forSchema(JSON.parse(schema), { registry: { "event.avro.wildcard": wildcard } });

const value = {
    message: "yeah",
    category: {
        someField: "test",
        anyfield: "test"
    }
};

console.log(type.isValid(value));
if (fs.existsSync("./object.avro")) { fs.unlinkSync("./object.avro"); }
const writer = avro.createFileEncoder("./object.avro", type);

writer.end(value);
writer.destroy();


avro.createFileDecoder('./object.avro')
    .on('metadata', function (type) {
        console.log(type);
    })
    .on('data', function (record) {
        console.log(JSON.stringify(record));
    })
    .on('error', function (err) {
        console.log("err");
    })
    .on('end', function (args) {
        console.log("end");
    });
````

**Comment by jwyglendowski-precisionlender** [comment]
After looking at the raw encoding files there is nothing written after the sync marker. If I take the same schema, generate objects using the C# library and then create an avro file, the resulting file can be read using avsc. So for some reason the I can not create a new avro file using the same schema.

**Comment by mtth** [comment]
Thank you for the detailed report. I am curious if this is happening because you are reading the file before the writer is done. Can you try tweaking your code to match the example below?

```javascript
const writer = avro.createFileEncoder('./object.avro', type)
  .on('finish', () => {
    // The writer is done writing when we get here.
    avro.createFileDecoder('./object.avro')
      .on('data', (record) => { console.log(record); });
  });
writer.end(value);
// No need to destroy.
```

**Comment by jwyglendowski-precisionlender** [comment]
@mtth Thanks for taking the time to point that out I really appreciated it. It seems that if I never called destroy then it would have flushed all the data to disk without issue. I thought I was missing something simple and as you pointed out I was. Streams are powerful things especially when you use them correctly :). Callbacks get me again :)

Have a good weekend and once again thanks for all your help. It's people like you that make this world a better place. Working on open source projects is a thankless job sometimes but I just wanted you to know there are people out here that really appreciate it.
