### ISSUE TITLE
Evolution with custom Long Type does not work with the latest version

### ISSUE THREAD

**Issue by hapialex** [mtth/avsc#237]
Take the example code given in https://github.com/mtth/avsc/issues/143

With the latest version 5.4.10, this fails in createResolver.  It works perfectly fine with 5.1.2 so it looks like there is a regression.  

Note that in the previous issue, it failed in 'fromBuffer'.  Now it fails in 'createResolver' so it's not the same bug.

Thanks for a great library!

**Comment by hapialex** [comment]
It looks like the problem is here:

AbstractLongType.prototype._update = function (resolver, type) {
  var self = this;
  switch (type.typeName) {
    case 'int':
      resolver._read = function (tap) {
        return self._fromJSON(type._read(tap));
      };
      break;
    case 'abstract:long':   // ========= Needs this line?
    case 'long':
      resolver._read = function (tap) { return self._read(tap); };
  }
};

**Comment by mtth** [comment]
Thanks for reporting this and suggesting a (correct!) fix. Updated version released as `5.4.11`.

**Comment by hapialex** [comment]
Thanks for the quick turnaround!
