### ISSUE TITLE
Promise support in RPC

### ISSUE THREAD

**Issue by tinchoz49** [mtth/avsc#240]
Hi @mtth, first of all, awesome work you've been doing here.

I want to ask you: what do you think about provide promise support for the RPC implementaton?

Something like:

```javascript
const server = service.createServer()
  .onHello(async function (name) {
    await delay()
    return `hello ${name}`
  });

const client = service.createClient({buffering: true, server})

const result = await client.hello('martin');
```

**Comment by mtth** [comment]
Hi @tinchoz49. Promise-support is definitely worth having. It's currently supported via a separate library--[`verdon`](https://github.com/mtth/verdon)--to allow `avsc` to remain compatible with pre-promise versions of node.

Usage is very simple, you just need to call `verdon.promisifyAll(avro.Service)`:

```javascript
const avro = require('avsc');
const {promisifyAll} = require('verdon');
const Promise = require('bluebird');

// Enable promisified client and servers for all services.
promisifyAll(avro.Service);

const service = avro.Service.forProtocol({
  protocol: 'HelloService',
  messages: {
    hello: {
      request: [{name: 'name', type: 'string'}],
      response: 'string',
    },
  },
});

const server = service.createServer()
  .onHello(async function (name) {
    await Promise.delay(1000);
    return `hello ${name}!`;
  });

const client = service.createClient({buffering: true, server});

async function main() {
  const result = await client.hello('Martin');
  console.log(result); // Hello Martin!
}

main();
```

In the long run, I'm hoping to release a revamped RPC API as [`@avro/services`](https://www.npmjs.com/package/@avro/services) with built-in promise support. It's still under development though, so the above approach is probably better to avoid breaking changes.

**Comment by tinchoz49** [comment]
Hi @mtth ! thank you so much for the help! The verdon util is enough for me meanwhile.

The branch `packages` seems to be a good direction.

Do I close the issue?

**Comment by mtth** [comment]
Yes, unless you have more questions :).
