### ISSUE TITLE
Handling corrupt arvo exceptions

### ISSUE THREAD

**Issue by InteliCare** [mtth/avsc#242]
We are using avsc to both encode and decode arvo files. The encoding appears to have become corrupt on occasion possibly due to missing/bad data when creating the files. The files are then uploaded to Azure blob storage. This becomes a problem when trying to retrieve the files as they are being streamed one by one from the blob storage and the function that does this appears unable to catch the error generated by the corrupt file. If we could catch this error then we would be able to skip the file and continue on with the next one.

We are currently using avsc 5.4.11 and the following code snippet to decode:

        const stream = blobService.createReadStream(container, filename, (err) => {
          if (err) {
            pipeCallback(err);
          }
        });

        stream.on('error', (error) => {
          pipeCallback(error);
        })
        const decoder = new avscStreams.BlockDecoder();
        decoder.on("data", (chunk) => {
          try {
            output.push(JSON.stringify(chunk)); //using string buffer
          } catch (error) {
            pipeCallback(error);
          }
        });
        decoder.on("end", () => {
          pipeCallback();
        })
        decoder.on('finish', () => {
          pipeCallback()
        });
        decoder.on("error", (error) => {
          pipeCallback(error);
        })
        stream.pipe(decoder);

Is there any way to catch the errors generated by a corrupt avro such as this:

avsc\lib\utils.js:613
    return this.buf.utf8Slice(pos, pos + len);
                    ^
RangeError: out of range index

Thanks

**Comment by mtth** [comment]
`5.4.12` emits corrupt data errors on the decoder, can you upgrade and see if it works for your use-case?

**Comment by InteliCare** [comment]
Yes that solves our issue.
Thank you!
