### ISSUE TITLE
Error: invalid union index: 2

### ISSUE THREAD

**Issue by gzunigaskyjack** [mtth/avsc#245]
Hello all,

I have recently started working with avro and I ran into this error at my first attempt of reading a Kafka message.

Could anybody please shed some light on this error? I cannot seem to fine any information either here or anywhere else. I read about unions and they are defined just fine in the schema. But what is index referring to?

Even a general idea of what it could mean would help.

Thank you very much.

**Comment by mtth** [comment]
Hi @gzunigaskyjack, this means the encoded data doesn't match the schema you are decoding it with. This is typically caused by a prefix in the data or upstream corruption; https://github.com/mtth/avsc/issues/241 would be a good read for the former and https://github.com/mtth/avsc/issues/204 for the latter.

**Comment by gzunigaskyjack** [comment]
Hello, thank you for your reply!

Well, you were right. The problem was that our node implementation of Kafka did not support LZ4 compression and that is how data was being compressed by out client. Therefore, by the time messages were passed to avsc, of course, they did not match the schemas.

We tried another Kafka library and avsc had no issues decoding or encoding messages.

Thank you!

**Comment by mtth** [comment]
Great to hear - thanks for the update!

**Comment by virusmiha** [comment]
Hallo! Installing lz4 didn't help. But the problem was that I had mbstring.overload = 2 on my node when 0 is required

**Comment by RPS044** [comment]
@virusmiha @mtth @gost  is it solved?

invalid union index: 4032 [object Object]"

**Comment by RPS044** [comment]
@virusmiha @mtth  please help us and totally stucked. we use node js. we get error: invalid union index: 4032 [object Object]"

We are trying to decode the avro encoded messages using node operator.


**Code:**

const SDK = require("@sap/vflow-sub-node-sdk");
const operator = SDK.Operator.getInstance();

const avro = require('avsc');
const fs = require('fs');
// var unescapeJs = require('unescape-js');

operator.getInPort("input").onMessage((message) => {

//Read Schema
const schema = fs.readFileSync("schema.avsc", "utf-8");
//Parse schema
var type = avro.parse(schema);
//Create Buffer
var buffer = new Buffer.from(message.Body, 'binary');
//Remove magic Bytes and Decode message
try{
var decodedMsg = type.fromBuffer(buffer.slice(5));
operator.getOutPort("output").send(JSON.stringify(decodedMsg));
} catch (error) {
// Should be modified to make more meaningful
operator.getOutPort("error").send(JSON.stringify(error.message+' '+message));  
}

});
