### ISSUE TITLE
Annotations on unions.

### ISSUE THREAD

**Issue by graham-fennell** [mtth/avsc#247]
Just a very quick question to ask if there is a reason that annotations are not supported on unions? I spotted that there is an explicit check in the `specs.js` file for this (line 450):

`throw new Error('union annotations are not supported');`

Any insights that you may have would be greatly appreciated.

Cheers,

graham.

**Comment by mtth** [comment]
Hi. This is because unions are represented using arrays in JSON schemas and we are not be able to encode their annotations.

For example we can serialize an annotation on a record:
```
@myAnnotation(true)
record Foo {
  int foo;
}
```
Since it becomes a property on the type's object: `{"type": "record", "name": "Foo", "fields": [{"name": "foo", "type": "int"}], "myAnnotation": true}`. But it's not possible to the same for a union:

```
@myAnnotation(true) // Can't be encoded.
union { int, string }
```
Because it's simply encoded as `["int", "string"]`.

**Comment by graham-fennell** [comment]
Hi Matthieu,

Thanks for the quick reply and detailed response. :+1:

Just wondering would it make sense to maybe have a "strip annotations", or similar, parameter available in the options (of `assembleProtocol`), with perhaps a warning passed through the callback? This would allow parsing of the IDL file to continue with the knowledge that the union annotation will not available.

Thanks again for the great work on the package!

**Comment by mtth** [comment]
Could you tell me more about your use-case? There might be another way to achieve what you are trying to do. I am reluctant to add an option for this since it seems like a uncommon need (and adding properties to JavaScript arrays feels slightly dirty).

**Comment by graham-fennell** [comment]
At the moment I'm consuming some third party `avdl` files to validate that the types generated by my code are in fact valid for that particular schema.

Unfortunately the third party `avdl` files contain unions with annotations attached (which I'm commenting out for the meantime) and I'll like to be able to call and have the `assembleProtocol` method complete, knowing that the annotations are missing for unions, as I'm only interested in the type validation aspect.

Absolutely no worries if you'd rather not add a fairly edge case processing need, I'm more than happy to pre-process the `avdl` files to eliminate the troublesome annotations. :+1:

**Comment by mtth** [comment]
I see. Thanks for the context.

> Absolutely no worries if you'd rather not add a fairly edge case processing need, I'm more than happy to pre-process the avdl files to eliminate the troublesome annotations.

I think that would be best for now, until there is evidence this is needed more widely or the spec allows it. Apologies for the inconvenience...

**Comment by graham-fennell** [comment]
No worries at all, completely understand. Thanks again for all your work on the package.
