### ISSUE TITLE
Strange data after toBuffer

### ISSUE THREAD

**Issue by GusPr** [mtth/avsc#249]
Hi! I tried the example code below and the data produced ended up to be a string "CATAlbert". Something I'm doing wrong here?

PS, node-rdkafka is used here to create a Kafka producer.

````
const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: 'string'},
    {name: 'name', type: 'string'}
  ]
});

const buf = type.toBuffer({kind: 'CAT', name: 'Albert'});
producer.produce(topic, -1, buf, 1);
````

**Comment by mtth** [comment]
I suspect this is an issue with how you have configured your producer. Unfortunately I am not familiar enough with `node-rdkafka` to be able to help you debug further. [`kafka-avro`](https://github.com/waldophotos/kafka-avro) might be a good place to start; IIRC it integrates `node-rdkafka` with `avsc`.
