### ISSUE TITLE
extractFileHeader blocks indefinitely if file is empty

### ISSUE THREAD

**Issue by hixus** [mtth/avsc#250]
I have file validation function which uses the extractFileHeader internally. There was a case where file was empty and program was blocked indefinitely. 

extractFileHeader function has a while loop that blocks until 'size' is read. I think it should check that if the file is less than 'size' it will error.

**Comment by mtth** [comment]
Fixed in https://github.com/mtth/avsc/commit/7cd33258aef29df21abb012c596c594bfbdf1d1c and released in `5.4.13`.
