### ISSUE TITLE
Browser service client example

### ISSUE THREAD

**Issue by ctusch** [mtth/avsc#251]
Hey! I haven't been able to find a full example of how to call a service from within a browser. Do I need to implement my own transport?

**Comment by mtth** [comment]
Yes. There is unfortunately no guide for this currently, but there a few integrations which could help you get started depending on your setup. For example:

+ If you want to communicate over HTTP directly, take a look at [`verdon`](https://www.npmjs.com/package/verdon)'s `Proxy` class. [This test](https://github.com/mtth/verdon/blob/45b20c9069de38050009134d9c29e6009bae9486/test/test-proxy.js#L132) gives an idea of how to listen to POST requests; you'll just need to emit a similar AJAX request using your preferred client-side library.
+ If you are considering WebSockets, take a look at [this example](https://github.com/mtth/avro-webpack-loader/tree/master/examples/link-service). You might also be interested in the loader itself if you use Webpack.
