### ISSUE TITLE
Lost of Doc information

### ISSUE THREAD

**Issue by Ken-LiuL** [mtth/avsc#253]
It seems doc information would be lost, when some schema like
` {
    "type": "record",
    "name": "SimpleSchema",
    "namespace": "examples",
    "doc": "this is a test schema",
    "fields": [{
        "name": "name",
        "type": "string",
        "doc": "this is the name",
        "default": ""
    }]`
is parsed

**Comment by mtth** [comment]
Can you clarify which information is lost?

Using your example:

```javascript
let attrs; // Your schema above.

const type = avro.Type.forSchema(attrs);
console.log(type.doc); // this is a test schema 
console.log(type.field('name').doc); // this is the name
```

**Comment by Ken-LiuL** [comment]
oh, I see,  but when I  console.log(type), the result will lose the doc information,

**Comment by mtth** [comment]
That's expected. In general, you shouldn't expect an object's [`inspect`](https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects) method to return all information about it.

Note that for your particular use-case, you can export the docs simply by outputting a type's [`schema`](https://github.com/mtth/avsc/wiki/API#typeschemaopts):

```javascript
console.log(type.schema({exportAttrs: true});
```

Output:
```sh
{ name: 'examples.SimpleSchema',
  type: 'record',
  fields:
   [ { name: 'name',
       type: 'string',
       default: '',
       doc: 'this is the name' } ],
  doc: 'this is a test schema' }
```
