### ISSUE TITLE
Better Error Hint for Missing Field

### ISSUE THREAD

**Issue by Ken-LiuL** [mtth/avsc#254]
when there is a missing field  in the data to be serialized , an error like below will be thrown, but it is too obscure, firstly you do not know it is caused by missing field in the data, secondly you do not know which field is missing.

`
Error: invalid "string": undefined
    at throwInvalidError (/Users/pengkunliu/Workspace/cn-eventcollector-js/node_modules/avsc/lib/types.js:3024:9)
`

**Comment by mtth** [comment]
This is by design: the bookkeeping required for more extensive error reporting would slow down encoding. The recommended flow is to use `isValid`; take a look at #140 for an example and more context.
