### ISSUE TITLE
question: do you have more complex Avro data file examples?

### ISSUE THREAD

**Issue by RandomFractals** [mtth/avsc#255]
just an FYI, I am using your lib in Data Preview  🈸 vscode ext: 

https://github.com/RandomFractals/vscode-data-preview

have a poke at it. I'd like to beef up this sample /data/avro part in that repo: 

https://github.com/RandomFractals/vscode-data-preview/tree/master/data/avro

also, whenever you decide to put out powered by/featured Avro tools page, would be nice to see our data preview ext. for devs who code there too!

**Comment by mtth** [comment]
(The [`etc/schemas/`](https://github.com/mtth/avsc/tree/master/etc/schemas) folder has a selection of schemas which might be helpful too. They can be used as argument to the above script.)

**Comment by RandomFractals** [comment]
that helps. thanks!
