### ISSUE TITLE
Help: trailing data

### ISSUE THREAD

**Issue by danielb2** [mtth/avsc#257]
I'm new to Avro and trying to figure this out. This is my code:

```javascript
const schemaStr = Fs.readFileSync('schema.avsc', 'utf8');
const schema = Avsc.parse(schemaStr);

// using kafka-node
consumerGroup.on('message', (message) => {

  const res = schema.fromBuffer(message.value);
  console.log(res);
});
```

I'm getting `Error: trailing data`. Any ideas why this would be ? 
Also, I've seen multiple libs doing `message.value.slice(5)` which I've also tried to no avail. Any help appreciated.

**Comment by danielb2** [comment]
I also tried:

``` javascript
const schemaObj = require('./schema.avsc.json');
const schema = Avsc.Type.forSchema(schemaObj);
```

**Comment by mtth** [comment]
This can happen when the data doesn't match the schema or is corrupt (more information [here](https://github.com/mtth/avsc/issues/245#issuecomment-510915558)). How is the data produced? If you share the first few (say 50 or so) hex-encoded bytes of the message, we can check whether it looks like a standard Kafka message.

**Comment by danielb2** [comment]
Thank you for looking @mtth 

I thought the schema would just return invalid if it doesn't match?

Is this what you mean?
```
"M`@����[���
�           ������;U��[��#Z49941569743
 710978614109/23/2019
                     �82400
10008�P2&/�
           -09-18 23:48:04RealTime
```

**Comment by danielb2** [comment]
I got it working with kafkajs instead of kafka-node. I think it was compressed with LZ4 and I don't know what the deal is with kafka-node and LZ4

**Comment by mtth** [comment]
Nice, thanks for the update. Glad to hear you got it to work!

**Comment by danielb2** [comment]
@mtth   seems `node-rdkafka` is the easiest library to get things working with :)

Thanks for your help
