### ISSUE TITLE
How does this project compare to avro-js?

### ISSUE THREAD

**Issue by blackdynamo** [mtth/avsc#259]
It seems like the documentations are ALMOST identical but the apache one gets no love. It also is broken.

**Comment by mtth** [comment]
`avro-js` is pretty much an older version of `avsc`. I kept it up-to-date a couple times, unfortunately I found the update process too heavy weight to make it the new source of truth. As you can imagine it was difficult to maintain two repositories, so I now focus on this one.

**Comment by blackdynamo** [comment]
Thanks for the clarification. Might be beneficial to have a blurb like that at the beginning of this package readme and maybe submit a PR to the other package readme to say it's no longer maintained. The other module doesn't seem to work correctly :p

I can submit a PR to this project.

**Comment by bhishp** [comment]
Would be good to add a deprecation to avro-js or update the README to point here. Search for "avro js" in google returns that package and avsc is hard to find, went down a rabbit hole until I made it here

**Comment by blackdynamo** [comment]
@bhishp I created a PR for this last year cause the same thing happened to me, but the PR was closed. Not sure what ended up being the solution.

https://github.com/mtth/avsc/pull/262
