### ISSUE TITLE
Record type

### ISSUE THREAD

**Issue by mdehus** [mtth/avsc#26]
I'm attempting to serialize a javascript object into avro that contains a nested record type.  However, it seems to fail.  Are nested record types not supported, or am I doing something wrong?

Here is my schema:

    {
      "namespace": "com.myorg.email",
      "name": "Spam",
      "type": "record",
      "fields": [
        {"name": "body", "type": "string"},
        {"name": "raw", "type": "string"},
        {"name": "received", "type": {"type": "array", "items": "string"}},
        {"name": "additionalheaders", "type": {"type": "array", "items": {
            "name": "Header",
            "type": "record",
            "fields": [
                {"name": "key",   "type": "string"},
                {"name": "value", "type": "string"}
            ]
        }}}
      ]
    }

and some test code:

    var Avro = require('avsc');
    var spam_schema = Avro.parse('./spam.avsc');
    test_spam = {'body':'test', 'raw':'test', 
                         'received':'test', 
                         'additionalheaders':[{'testkey1':'testval1'}]}
    avro_object = spam_schema.toBuffer(test_spam)

and the error:

    node_modules/avsc/lib/types.js:2233
    throw new Error(f('invalid %s: %j', type, val));
              ^
    Error: invalid {"type":"array","items":"string"}: "test"

**Comment by mtth** [comment]
There are two issues with the value you pass in:

+ The `received` field is declared as an array but the value contains the string `'test'` (that's the mismatch the error message is referring to).
+ The `additionalheaders` field should contain an object with `key` and `value` fields but the value contains an object with only a single `testkey1` key.

For example, the value below would fit your schema:
```javascript
{
  'body': 'test',
  'raw': 'test',
  'received': ['test'],
  'additionalheaders': [{'key':'testval1', 'value': '2'}]
}
```
