### ISSUE TITLE
avsc or @avro

### ISSUE THREAD

**Issue by tinchoz49** [mtth/avsc#263]
Hi @mtth, how are you?

I'm going to use the library in a new project and I want to ask you: should I start using the new modules @avro/* that you were working on the `packages` branch, do you think is stable?

Thanks!

**Comment by mtth** [comment]
Hi @tinchoz49. I would recommend using the `@avro` modules, they will eventually become the next major version of `avsc` and are already stable. I just need to find the time to update the documentation before the transition can happen...

Most modules should have very similar APIs between the two versions. The only major difference is `@avro/services` which entirely revamps and improves how RPC services work. Additionally, changes and fixes to `avsc`'s current major version will be ported to the `@avro` modules but not the other way.

**Comment by tinchoz49** [comment]
thanks,  I will follow your recomendation
