### ISSUE TITLE
toString in schema throws exception

### ISSUE THREAD

**Issue by Othreumaru** [mtth/avsc#267]
Hello, I have found small bug in your implementation of hasDuplicates from lib/utils

`
function hasDuplicates(arr, fn) {
  var obj = {};
  var i, l, elem;
  for (i = 0, l = arr.length; i < l; i++) {
    elem = arr[i];
    if (fn) {
      elem = fn(elem);
    }
    if (obj[elem]) {
      return true;
    }
    obj[elem] = true;
  }
  return false;
}
`

var obj = {}; is not a good choice for a map since toString is in prototype of JavaScript object and will cause this code to report duplicated field even though such duplicate is not there. You should use Object.create(null)

**Comment by mtth** [comment]
You're right - thanks for bringing this up, @Othreumaru! Fixed and released in `5.4.16`.

**Comment by Othreumaru** [comment]
Thanks for the quick fix and keep up good job :)
