### ISSUE TITLE
Failing to encode union of complex types

### ISSUE THREAD

**Issue by Lroca88** [mtth/avsc#268]
Hi Matt 👋🏻
I've been trying to encode a simple union of records and it keeps failing with the next: 
`Error: invalid [{"name":"myOrder.Accessory","type":"record","fields":[{"name":"category","type":"string"}]},{"name":"myOrder.Computer","type":"record","fields":[{"name":"category","type":"string"},{"name":"os","type":"string"}]}]: {"category":"X1 Carbon","os":"Ubuntu"}`

In my avsc you will see that order is a record that only contains on element named item, this element is a union of an Accessory and a Computer:
```javascript
{
  "type" : "record",
  "name" : "order",
  "namespace" : "myOrder",
  "fields" : [ {
    "name" : "item",
    "type" : [ {
      "type" : "record",
      "name" : "Accessory",
      "fields" : [ {
        "name" : "category",
        "type" : "string"
      } ]
    }, {
      "type" : "record",
      "name" : "Computer",
      "fields" : [ {
        "name" : "category",
        "type" : "string"
      }, {
        "name" : "os",
        "type" : "string"
      } ]
    } ]
  } ]
}
```
If you try to encode the next simple object will fail with the error described above:
```javascript
{
   "item": { 
      "category": "X1 Carbon",
      "os": "Ubuntu"
   }
}
```

The weird thing is that I was able to get it encoded if I added the namespace (myOrder) and the record that I'm using (Computer) like this:
```javascript
{
   "item": { 
       "myOrder.Computer": {
          "category": "X1 Carbon",
          "os": "Ubuntu"
       }
   }
}
```
It feels wrong having to include namespace.record in the actual data that I want to encode, especially because I would like to keep the avro world decoupled from my pure data objects.
Looking forward to hearing from your considerations!

**Comment by mtth** [comment]
Hi @Lroca88. It is indeed expected that the union's value is nested inside a field with the type's name as key: it is required to guarantee correctness for certain types of unions. Take a look at [this related comment](https://github.com/mtth/avsc/issues/129#issuecomment-329944723) for more context and a potential way to achieve the representation you are looking for.
