### ISSUE TITLE
Cant decode - buffer is truncated

### ISSUE THREAD

**Issue by PeriGK** [mtth/avsc#269]
Hi there,

I am using the library to convert the data to AVRO, pipe it through a kafka instance and decode it from a consumer.

Though, the buffer I am passing looks like it is truncated

Here is what I do on the producer part:

```
const avro = require('avsc');
const payload = get_the_payload_for_delivery(various_args);
let vehicles_avro_types = avro.Type.forValue(payload);
const avro_data = vehicles_avro_types.toBuffer(payload);
kafka_utils.kafka_produce(avro_data);
```

On the consumer part:

I first copy the AVRO schema from the producer (via a debugging session maybe). Then I do:

```
const { Kafka } = require('kafkajs');
const avro = require('avsc');

const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['localhost:9092']
})

let schema = the_schema_I_copied_from_the_previous_step.

const run = async () => {
    const consumer = kafka.consumer({ groupId: 'test-group' })
    await consumer.connect()
await consumer.subscribe({ topic: 'my_topic', fromBeginning: true })

await consumer.run({
  eachMessage: async ({ topic, partition, message }) => {

    const schema_format = avro.Type.forSchema(schema);
    const from_buffer = schema_format.fromBuffer(message);

    let buffer_to_string = new Buffer(JSON.stringify(data), "binary").toString();
  },
})
}

run().catch(console.error)

```

I get this error:

```
{"level":"ERROR","timestamp":"2019-11-21T12:23:19.784Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"my_topic","partition":0,"offset":"0","stack":"Error: truncated buffer\n    at RecordType.Type.fromBuffer ......
```
Any ideas on what is going on?

Thanks
P.

**Comment by mtth** [comment]
Hi. It's hard to say without knowing more about your Kafka setup and the raw data you are decoding. This error is a generic failure which happens when the decoded data doesn't match the schema. In your case the message's payload might include a prefix or be compressed. Take a look at [this related thread](https://github.com/mtth/avsc/issues/245) for more a few pointers related to similar Kafka issues.

**Comment by PeriGK** [comment]
Hi @mtth 

Thanks for coming back. The Kafka setup is the default one projected in dockerized distributions like fast-data-dev and wurstmeister/kafka-docker

The raw data are json objects with one key having array-of-objects value (if it matters).

About the schema mismatch, I think this is not the case, as I am copying the generated schema to the consumer, by forcing an execution stop with the debugger.

I will totally have a look to the other tickets too

Cheers

**Comment by PeriGK** [comment]
Hi @mtth 

I dug a bit deeper. Looks like the forValue function doesn't include a name in the AVRO schema. I had to pass it through a validator to fix it. 

So you may consider this a bug report too. :)

Best,
P.

**Comment by sashaaKr** [comment]
@PeriGK you just saved me hours/days of debugging, thanks.
