### ISSUE TITLE
Adding new fields to existing schema

### ISSUE THREAD

**Issue by BeamupAI** [mtth/avsc#270]
We are using avsc for quite some time. We use it to transfer data between our python and node.js applications.

Lately we've had the need to update one of our schemas, so we've added
    {
      "name": "newPoint",
      "type": ["null", "point"],
      "default": null
    }

To the schema.

Even though the field is optional, and with a default value, we cannot decode any of the data that was encoded with the previous schema version.

The error we are getting is "invalid union index: -25"

This is crucial for us, as our schema will continue to evolve, but and the same time we must be backwards compatible.

Any advice as to how to approach this?

Thanks.

**Comment by mtth** [comment]
Hi. Are you specifying the (old) writer's schema when decoding? Your two schemas are [compatible](https://avro.apache.org/docs/current/spec.html#Schema+Resolution) but Avro requires you to specify both old and new schemas. [This Wiki section](https://github.com/mtth/avsc/wiki/Advanced-usage#schema-evolution) has more information on schema evolution.

**Comment by paulocoghi** [comment]
If the new schema has one extra field, can we consider the old schema as a "light type" for the new one?

**Comment by paulocoghi** [comment]
Or can we decode old saved files (with the small and old schema) directly using the new schema (which has a new extra field)?
