### ISSUE TITLE
Serialization errors break the BlockEncoder

### ISSUE THREAD

**Issue by sbwrege2z** [mtth/avsc#271]
When I execute the following code a pets.avro file is created with the 15 cats and dogs listed  in the pet arrays, and I get the expected output from the deserialization afterwards.

**EXAMPLE 1 - Cats and Dogs Only**
```
const fs = require('fs');
const avro = require('avsc');

const petFile = './/pets.avro';

const petType = avro.Type.forSchema({
  type: 'record',
  fields: [
    { name: 'kind', type: { type: 'enum', symbols: ['CAT', 'DOG'] } },
    { name: 'name', type: 'string' }
  ]
});

const cats = [
  { kind: 'CAT', name: 'Felix' },
  { kind: 'CAT', name: 'Garfield' },
  { kind: 'CAT', name: 'Heathcliff' },
  { kind: 'CAT', name: 'Tom' },
  { kind: 'CAT', name: 'Sylvester' },
  { kind: 'CAT', name: 'Figaro' },
  { kind: 'CAT', name: 'Si' },
  { kind: 'CAT', name: 'Am' }
];

const dogs = [
  { kind: 'DOG', name: 'Odie' },
  { kind: 'DOG', name: 'Astro' },
  { kind: 'DOG', name: 'Goofy' },
  { kind: 'DOG', name: 'Pluto' },
  { kind: 'DOG', name: 'Odie' },
  { kind: 'DOG', name: 'Scooby Doo' },
  { kind: 'DOG', name: 'Snoopy' }
];

const birds = [
  { kind: 'BIRD', name: 'Donald Duck' },
  { kind: 'BIRD', name: 'Foghorn Leghorn' },
  { kind: 'BIRD', name: 'Daffy Duck' },
  { kind: 'BIRD', name: 'Tweety' },
  { kind: 'BIRD', name: 'Woody Woodpecker' }
];

const encoder = new avro.streams.BlockEncoder(petType, {
  codec: 'deflate'
});

const decoder = new avro.streams.BlockDecoder();

async function open() {
  encoder.pipe(fs.createWriteStream(petFile));
}

function close() {
  return new Promise((resolve, reject) => {
    encoder.end((error) => {
      /*
        If I call serialize(birds) this callback will never be made
      */
      if (error) return reject(error);
      console.log('File saved!\n');
      resolve();
    });
  });
}

function encode(pet) {
  try {
    encoder.write(pet);
  } catch (error) {
    /*
      I should get an exception for each bird I try to encode
    */
    console.error(error.message);
    console.log(pet.kind + ': ' + pet.name);
  }
}

async function serialize(pets) {
  if (!pets.length) throw new Error('No pets!');
  console.log('Serializing ' + pets[0].kind + 'S');
  for (let pet of pets) {
    encode(pet);
  }
}

function deserialize(pets) {
  console.log('Deserializing pets');
  return new Promise((resolve, reject) => {
    decoder
      .on('data', (pet) => {
        pets.push(pet);
        console.log(pet.kind + ': ' + pet.name);
      })
      .on('end', () => resolve(pets))
      .on('error', reject);

    const readStream = fs.createReadStream(petFile).on('open', function() {
      readStream.pipe(decoder);
    });
  });
}

open()
  .then(() => serialize(cats))
  .then(() => serialize(dogs))
  /*
    Executing this next line causes the program to break
  */
  //.then(() => serialize(birds))
  .then(() => close())
  .then(() => deserialize([]))
  .then((pets) => console.log(pets.length + ' pets'))
  .catch((err) => console.error(err));
```

**Output**
```
Serializing CATS
Serializing DOGS
File saved!

Deserializing pets
CAT: Felix
CAT: Garfield
CAT: Heathcliff
CAT: Tom
CAT: Sylvester
CAT: Figaro
CAT: Si
CAT: Am
DOG: Odie
DOG: Astro
DOG: Goofy
DOG: Pluto
DOG: Odie
DOG: Scooby Doo
DOG: Snoopy
15 pets
```

View on Repl.it
[https://repl.it/@sbwrege2z/Avro-Cats-and-Dogs](https://repl.it/@sbwrege2z/Avro-Cats-and-Dogs)

**EXAMPLE 2 - Cats, Dogs, and Birds**

If I uncomment and execute the serialize(birds) line, I am expecting to see an error for each bird, but otherwise the program should complete as it did in the previous example.  

**Expected Output**
```
Serializing CATS
Serializing DOGS
Serializing BIRDS
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Donald Duck
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Foghorn Leghorn
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Daffy Duck
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Tweety
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Woody Woodpecker
File saved!

Deserializing pets
CAT: Felix
CAT: Garfield
CAT: Heathcliff
CAT: Tom
CAT: Sylvester
CAT: Figaro
CAT: Si
CAT: Am
DOG: Odie
DOG: Astro
DOG: Goofy
DOG: Pluto
DOG: Odie
DOG: Scooby Doo
DOG: Snoopy
15 pets
```

Unfortunately, only the first error is displayed.  Execution continues for each bird, but no exceptions are thrown after the first error.  I get a pets.avro file with no pets, and the callback for encoder.end inside the close function is never made.  Since that promise never resolves the deserialize function in the promise chain is never called either.  This is not at all what I was expecting.

**Actual Output**
```
Serializing CATS
Serializing DOGS
Serializing BIRDS
invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Donald Duck
```

View on Repl.it
[https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds](https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds)

Is the actual output shown the expected result?  If it is, what am I doing wrong?

Thanks for any help.

Best Regards,
Shannon

**Comment by sbwrege2z** [comment]
I suspect the problem is that the encoder stream is unpiped from the file writer stream when the error occurs, but I'm not familiar enough with node.js streams to figure out what to do next.  

From what I've seen during debugging, data is steal being serialized on the encoder stream, but no errors are being emitted (because I think the encoder stream is stuck in the writing state).  Is there a way to hook it back up to the file stream and continue after the first error is emitted?

**Comment by sbwrege2z** [comment]
OK.  I added one line of code after creating the encoder, and the behavior is ALMOST exactly as I would expect.

**EXAMPLE 3 - Cats, Dogs, and Birds Revised**

```
const encoder = new avro.streams.BlockEncoder(petType, {
  codec: 'deflate'
})

// NEW LINE:
encoder.on('error', (error) => console.error('Serialization error: ' + error.message));
```

**Output**

```
Serializing CATS
CAT: Felix
CAT: Garfield
CAT: Heathcliff
CAT: Tom
CAT: Sylvester
CAT: Figaro
CAT: Si
CAT: Am
Serializing BIRDS
Serialization error: invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Donald Duck
Serialization error: invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Foghorn Leghorn
Serialization error: invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Daffy Duck
Serialization error: invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Tweety
Serialization error: invalid {"type":"enum","symbols":["CAT","DOG"]}: "BIRD"
BIRD: Woody Woodpecker
Serializing DOGS
DOG: Odie
DOG: Astro
DOG: Goofy
DOG: Pluto
DOG: Odie
DOG: Scooby Doo
DOG: Snoopy
File saved!

Deserializing pets
CAT: Felix
CAT: Garfield
CAT: Heathcliff
CAT: Tom
CAT: Sylvester
CAT: Figaro
CAT: Si
CAT: Am
DOG: Odie
DOG: Astro
DOG: Goofy
DOG: Pluto
DOG: Odie
DOG: Scooby Doo
DOG: Snoopy
Error: truncated block
    at BlockDecoder._read (/home/runner/node_modules/avsc/lib/containers.js:305:13)
    at BlockDecoder.Readable.read (_stream_readable.js:469:10)
    at maybeReadMore_ (_stream_readable.js:613:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

View on Repl.it
[https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds-v2](https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds-v2)

Does anyone know why I am getting the "truncated block" error at the end of the deserialization???

**Comment by mtth** [comment]
Hi. Thanks for the detailed examples and follow up investigation!

> Why did handling the error in this way change the behavior of the program rather than using the try/catch block in the original implementation?

Writes are asynchronous so wrapping `encoder.write(pet)` inside a `try` won't catch the encoding exception. Your update identified the correct way of handling them: attaching an `'error'` handler to the stream. (I agree that using `try` catch would be a simpler user experience, but it's not possible to support it with node streams.)

> Also why I am getting the "truncated block" error at the end of the deserialization rather than "15 pets" logged in the success case?

That happens because the element count is incremented even when serialization fails, so the decoder in your example is still expecting more data points (1 for each bird). The assumption was that the entire stream would be discarded if an error occurs. However it's probably better to ignore these elements entirely instead, such that a failed encoding doesn't corrupt the entire block. I'll commit a change for this shortly.

**Comment by mtth** [comment]
`5.4.17` includes the change described above - can you upgrade and rerun example 3?

**Comment by sbwrege2z** [comment]
Matt, thanks for the help.  This raises a couple of questions:

> Writes are asynchronous so wrapping encoder.write(pet) inside a try won't catch the encoding exception. Your update identified the correct way of handling them: attaching an 'error' handler to the stream. (I agree that using try catch would be a simpler user experience, but it's not possible to support it with node streams.)

I can't think of a good way to access the offending object without logging every single write like I did in the revised example.  If there are 1,000,000 successes per 1 failure it would be nice to log just the failures.  The only thing I can think of is to check for validation errors before the write takes place:

```
async function serialize(pets) {
  if (!pets.length) throw new Error('No pets!');
  console.log('Serializing ' + pets[0].kind + 'S');
  for (let pet of pets) {
    if (petType.isValid(pet)) {
      encoder.write(pet);
    } else {
      console.error('Error: ' + pet.name + ' is not a pet');
    }
  }
}
```

View on Repl.it
[https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds-Revision-2](https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds-Revision-2)

The good news is that this finally exhibits the behavior I expected when constructing this example. 

The problem with this approach is that when the object IS a valid pet then the pet is double checked --- once before the write and then again when the write takes place.  In my opinion one of the strong points of using avro rather than just plain json is the guaranteed type checking.  While avro will guarantee the type, it seems like it is hard to find what is causing the error unless I check the type before the write, and if I have to do that anyway I could do the same with ordinary json.

When the error is emitted is there any way to pass a reference to the offending object if it is a validation error in addition to detailing why the object is invalid?  If this information is already available, can you show me how I can access it in the error handler.

> However it's probably better to ignore these elements entirely instead, such that a failed encoding doesn't corrupt the entire block. I'll commit a change for this shortly.

Excellent!  I have only ever installed packages with npm.  I assume this type of commit won't be available using `npm install` for a while.  Is the best way to get the updated code to just clone the repo in a 3rd party `modules` directory and not use `node_modules` for this particular library?  I am relatively new to node and it's package manager, and this is a use case I haven't had to worry about yet.

**Comment by mtth** [comment]
> In the original code, why does the very first error generate an exception caught in the try/catch block?

For certain writes the method will be called synchronously. You shouldn't rely on this though, it's an implementation detail due to stream internals.

> I am ok changing the way stream errors are handled, but I can't think of a good way to access the offending object without logging every single write like I did in the revised example. If there are 1,000,000 successes per 1 failure it would be nice to log just the failures. The only thing I can think of is to check for validation errors before the write takes place:

If you just want to log the error message, attaching logging as error handler on the stream should be OK (with the caveat that you might not fail on other, non-serialization, errors). If you would like more detailed explanations on the failure, checking via `isValid` is the way to go. For many realistic examples, you'll want to provide details on which fields are invalid and `isValid` supports this via its [`errorHook`](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts) option (for performance reasons, this detailed information is unavailable in errors thrown during serialization).

The situation here is not ideal though, especially given that we can't just wrap stream `write` calls in a `try`... To make this easier, I just released a new version (`5.4.18`) which exposes a new event you can listen to to get the mismatched value and type. Here's how you can use it:

```javascript
var encoder  = new avro.streams.BlockEncoder(type)
  .removeAllListeners('typeError') // By default, there is a handler emitting 'error'.
  .on('typeError', function (err, val, type) { /* Add your own logic here. */ });
```

> The problem with this approach is that when the object IS a valid pet then the pet is double checked --- once before the write and then again when the write takes place.

FTR double-checking is not an issue performance-wise: the checks done during serialization (and `isValid` without an error hook) are very fast and will be insignificant compared to the rest.

> I assume this type of commit won't be available using npm install for a while.

It's already available: you can get the latest (updated) version just by running `npm install avsc`.

> Is the best way to get the updated code to just clone the repo in a 3rd party modules directory and not use node_modules for this particular library?

If the code is on GitHub, you usually don't have to clone the repo. You can just add [`user/repo`](https://docs.npmjs.com/files/package.json#github-urls) directly as a dependency. NPM actually supports a variety of [URL dependencies](https://docs.npmjs.com/files/package.json#dependencies) (in general you should only use these more esoteric options if you don't have another choice).

**Comment by sbwrege2z** [comment]
That answered all my questions.  Thanks for the thoughtful responses!

**Comment by sbwrege2z** [comment]
I just installed the updates and modified the example to include the typeError check.

View on Repl.it
https://repl.it/@sbwrege2z/Avro-Cats-Dogs-and-Birds-Revision-3

Now the behavior is exactly as expected and I can log the offending objects. 

Final question based on your last response: Would you recommend that I do the type checking before serializing the object instead of using the typeError method?  It seems like you think this might actually be the more performant approach even though the type is double-checked.  Maybe it makes sense to do both and have the typeError event as a fail safe.

**Comment by sbwrege2z** [comment]
I **love** the errorHook!  It allows you to not only get the offending object and tell you what the validation error is, but it allows you to show which field(s) caused the error.  

The way I think I will implement things unless you recommend differently is as follows:

1. Add the on typeError listener as suggested.
2. Remove the type validation during streaming.  I suspect 99.999% of the time this will never be an issue.
3. In the event of a typeError, the error is handled by the listener.  In the error handler, I will put the detailed isValid function with the error hook. 

The advantages as I see them are:

1. I no longer double validate.
2. My pipeline does not break.
3. I get very detailed error messages.

If there is some other best practices that anyone might suggest, I am open to changing it up.  For now I am very happy with this way of doing things.
