### ISSUE TITLE
LogicalType manipulation doesn't work 

### ISSUE THREAD

**Issue by han8909227** [mtth/avsc#272]
Hi, 

I am trying to making a logicaltype checker for my custom logical type `validated-string` but I can't get it to work. Not even the example works. https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types

Does passing in the class the correct approach ? 
How may I do a custom logical type checking ?
How can I get the all the logical type fields and do the checking ? 

Using 
    "avsc": {
      "version": "5.4.16",

Event
`  const eventObj = {
    time: Date.now(),
    age: 15,
    timeSpentOnlineMs: 100000000,
    amountSpendShopping: 20.56,
    sessionId: '123-1234-12345',
    amountSpendShoppingWithFloat: 20.56
  }`

Schema 
`  const schema = {
    "type": "record",
    "name": "avro_tester_han_field_validation",
    "fields": [
      {
        "name": "time",
        "type": {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      },
      {
        "name": "age",
        "type": {
          "type": "int",
          "logicalType": "validated-int",
          "minimum": 5
        },
        "default": 10
      },
      {
        "name": "timeSpentOnlineMs",
        "type": {
          "type": "long",
          "logicalType": "validated-long",
          "maximum": 100000000
        }
      },
      {
        "name": "amountSpendShopping",
        "type": {
          "type": "float",
          "logicalType": "validated-float",
          "minimum": 10.45,
          "maximum": 20.55
        }
      },
      {
        "name": 'sessionId',
        "type": {
          "type": 'string',
          "logicalType": 'validated-string',
          "pattern": '^\\d{3}-\\d{4}-\\d{5}$' // Validation pattern.
        }
      },
      {
        "name": "amountSpendShoppingWithFloat",
        "type": ['double', 'null']
      },
    ]
  }`

Code
`      const newType: Type = avro.Type.forSchema(
        this.schema,
        { logicalTypes: {'timestamp-millis:': DateType}}
      );
      const buf = newType.toBuffer(this.record)
      const date = newType.fromBuffer(buf);
      console.log('****', date, '****')` 

Output
`**** avro_tester_han_field_validation {
  time: 1576267212484,
  age: 15,
  timeSpentOnlineMs: 100000000,
  amountSpendShopping: 20.559999465942383,
  sessionId: '123-1234-12345',
  amountSpendShoppingWithFloat: 20.56
} ****`

**Comment by han8909227** [comment]
And I did use the exact code from the DateType example
`
class DateType extends avro.types.LogicalType {
  _fromValue(val) {
    console.log('here')
    return new Date(val);
  }
  _toValue(date) {
    console.log('here')
    return date instanceof Date ? +date : undefined;
  }
  _resolve(type) {
    console.log('here')

    if (avro.Type.isType(type, 'long', 'string', 'logical:timestamp-millis')) {
      return this._fromValue;
    }
  }
}`

**Comment by mtth** [comment]
Hi @han8909227, there's a typo in your type's `logicalTypes` object: `{'timestamp-millis:': DateType}`: there is a trailing `:` in the key. If you fix it, the logical type will be applied as you expect (you'll need to update `Date.now()` to `new Date()` in your record too, to make it a `Date`).
