### ISSUE TITLE
GenericRecord support? (Parsing data with embedded schema)

### ISSUE THREAD

**Issue by kalanyuz** [mtth/avsc#273]
There are use cases where I want the receiving end to not having to maintain or keep track of the schema information. I have a Java/Kotlin code that encodes data in GenericRecord format. Usually, you'd be able to parse the encoded data without having to supply schema information. For example:

```kotlin
///encode your generic records to ByteArray.....
var dataReader = DataFileReader<GenericRecord>(byteInput, GenericDatumReader())
var records = dataReader.toList()
```

Is there a way for avsc or avro-js to decode the bytearray made from above method?

**Comment by mtth** [comment]
`avsc`'s `DataFileReader`'s equivalent is the [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts). Both read [container files](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) which include the schema of the objects they contain. Here's how you can use one:

```javascript
// Decodes all records inside the given buffer and returns them as an array.
function accumulateRecords(buf, cb) {
  const records = [];
  const encoder = new BlockDecoder()
    .on('error', cb)
    .on('data', (record) => { records.push(record); })
    .on('end', () => { cb(null, records); });
  encoder.end(buf);
}
```

A few things to note:

+ Generic records and specific records have the same encoding. You can read generic records as specific records and vice-versa. (In fact this distinction is language dependent: not all Avro implementations have it.)
+ Unless you send many records at a time, this will be inefficient. Container files introduce overhead (header, blocks).
+ You can write also write container files with `avsc`'s [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts).
