### ISSUE TITLE
Performance of Avro versus TSV

### ISSUE THREAD

**Issue by sbwrege2z** [mtth/avsc#274]
I have written a simple program that generates 10,000 sample users and saves them as an avro container, a tab-separated file, and a gzipped tab-separated file.

I then serialize the data back from each of the files and report on the results. 

I am not seeing the big performance benefits that I was expecting.  Here's the output from a sample run:

```
Decoding ./data/sample.avro
File size: 635,149
10,000 users decoded
decode: 375.618ms

Decoding ./data/sample.tsv
File size: 1,185,222
10,000 users decoded
decode: 301.678ms

Decoding ./data/sample.tsv.gz
File size: 557,797
10,000 users decoded
decode: 398.467ms
```

The avro container is about half the size of the uncompressed TSV file and a little bigger than the zip file.

The code for the deserialization of the avro container is a little cleaner and the type guarantees are great, but I guess I was expecting more from reading the data in binary format than from reading and parsing data saved as plain text.

You can view the code on Repl.it here:
[https://repl.it/@sbwrege2z/avro-vs-tsv](https://repl.it/@sbwrege2z/avro-vs-tsv)

The core functionality of the avro deserialization looks like this:

```
    let count = 0;
    const decoder = new Promise((resolve, reject) => {
      streams
        .createAvroDecoder({
          path: filename
        })
        .on('data', (user) => {
          count++;
          // do something with the user
        })
        .on('end', () => resolve())
        .on('error', reject);
    });

    await decoder;
```

The core functionality of the TSV deserialization looks like this:

```
    let count = -1; // Ignore first line contains field names
    const input = fs.createReadStream(filename);
    const splitter = streams
      .splitter({ mapper: (line) => line.split('\t') })
      .on('data', (values) => {
        if (count >= 0) {
          const user = Object.assign({}, modelUser);
          for (let [index, key] of keys) user[key] = values[index];
        }
        count++;
        // do something with user
      });

    await streams.pipeline(input, splitter);
```

Avro seems to do better when I create much larger sample sizes (e.g. 100,000 users), but it's not earth shaking:

```
Decoding ./data/sample.avro
File size: 6,336,032
100,000 users decoded
decode: 1919.791ms

Decoding ./data/sample.tsv
File size: 11,847,180
100,000 users decoded
decode: 2090.491ms

Decoding ./data/sample.tsv.gz
File size: 5,558,014
100,000 users decoded
decode: 2612.731ms
```

Here are the results for 1,000,000 users, but my data sets will never be this large:

```
Decoding ./data/sample.avro
File size: 63,341,171
1,000,000 users decoded
decode: 15459.835ms

Decoding ./data/sample.tsv
File size: 118,470,696
1,000,000 users decoded
decode: 18192.243ms

Decoding ./data/sample.tsv.gz
File size: 55,562,410
1,000,000 users decoded
decode: 23616.085ms
```

Should I temper my expectations about the performance benefits of avro?  Are there any modifications I can make to the code that could make the avro decoding more performant?

Thanks for any help.

**Comment by mtth** [comment]
Hi, good question (and nice writeup!).

I'll start with a general word of caution: benchmarks are notoriously difficult to get right, especially on small samples and with a JIT-ed language (the case here). Performance often doesn't generalize to real use-cases. There are ways to mitigate the disparities--libraries and tooling definitely help--but it's good always keep that in mind when interpreting results.

W.r.t. the example here, one thing to know is that relative performance depends on the data. String-heavy schemas such as this one favor string-based encodings (TSV, JSON). I expect the benefit would be larger if your data included a wider variety of types (enums, arrays, nested records, etc.). By now the numbers are outdated but you can get an idea of the variability by looking at [these decoding benchmarks](https://github.com/mtth/avsc/wiki/Benchmarks#decoding-1). There is also [a script](https://github.com/mtth/avsc/blob/master/etc/scripts/perf) that you can run to get current numbers.

Another factor I can think of is that the `BlockDecoder` itself introduces overhead. For example, each decoder parses the header which includes building the type, a relatively expensive step. This fixed cost is marginal when amortized over files with many entries but can be significant for small files. Using a `RawDecoder` instead would lead to faster decoding overall, but I would only do this if performance is critical (in most cases the convenience and guaranteed consistency of the block decoder will outweigh any gains here).

BTW, I don't expect that it will affect the numbers but I think there is a typo in your benchmarked TSV code: `for (let [index, key] of keys) user[key] = values[index];` does not end up actually setting `user`'s fields, I think you meant to add `keys.entries()`.

**Comment by sbwrege2z** [comment]
> BTW, I don't expect that it will affect the numbers but I think there is a typo in your benchmarked TSV code: for (let [index, key] of keys) user[key] = values[index]; does not end up actually setting user's fields, I think you meant to add keys.entries().

Yep!  Bug fixed.  Thank you!

> Another factor I can think of is that the BlockDecoder itself introduces overhead. For example, each decoder parses the header which includes building the type, a relatively expensive step. This fixed cost is marginal when amortized over files with many entries but can be significant for small files. Using a RawDecoder instead would lead to faster decoding overall, but I would only do this if performance is critical (in most cases the convenience and guaranteed consistency of the block decoder will outweigh any gains here).

If I'm going to use Avro, I definitely want the type guarantees.  In fact, when creating multiple streams I ONLY catch the errors when writing to the Avro container.  The TSV and zipped TSV streams don't care whether what I write is what I think I am supposed to be writing.  The Avso stream does.  That is one of the biggest benefits in my opinion.  Even if I decide not to serialize to Avro, it might be worth doing Avro type checking during serialization.

I'm not sure I understand the distinction between a BlockEncoder and a RawEncoder when we're talking about 10,000+ records.  Doesn't it construct the type just once for the entire container?  I made a one record test to see what the fixed cost of processing the header looks like.

> String-heavy schemas such as this one favor string-based encodings (TSV, JSON). I expect the benefit would be larger if your data included a wider variety of types (enums, arrays, nested records, etc.). 

Excellent suggestion!  I changed my program to implement a generic type instead of just a User.  I created a Foo type which has 5 ints, 5 longs, 5 floats, 5 doubles, and 5 booleans (no strings).  The idea here is to give Avro the benefit of shining where it should.

View on Repl.it
[https://repl.it/@sbwrege2z/avro-vs-tsv-Revised](https://repl.it/@sbwrege2z/avro-vs-tsv-Revised)

I still don't see much of a performance boost for files with 10,000 of fewer records.  In fact the time to deserialize the data is still the same or a little worse for the Avro containers.  I will note that the file size for the Avro container is now smaller in every case, though. 

The big performance gains start to show up with 100,000+ records for this data type.  Deserializing the data in the Avro container is 2-3 times faster than deserializing the text based formats!

I really wish Avro was a winner across the board.  Most of my data is in small files, so I don't want to add overhead and complexity just for the sake of saving a little disk space.  The type guarantees are great, though, so it doesn't make the decision an easy one.  

## Repl.it Results
Here's the updated statistics from a few of my sample runs on Repl.it if anyone is interested. 

**Deserialization (ms)**

|    Rows   |   Avro  |   TSV   | TSV.GZ  |
|----------:|--------:|--------:|--------:|
|         1 |       8 |       5 |       2 |
|     1,000 |     102 |      88 |     111 |
|    10,000 |     512 |     580 |     416 |
|   100,000 |   1,549 |   2,584 |   3,818 |
|   500,000 |   6,627 |  13,040 |  19,007 |

**File Size (MB)**

|    Rows   |   Avro  |   TSV   | TSV.GZ  |
|----------:|--------:|--------:|--------:|
|         1 |   1004B |    513B |    291B |
|     1,000 |    116K |    351K |    165K |
|    10,000 |     1.1 |     3.5 |     1.6 |
|   100,000 |    11.5 |    35.1 |    16.4 |
|   500,000 |    57.6 |   175.7 |    81.9 |

## Laptop Results
Here are the same tests run on my laptop.

**Deserialization (ms)**

|    Rows   |   Avro  |   TSV   | TSV.GZ  |
|----------:|--------:|--------:|--------:|
|         1 |       8 |       4 |       3 |
|     1,000 |      28 |      35 |      25 |
|    10,000 |      90 |      98 |     127 |
|   100,000 |     340 |     729 |   1,150 |
|   500,000 |   1,639 |   3,531 |   4,792 |
| 1,000,000 |   2,535 |   6,947 |  11,508 |

**File Size (MB)**

|    Rows   |   Avro  |   TSV   | TSV.GZ  |
|----------:|--------:|--------:|--------:|
|         1 |   1047B |    506B |    294B |
|     1,000 |    116K |    351K |    165K |
|    10,000 |     1.2 |     3.5 |     1.6 |
|   100,000 |    11.5 |    35.1 |    16.4 |
|   500,000 |    57.6 |   175.7 |    81.9 |
| 1,000,000 |   115.2 |   351.4 |   163.7 |

---
At the end of the day, 2.5 seconds to decode 1,000,000 records in an interpreted language is really impressive in my book.  That's 394,400 records per second!  Kudos to all the great minds that made this possible and @mtth for making this great library!
