### ISSUE TITLE
nested schemas (optional)

### ISSUE THREAD

**Issue by faeb187** [mtth/avsc#275]
Hi there

I need to implement a very complex schema (multi level nesting). Is the plan of a avro schema, that the whole schema is defined as one (or am I allowed to modularize).

A working example:
`fields: [
   {
      name: "anyname",
      type: RefToOtherSchema
   }
]`

Now when I try to make this field optional it won't work:

`fields: [
    {
      name: "anyname",
      type: ["null", type: RefToOtherSchema],
      default: null
    }
]`

However, when I copy the content of 'RefToOtherSchema' into type (instead of using a variable) it works...

That means to me I have to write the whole schema as one, maybe that's just the plan? I imagine this will  be very complicated to read afterwards... What's the plan please, is this even an issue?

**Comment by mtth** [comment]
You should be able to use variables within schemas. There's a typo in your snippet (the extra `type:` in the optional case), perhaps that is the issue? If not, can you provide a snippet which reproduces the error?
