### ISSUE TITLE
display why a schema isn't valid

### ISSUE THREAD

**Issue by faeb187** [mtth/avsc#276]
having a multinested complex schema, the method isValid() just returns false.
Is it possible to display why (or where) it's invalid?
It's pretty weird to look through the whole schema for the location where it breaks...

**Comment by mtth** [comment]
`isValid` has an `errorHook` option you can use to identify where your data doesn't match the schema. [This gist](https://gist.github.com/mtth/fe006b5b001beeaed95f) has a few sample implementations.

Also, in case it helps clarify: `isValid` is used to check the validity of _data_ against a schema, not the validity of the schema itself (there is no such functionality ATM).
