### ISSUE TITLE
Error: truncated buffer\n    at RecordType.Type.fromBuffer

### ISSUE THREAD

**Issue by akki192** [mtth/avsc#279]
Hi,

I am reading kafka messages using kafka-js which are sent by upstream system using java. I'm trying to use avsc for decoding the message using below schema and code.

Schema:
`
[
  {
    "namespace": "com.pojo",
    "name": "StatusCode",
    "type": "enum",
    "symbols": [
      "NEW",
      "RDY",
      "STA",
      "AP",
      "ENQ",
      "DLV",
      "CON",
      "GF",
      "DEL"
    ]
  },

  {
    "namespace": "com.pojo",
    "name": "StatusEvent",
    "type": "record",
    "fields": [
      {
        "name": "statusTimestamp",
        "type": "string"
      },
      {
        "name": "statusCode",
        "type": "com.pojo.StatusCode"
      },
      {
        "name": "userName",
        "type": [ "null", "string" ],
        "default": null
      }
    ]
  },

  {
    "namespace": "com.pojo",
    "name": "Company",
    "type": "record",
    "fields": [
      {
        "name": "companyId",
        "type": "string"
      },
      {
        "name": "companyName",
        "type": "string"
      }
    ]
  },

  {
    "namespace": "com.pojo",
    "name": "Error",
    "type": "record",
    "fields": [
      {
        "name": "errorCode",
        "type": "long"
      },
      {
        "name": "errorMessage",
        "type": [ "null", "string" ]
      }
    ]
  },

  {
    "namespace": "com.pojo",
    "name": "Max_Notification",
    "type": "record",
    "fields": [
      {
        "name": "schemaVersion",
        "type": "string",
        "default": "1.2.0"
      },
      {
        "name": "domain",
        "type": "string"
      },
      {
        "name": "messageId",
        "type": "string"
      },
      {
        "name": "messageTimestamp",
        "type": "string"
      },
      {
        "name": "aomaDspId",
        "type": "string"
      },
      {
        "name": "raasProductId",
        "type": "string"
      },
      {
        "name": "groupId",
        "type": "long"
      },
      {
        "name": "statusEvent",
        "type": "com.pojo.StatusEvent"
      },
      {
        "name": "priorStatusEvents",
        "type": {
          "type": "array",
          "items": "com.pojo.StatusEvent"
        },
        "default": []
      },
      {
        "name": "territories",
        "type": {
          "type": "array",
          "items": "string"
        }
      },
      {
        "name": "repOwner",
        "type": "com.pojo.Company"
      },
      {
        "name": "maintOwner",
        "type": "com.pojo.Company"
      },
      {
         "name": "url",
         "type": "string"
      },
      {
        "name": "error",
        "type": [ "null", "com.pojo.Error" ],
        "default": null
      },
      {
        "name": "clientProperties",
        "type": [
          "null",
          {
            "type": "map",
            "values": "string"
          }
        ],
        "default": null
      }
    ]
  }
]
`

Message [JSON.stringify(message.value)]:
`Obj\u0001\u0002\u0016avro.schema�\u0014{\"type\":\"record\",\"name\":\"Max_Notification\",\"namespace\":\"com.pojo\",\"fields\":[{\"name\":\"schemaVersion\",\"type\":\"string\",\"default\":\"1.2.0\"},{\"name\":\"domain\",\"type\":\"string\"},{\"name\":\"messageId\",\"type\":\"string\"},{\"name\":\"messageTimestamp\",\"type\":\"string\"},{\"name\":\"aomaDspId\",\"type\":\"string\"},{\"name\":\"raasProductId\",\"type\":\"string\"},{\"name\":\"groupId\",\"type\":\"long\"},{\"name\":\"statusEvent\",\"type\":{\"type\":\"record\",\"name\":\"StatusEvent\",\"fields\":[{\"name\":\"statusTimestamp\",\"type\":\"string\"},{\"name\":\"statusCode\",\"type\":{\"type\":\"enum\",\"name\":\"StatusCode\",\"symbols\":[\"NEW\",\"RDY\",\"STA\",\"AP\",\"ENQ\",\"DLV\",\"CON\",\"GF\",\"DEL\"]}},{\"name\":\"userName\",\"type\":[\"null\",\"string\"],\"default\":null}]}},{\"name\":\"priorStatusEvents\",\"type\":{\"type\":\"array\",\"items\":\"StatusEvent\"},\"default\":[]},{\"name\":\"territories\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"repOwner\",\"type\":{\"type\":\"record\",\"name\":\"Company\",\"fields\":[{\"name\":\"companyId\",\"type\":\"string\"},{\"name\":\"companyName\",\"type\":\"string\"}]}},{\"name\":\"maintOwner\",\"type\":\"Company\"},{\"name\":\"url\",\"type\":\"string\"},{\"name\":\"error\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Error\",\"fields\":[{\"name\":\"errorCode\",\"type\":\"long\"},{\"name\":\"errorMessage\",\"type\":[\"null\",\"string\"]}]}],\"default\":null},{\"name\":\"clientProperties\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}],\"default\":null}]}\u0000aH����\u0010����M�A��\u0002�\u0005\n1.2.0\u0006SMEH6a982858-0f79-4715-975d-071c380881ef02020-01-30T06:39:27.246Z\u00060A6\u001cG010003010331F̟�\u000402020-01-30T06:39:21.158Z\b\u0000\b02020-01-30T06:33:51.926Z\u0000\u000002020-01-30T06:35:56.194Z\u0002\u0002\u0010EAI_PUSH02020-01-30T06:36:17.245Z\u0004\u0002\u0014EAI_CLIENT02020-01-30T06:36:31.205Z\u0006\u0002\u0014EAI-CLIENT\u0000\u0014\u0004AT\u0004AU\u0004BE\u0004CA\u0004CH\u0004DE\u0004FR\u0004GB\u0004IT\u0004US\u0000\b9999*Multiple (see tracks)\b0202\u001cSME UK Limited\u0000\u0000\u0002\u0002\u001aAOMA_BATCH_ID\u000e3610049\u0000aH����\u0010����M�A��`

HEX message:
`4f626a0102166176726f2e736368656d61c2147b227479...`

Source Code:
`
const type = avro.parse(path.resolve(__dirname, 'schemas/mySchema.avsc'))
var buff = Buffer.from(message.value, 'binary')
const decodedMessage = type.fromBuffer(buff)
`

Thia resulted in below error:

`invalid union index`

Also, tried breaking the schema like:

`
var registry = {}
avro.parse(path.resolve(__dirname, 'schemas/component1.avsc'), { registry: registry })
avro.parse(path.resolve(__dirname, 'schemas/component2.avsc'), { registry: registry })
avro.parse(path.resolve(__dirname, 'schemas/component3.avsc'), { registry: registry })
avro.parse(path.resolve(__dirname, 'schemas/component4.avsc'), { registry: registry })
const type = avro.parse(path.resolve(__dirname, 'schemas/finalComponent.avsc'), { registry: registry })
`

I'm now getting below mentioned error message. Any idea what might be causing this?

`Error: truncated buffer\n    at RecordType.Type.fromBuffer (/opt/order-history-status-feeder/node_modules/avsc/lib/types.js:597:11)`

I have also tried buffer.slice(5) but that did not solve my issue.

Thanks,

**Comment by mtth** [comment]
Looks like the message your are trying to decode is an [object container file](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) (it starts with `0x4f626a01`). You should be able to decode it with a [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts), for example something like:

```javascript
new avro.streams.BlockDecoder()
  .on('data', (val) => { /* Do something with each value. */ })
  .end(buf); // Feed in your binary data.
```

**Comment by akki192** [comment]
Thanks Matthieu! That fixed my issue.
