### ISSUE TITLE
Problems when writing decoded data to database

### ISSUE THREAD

**Issue by pekkalaaksonen** [mtth/avsc#280]
Hi,

I'm quite sure that this isn't actually related to avsc library but I decided to ask anyway.

I am writing an application that reads data from very busy kafka topics (millions of messages per day) and writes them to database. The problem is that the program runs for a minute or two and then crashes on JavaScript heap out of memory error. I've investigated where the issue might be and it seems that it happens when I am writing decoded message to database. If I just log decoded messages it works fine. Or If I write messages to database without decoding it works fine. But when I call my writeRow() function on decoder.on('data') event, it runs out of memory very soon. Am I not handling events emited by the decoder correctly?

Here are the relevant pieces of code:

**Consumer:**

```
const run = async () => {
  await consumer.connect();
  await topics.forEach(topic => {
    consumer.subscribe({ topic: topic, fromBeginning: false });
  });

  await consumer.run({
    eachMessage: async ({ topic, message }) => {
      try {
        const buf = await Buffer.from(message.value, "binary");
        const decoder = new avro.streams.BlockDecoder();
        await decoder.on("data", async msg => {
          console.log(`Message received: ${msg}`);
          await writeRow(topic, new Date().toISOString(), msg);
        });
        await decoder.end(buf);
      } catch (err) {
        console.log(err);
      }
    }
  });
};
```

**writeRow() function:**

```
const writeRow = async (topic, timestamp, data) => {
  const client = await pool.connect();
  try {
    const res = await client.query(
      `INSERT INTO ${topic.replace(
        /\./g,
        "_"
      )}(topic, timestamp, data) VALUES('${topic}', '${timestamp}', '${JSON.stringify(
        data
      )}')`
    );
    console.log(`${res.rowCount} row written to database.`);
  } catch (err) {
    console.log(err);
  } finally {
    await client.release();
  }
};
```

**Comment by mtth** [comment]
My best guess is that the code is opening many connections at once, causing it to eventually OOM. Streams do not interface well with `async` functions, and `writeRow` here likely ends up being called many times concurrently (the `'data'` handler is called in quick succession as the file is decoded, without waiting for the calls to return).

One way to implement the behavior you want would be to [use a transform stream](https://stackoverflow.com/a/37041949/1062617). However, opening a new connection for each row is suboptimal, I might recommend batching the rows and inserting many in a single query. For example, if each message isn't too large, you can accumulate all its decoded rows into an array and insert them all at once when the stream ends. Something like:

```javascript
const vals = [];
decoder
  .on('data', (val) => { vals.push(val); })
  .on('end', () => /* Write vals to the database. */)
  .end(buf);
```
