### ISSUE TITLE
Problems with array of records type of schema

### ISSUE THREAD

**Issue by vadymrybak** [mtth/avsc#283]
I have a schema below which is an array of records:

```
[
	{
		"type": "record",
		"namespace": "com.vad.wf.api.task",
		"name": "WfControlKey",
		"doc": [
			"Definition of control key",
			"Created based on TC definition XML."
		],
		"fields": [
			{
				"name": "rootInstanceKey",
				"type": [
					"null",
					"string"
				],
				"default": null
			},
			{
				"name": "instanceKey",
				"type": [
					"null",
					"string"
				],
				"default": null
			},
			{
				"name": "controlKey",
				"type": [
					"null",
					"string"
				],
				"default": null
			}
		]
	},
	{
		"type": "record",
		"namespace": "com.vad.wf.api.task",
		"name": "WfTask",
		"fields": [
			{
				"name": "controlKey",
				"type": "com.vad.wf.api.task.WfControlKey"
			},
			{
				"name": "taskTypeNm",
				"type": [
					"null",
					"string"
				],
				"default": null,
				"doc": "Task type name"
			}
		]
	}
]
```

This is my message that I'm trying to encode:

```
const message: object = {
    "controlKey": {
        "rootInstanceKey": "bd1f8011-9341-46d2-bb3b-c88c144cd1",
        "instanceKey": "bd1f8011-9341-46d2-bb3b-c8s8cd144cd0",
        "controlKey": "bd1f8011-9341-46d2-bb3b-c88cd1a49sc2d0"
    },
    "taskTypeNm": "add_sub",
};
```

Code for encoding:

```
const schema: string = fs.readFileSync('../avro/wf-instance.avsc', {encoding: 'utf8'});
const _registry: any = {};
const _schema: any      = JSON.parse(schema);
const _mainType: any   =  avsc.Type.forSchema(_schema, {registry: _registry});
console.log(_mainType.toBuffer(message));
```

Getting error below:

> C:\Users\server\node_modules\avsc\lib\types.js:3023
>   throw new Error(f('invalid %j: %j', type.schema(), val));
>         ^
> Error: invalid [{"name":"com.vad.wf.api.task.WfControlKey","type":"record","fields":[{"name":"rootInstanceKey","type":["null","string"]},{"name":"instanceKey","type":["null","string"]},{"name":"controlKey","type":["null","string"]}]},{"name":"com.vad.wf.api.task.WfTask","type":"record","fields":[{"name":"controlKey","type":"com.vad.wf.api.task.WfControlKey"},{"name":"taskTypeNm","type":["null","string"]}]}]: {"controlKey":{"rootInstanceKey":"bd1f8011-9341-46d2-bb3b-c88c144cd1","instanceKey":"bd1f8011-9341-46d2-bb3b-c8s8cd144cd0","controlKey":"bd1f8011-9341-46d2-bb3b-c88cd1a49sc2d0"},"taskTypeNm":"add_sub"}
>     at throwInvalidError (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\node_modules\avsc\lib\types.js:3023:9)
>     at WrappedUnionType._write (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\node_modules\avsc\lib\types.js:1502:7)
>     at WrappedUnionType.Type.toBuffer (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\node_modules\avsc\lib\types.js:652:8)
>     at Object.<anonymous> (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\src\kafka\registry.ts:47:23)
>     at Module._compile (internal/modules/cjs/loader.js:1157:30)
>     at Module.m._compile (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\node_modules\ts-node\src\index.ts:814:23)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
>     at Object.require.extensions.<computed> [as .ts] (C:\Users\vadymr\Documents\provisioning\ui-dev-tools\jea-console-ui\server\node_modules\ts-node\src\index.ts:817:12)
>     at Module.load (internal/modules/cjs/loader.js:1001:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:900:14)
> 

Does anybody know what is wrong with this code?

**Comment by mtth** [comment]
The issue is that array schemas represent [unions](https://avro.apache.org/docs/current/spec.html#Unions) in Avro and since yours contains two records, it expects its instances to be [wrapped](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts).

You have a few options here, for example:

+ If you didn't meant to declare a top-level union type and only expect `WfTask` instances, you can shuffle your schema from (pseudo-code) `[{name: 'WfControlKey'} {name: 'WfTask'}]` to `{name: 'WfTask'}`, replacing the first nested reference to `'WfControlKey'` with the full schema. Alternatively you can keep your schema as-is and extract the type programmatically, either via `type.types[1]` or via the registry `registry['com.vad.wf.api.task.WfTask']`.
+ If you expect a mix of both types at the top-level, you'll need to wrap them before encoding. So, for example, your message would become `{'com.vad.wf.api.task.WfTask': task}`.

**Comment by vadymrybak** [comment]
> The issue is that array schemas represent [unions](https://avro.apache.org/docs/current/spec.html#Unions) in Avro and since yours contains two records, it expects its instances to be [wrapped](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts).
> 
> You have a few options here, for example:
> 
> * If you didn't meant to declare a top-level union type and only expect `WfTask` instances, you can shuffle your schema from (pseudo-code) `[{name: 'WfControlKey'} {name: 'WfTask'}]` to `{name: 'WfTask'}`, replacing the first nested reference to `'WfControlKey'` with the full schema. Alternatively you can keep your schema as-is and extract the type programmatically, either via `type.types[1]` or via the registry `registry['com.vad.wf.api.task.WfTask']`.
> * If you expect a mix of both types at the top-level, you'll need to wrap them before encoding. So, for example, your message would become `{'com.vad.wf.api.task.WfTask': task}`.

Thank you! Can please clarify the option with registry? Is it something I have to do with the way I call forSchema?

```
const _registry: any = {};
const _schema: any      = JSON.parse(schema);
const _mainType: any   =  avsc.Type.forSchema(_schema, {registry: _registry});
```

**Comment by mtth** [comment]
You can read the type from the registry after calling `forSchema` (which populates it):

```javascript
const _registry: any = {};
const _schema: any      = JSON.parse(schema);
const _mainType: any   =  avsc.Type.forSchema(_schema, {registry: _registry});
const usedType = _registry['com.vad.wf.api.task.WfTask'];
```

**Comment by vadymrybak** [comment]
> You can read the type from the registry after calling `forSchema` (which populates it):
> 
> ```js
> const _registry: any = {};
> const _schema: any      = JSON.parse(schema);
> const _mainType: any   =  avsc.Type.forSchema(_schema, {registry: _registry});
> const usedType = _registry['com.vad.wf.api.task.WfTask'];
> ```

Ohhh and then I can just call that type to encode like below?

`console.log(usedType.toBuffer(message));`

**Comment by mtth** [comment]
Yes, the values in the registry are regular `avro.Type`s (same as what `forSchema` returns).

**Comment by vadymrybak** [comment]
> Yes, the values in the registry are regular `avro.Type`s (same as what `forSchema` returns).

This code works perfectly now! Thanks for your help

```
const _registry: any = {};
const _schema: any      = JSON.parse(schema);
avsc.Type.forSchema(_schema, {registry: _registry});
const usedType: any = _registry['com.vad.wf.api.task.WfTask'];

console.log(usedType.toBuffer(message));
```
