### ISSUE TITLE
JS BigInt support

### ISSUE THREAD

**Issue by infloop** [mtth/avsc#285]
Hello!

Can you add BigInt support?

https://github.com/tc39/proposal-bigint

Thanks!

**Comment by mtth** [comment]
Do you mean to support `BigInt` for `long` types? If so, it's already supported via custom long types. I've updated [the documentation](https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types) to include an example.

**Comment by infloop** [comment]
Yeah, thanks, but there are a couple of issues with the example from documentation.

1) According to https://v8.dev/features/bigint
`Another thing to note is that the >>> operator, which performs an unsigned right shift, does not make sense for BigInts since they’re always signed. For this reason, >>> does not work for BigInts.`

2) The code below does not work:

```

**Comment by infloop** [comment]
I've done some research and I think this is a good example:

```
import * as avro from 'avsc';


const longType = avro.types.LongType.__with({
  fromBuffer: (buf) => {
    return BigInt.asIntN(64, buf.readBigInt64LE(0));
  },
  toBuffer: (n) => {
    const buf = Buffer.alloc(8);
    buf.writeBigInt64LE(n);
    return buf;
  },
  fromJSON: BigInt,
  toJSON: Number,
  isValid: (n) => typeof n == 'bigint',
  compare: (n1, n2) => n1 === n2 ? 0 : (n1 < n2 ? -1 : 1),
});

// Our schema here is very simple, but this would work for arbitrarily complex
// ones (applying to all longs inside of it).
const type = avro.Type.forSchema('long', {registry: {'long': longType}});

// Singed Int 64 value
const value = 2n ** (63n) - 1n;
const negativeValue = value * -1n ;

const encoded = type.toBuffer(value);
const decoded = type.fromBuffer(encoded);

const encoded2 = type.toBuffer(negativeValue);
const decoded2 = type.fromBuffer(encoded2);

console.log(value); // 9223372036854775807n
console.log(decoded);

console.log(negativeValue); // -9223372036854775807n
console.log(decoded2);

```

**Comment by mtth** [comment]
Thanks; I wasn't aware of the new buffer methods. I've updated the documentation.

**Comment by infloop** [comment]
Thanks! And btw... your library is awesome!

**Comment by mtth** [comment]
Happy to help!
