### ISSUE TITLE
reading decimal type

### ISSUE THREAD

**Issue by pwmcintyre** [mtth/avsc#287]
I have an avro file which has some data as type "decimal", and i'm having trouble making sense of it

using a command-line tool `fastavro` I can inspect my file to see the correct values:
```json
{
    "rate_net_amount": "5.84"
}
```

but the same file via `avsc` shows this:
```
{
    "rate_net_amount": {
        "data": [
            2,
            72
        ],
        "type": "Buffer"
    }
}
```

this is the schema:
```json
{
    "type": "record",
    "name": "baseRecord",
    "fields": [
        {
            "name": "rate_net_amount",
            "default": null,
            "type": [
                "null",
                {
                    "logicalType": "decimal",
                    "scale": 2,
                    "type": "bytes",
                    "precision": 10
                }
            ]
        }
    ]
}
```

seeking advice!

**Comment by pwmcintyre** [comment]
reading the avro spec
https://avro.apache.org/docs/1.8.2/spec.html#Decimal
> The decimal logical type represents an arbitrary-precision signed decimal number of the form unscaled × 10^scale.

so in my example, the value `5.84` becomes `584`

> A decimal logical type annotates Avro bytes or fixed types. The byte array must contain the two's-complement representation of the unscaled integer value in big-endian byte order. The scale is fixed, and is specified using an attribute.

I had to look lookup what two's-complement is, but i also found an online converter to help:
https://www.exploringbinary.com/twos-complement-converter/

so 584 becomes the following in twos-compliment:
```
0000001001001000
```

what's interesting is the value 72 is similar, with the most significant bit missing:
```
0000000001001000
      ^
```

is there something getting truncated?

**Comment by pwmcintyre** [comment]
I think I get it now - as per the spec it's a "byte array" ... which javascript just presents as an array numbers

earlier i was ignoring the "2" in the array (because I didn't understand it)

here's 2 in two's-compliment
```
00000010
```

and here's 72
```
01001000
```

and here they are next to each other ... which matches my 584!
```
00000010 01001000
```

**Comment by pwmcintyre** [comment]
as an experiment ... here's some code that works for this example

```TypeScript
function reconstruct( bytes: number[], scale: number ): number {

    // convert items to binary representation, pad to length 8
    const binary_string_bytes = bytes.map( val => val.toString(2).padStart(8, '0') )

    // join to 1 long binary "number"
    const binary_string = binary_string_bytes.join('')

    // convert to a number
    const num = parseInt( binary_string, 2 )

    // shift scale
    const result = num / Math.pow( 10, scale )

    return result

}

console.log( reconstruct([ 2, 72 ], 2) )
// > 5.84
```

problems:
- this surely can't be the best way ... convert numbers to string and back
- doesn't cater for negatives

**Comment by pwmcintyre** [comment]
trying again using NodeJS's Buffer
https://nodejs.org/api/buffer.html#buffer_buf_readintbe_offset_bytelength

```TypeScript
function reconstruct( bytes: number[], scale: number ): number {

    // read into buffer
    const buf = Buffer.from( bytes )

    // convert to a number
    const num = buf.readIntBE( 0, bytes.length )

    // shift scale
    const result = num / Math.pow( 10, scale )

    return result

}

console.log( reconstruct([ 2, 72 ], 2) )
// > 5.84
```

... although I'm still yet to see how it handles negatives

**Comment by mtth** [comment]
Hi @pwmcintyre. You have the right idea: Avro decimals are encoded similar to bytes and use logical type "magic" to appear differently when decoded.

`avsc` also supports logical types (see [this section](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) in the wiki) and there is even a sample `DecimalType` implementation available [here](https://gist.github.com/mtth/1aec40375fbcb077aee7#file-decimal-js). Using it, we can make our code much more intuitive (as well as support negative numbers):

```javascript
const logicalTypes = {decimal: DecimalType}; // `DecimalType` from the file above.

// Parse the schema, providing our decimal implementation.
const type = avro.Type.forSchema(schema, {logicalTypes});

const buf = Buffer.from([2, 4, 2, 72]); // A valid encoded record for your schema.
const val = type.fromBuffer(buf); // The parsed value.
const dec = val.rate_net_amount; // A `Decimal` instance.
console.log(dec.toNumber()); // 5.84!
```

Since it sounds like you are reading object container files, you can wire the logical type via the decoder's `parseHook` option:

```javascript
const decoder = avro.createFileDecoder('path.avro', {
  parseHook: (schema) => avro.Type.forSchema(schema, {logicalTypes})
});
```

Finally, note that the decimal implementation above is relatively simple (and dated - it predates classes). For production use-cases, I would recommend deriving your own from it, making use of `BigInt`s to support arbitrarily large unscaled values.

**Comment by pwmcintyre** [comment]
Hi @mtth

just wanted to let you know that I got it working, thanks for the details / links

my work is in typescript, let me know if you'd like me to publish an example somewhere based on my progress

**Comment by pwmcintyre** [comment]
For what it's worth -- here's how we solved this in Typescript

### Create Decimal class
```TypeScript
// Decimal is a numeric type which allows greater control 
// over scale and precision than JavaScript's primitive "number"
export class Decimal {
    constructor(
        public readonly unscaled: number,
        public readonly precision = 32,
        public readonly scale = 0,
    ){}
    public toNumber (): number {
        return this.unscaled * Math.pow(10, -this.scale);
    }
}
```

### extend LogicalType to decode decimal
```Typescript
// DecimalType allows us to extend avsc to properly decode the "decimal" logical type to a custom Decimal object
// for more info see an issue we raised here:
// https://github.com/mtth/avsc/issues/287
// or documentation on logical types here:
// https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types
class DecimalType extends avro.types.LogicalType {

    protected precision: number
    protected scale: number

    constructor(schema: avro.Schema, opts?: any){

        super(schema, opts)

        // make typescript happy
        const s = schema as avro.schema.LogicalTypeExtension

        // parse precision
        if ( !s.precision || s.precision !== (s.precision | 0) || s.precision <= 0) {
            throw new Error('invalid precision')
        }

        // parse scale
        if (s.scale !== (s.scale | 0) || s.scale < 0 || s.scale > s.precision) {
            throw new Error('invalid scale')
        }

        // determine if we can work with the specified precision
        if (avro.Type.isType(this.underlyingType, 'fixed')) {
            const size = ( this.underlyingType as avro.types.FixedType ).size
            const maxPrecision = Math.log(Math.pow(2, 8 * size - 1) - 1) / Math.log(10)
            if (s.precision > (maxPrecision | 0)) {
                throw new Error('fixed size too small to hold required precision')
            }
        }

        this.precision = s.precision
        this.scale = s.scale

    }

    // convert Buffer to Decimal
    protected _fromValue(val: Buffer): any {
        return new Decimal(val.readIntBE(0, val.length), this.precision, this.scale)
    }

}
```

### Optional: extend the above to return a primitive number
```TypeScript
// DecimalToNumberType is an extension to the above
// which returns a primitive javascript "number" instead of a Decimal
// Depending on your use-case, this may be more convenient
class DecimalToNumberType extends DecimalType {
    protected _fromValue(val: Buffer): any {
        return super._fromValue(val).toNumber()
    }
}
```

### wire in the decoder for "decimal"
```TypeScript
const avroDecoder = new avro.streams.BlockDecoder({
    parseHook: (schema) => avro.Type.forSchema(schema, { logicalTypes: { decimal: DecimalType } })
})
```
