### ISSUE TITLE
Special Character in Schema [Question]

### ISSUE THREAD

**Issue by MichaelHirn** [mtth/avsc#290]
Hey @mtth - thank you for this repo. I have a question about special character support, I understand that this is partially just general avro specifications, but the solution via aliases doesn't seem to work and I feel that this part might be `avsc` related. So here's the situation:

Given the following JSON object

```js
{ year: 2001, $type: "org.xxx.Date" }
```

I would like to create an avro schema definition, e.g. something like this in Avro IDL

```avdl
record Date {
  int year;
  string $type;
}
```

Now this doesn't work because the type names are not allows to start with `$`. So I tried to change it to the avro schema definition to this:

```avro
record Date {
  int year;
  string @aliases(["$type"]) _type;
}
```

This compiles to `.avsc` as expected, however, I expected that the initial JSON object from above (`{ year: 2001, $type: "..." }`) would fit the schema now but it doesn't and throws the usual error message via `avsc` (`invalid "string": undefined`).

So the question is: Is `aliases` the way to go to make type names with special characters work and if so is this a bug/not supported in `avsc` lib and if it's not the way to go, what is the recommended way for special characters (e.g. must the JSON object be preprocessed first to rename the key from `$type` to `_type`)?

**Comment by mtth** [comment]
Hey @MichaelHirn. Aliases are only used during schema evolution: ["Aliases function by re-writing the writer's schema using aliases from the reader's schema. "](https://avro.apache.org/docs/current/spec.html#Aliases). They are not applied when encoding or decoding JSON.

We need a different mechanism for your use-case. Pre-processing the objects outside of `avsc` is one option. An alternative is to use a [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) to do it transparently. The logical type would automatically convert the prefix before encoding (in `_toValue`) and after decoding (in `_fromValue`).

**Comment by MichaelHirn** [comment]
Appreciated your quick response. I had to work on a few other things but now coming back to this and wanted to circle back.

I played around with `logical types` and looks very interesting and I appreciate the tight integration into the process without doing some external pre/post processing. However, I looked at your gist examples but I'm not sure if they can fix the problem. It seems to me they only have access to the value and not the key (prefix)?

I created a gist here to show what I have done with the logical type and the problem I ran into: https://gist.github.com/MichaelHirn/f73d3ed6440a5afc4fe557b6a7d48c07

Would love to use any hooks that avro/avsc offers and not have to step outside of it, but would need you to push me in the right direction 🙏

**Comment by mtth** [comment]
In this case, we'll use the logical type on the record directly rather than its fields. Here's a snippet to show how it could work:

```javascript
/**
 * A logical type which remaps record keys.
 *
 * This is useful when the in-memory representation uses characters which are
 * invalid in an Avro schema (e.g. `$`).
 *
 * We make the mapping configurable to give an example of how to customize
 * logical types via the schema (here via `keyMapping`). This can be removed if
 * not needed (e.g. if the mapping is constant).
 */
class KeyMappingRecord extends avro.types.LogicalType {
  constructor(schema, opts) {
    super(schema, opts);
    this._mapping = schema.keyMapping;
  }

  /** Converts from stored to exposed representation. */
  _fromValue(val) {
    return this._mapKeys(val, this._mapping[0], this._mapping[1]);
  }

  /** Converts from exposed to stored representation. */
  _toValue(any) {
    return this._mapKeys(any, this._mapping[1], this._mapping[0]);
  }

  _mapKeys(unmapped, from, to) {
    const mapped = {};
    for (const [key, val] of Object.entries(unmapped)) {
      mapped[key.replace(from, to)] = val;
    }
    return mapped;
  }
}

// Let's use our logical type on a sample schema:
const type = avro.Type.forSchema({
  type: 'record',
  logicalType: 'key-mapping-record',
  keyMapping: ['_', '$'], // Swap underscores and dollars.
  fields: [
    {name: 'year', type: 'int'},
    {name: '_type', type: 'string'}, // Exposed as `$type`.
  ],
}, {logicalTypes: {'key-mapping-record': KeyMappingRecord}});

// We can check that it works:
const obj = {year: 2020, $type: 'TYPE'};
console.log(type.isValid(obj)); // True.
console.log(type.toBuffer(obj)); // OK!
```

The mapping logic above is very simple (just a `replace` call) but should be straightforward to extend to fit your use-case. Also, since it looks like you are using `.avdl` files, the corresponding IDL would look like:

```
@logicalType("key-mapping-record")
@keyMapping(["_", "$"])
record Test {
  int year;
  string _type;
}
```

Finally, in case you want to avoid explicitly adding the logical type annotations, you can use a `typeHook` to dynamically add them. For example, you could use this one to add them everywhere:

```javascript
/** Hook which adds the key mapping logical type to all records. */
function typeHook(schema, opts) {
  if (schema.type === 'record') {
    Object.assign(schema, {
      logicalType: 'key-mapping-record',
      keyMapping: ['_', '$'],
    });
  }
}
```

**Comment by MichaelHirn** [comment]
Thank you for this example @mtth - this is beautiful and works like a charm.

Will close the issue and hope that it helps ppl in the future.
