### ISSUE TITLE
truncated buffer error using schema array

### ISSUE THREAD

**Issue by akki192** [mtth/avsc#292]
Hello,

I'm getting avro binary content from an endpoint which I'm trying to decode. I have schema as an array stored locally in "group.avsc" file. I'm using below code to decode it:

```
    const registry = {}
    const avroData = await this.get(`/data/avro/123`)
    const schemaArray = fs.readFileSync(path.resolve(__dirname, '../../../schemas/group.avsc'))
    const jsonSchemaArray = JSON.parse(schemaArray)
    for (var i = 0; i < jsonSchemaArray.length; i++) {
      const jsonSchemaComponent = jsonSchemaArray[i]
      avro.parse(jsonSchemaComponent, { registry: registry })
    }
    const type = registry['GroupResponse']

    var buf = Buffer.from(data, 'binary')
    const decodedMessage = type.fromBuffer(buf)
```

This results in "truncated buffer" error.

Data received from endpoint:
```
��և��
1.2.0SMEHad720db2-05bc-46f2-bc3e-c05089c0f5e802020-03-31T21:36:29.273Z...
```

Message [JSON.stringify(data)]:
`�\u0001�և��\u000b\u001c\u0016\n1.2.0\u0006SMEH83c65f8d-85c8-4969-9340-7a5ff63990de02020-04-01T15:31:15.135Z...`

HEX value:
`efbfbd01efbfbdd687efbfbdefbfbd0b1c160a312e322e3006534d45483833...`

The schema is similar to the one mentioned in https://github.com/mtth/avsc/issues/279.

I even tried with below code which results in "invalid union index: -38" error.
`const decodedMessage = type.fromBuffer(buf.slice(9))`

I tried with this code and it results in below mentioned error:
```
var buf = Buffer.from(data, 'utf8')
const decodedMessage = type.fromBuffer(buf.slice(18))
```

Error:
```
Error: potential precision loss
at LongType._read (C:\\Work\\Workspaces\\vscode-workspace\\order-history-api\\node_modules\\avsc\\lib\\types.js:912:11)
at UnwrappedUnionType._read (C:\\Work\\Workspaces\\vscode-workspace\\order-history-api\\node_modules\\avsc\\lib\\types.js:1310:23)
...
```

I also implemented below piece of code to resolve this issue:
```
    const Long = require('long')
    const longType = avro.types.LongType.__with({
      fromBuffer: (buf) => {
        return new Long(buf.readInt32LE(), buf.readInt32LE(4))
      },
      toBuffer: (n) => {
        const buf = Buffer.alloc(8)
        buf.writeInt32LE(n.getLowBits())
        buf.writeInt32LE(n.getHighBits(), 4)
        return buf
      },
      fromJSON: Long.fromValue,
      toJSON: (n) => +n,
      isValid: Long.isLong,
      compare: (n1, n2) => n1.compare(n2)
    })
    const registry = { long: longType }
    …
    var buf = Buffer.from(data, 'utf8')
    const decodedMessage = type.fromBuffer(buf.slice(18))
```

But, now I'm getting "truncated buffer" error.

Any idea what could be the problem?

Thanks,
Akshay

**Comment by akki192** [comment]
I tried with this code and it results in below mentioned error:
```
var buf = Buffer.from(data, 'utf8')
const decodedMessage = type.fromBuffer(buf.slice(18))
```

Error:
```
Error: potential precision loss
at LongType._read (C:\\Work\\Workspaces\\vscode-workspace\\order-history-api\\node_modules\\avsc\\lib\\types.js:912:11)
at UnwrappedUnionType._read (C:\\Work\\Workspaces\\vscode-workspace\\order-history-api\\node_modules\\avsc\\lib\\types.js:1310:23)
...
```

**Comment by mtth** [comment]
Hi. It looks like the data you are receiving doesn't match your schema. Is the hex string above from the raw server response? If so, there is likely an encoding issue upstream: the data contains multiple `efbfbd` sequences (it's a unicode replacement character).

**Comment by akki192** [comment]
Hi Matthieu,

The upstream API is also consumed by a java program which successfully decodes the content hence it does not look like an issue with the upstream API.
```
var buf = Buffer.from(data, 'utf8')
const decodedMessage = type.fromBuffer(buf.slice(18))
```
I ran the above code for different inputs and looks like 50% of the responses are decoded successfully. The other half fail with "truncated buffer" error.

Alter, looking further it looks like if the response contains few Japanese character (most probably Hiragana syllabaries) then it fails. It works fine for Japanese Katakana syllabaries.

Have you come across this kind of issue in the past or aware of possible fix?

Thanks,
Akshay

**Comment by mtth** [comment]
The error might be in upstream node.js code. For example is the data encoded with something else than `utf8`? Should the offset (18 here) vary per message? I would prefer if you shared the data hex-encoded by gist.

**Comment by akki192** [comment]
Hi Matthieu,

The upstream code is written in java. Please fin the Hex encoded data below:

Working:
Hex original message: efbfbd01efbfbdd687efbfbdefbfbd0b1c160a312e322e3006534d454830313439396537372d373231392d343038312d383634302d39653362373035306337366230323032302d30342d31335431333a34393...
Hex after slice(18): 0a312e322e3006534d454830313439396537372d373231392d343038312d383634302d39653362373035306337366230323032302d30342d31335431333a34393a31362e3038385a0100000202efbfbdefbfbd...

Failing:
Hex original message: efbfbd01efbfbdd687efbfbdefbfbd0b1c160a312e322e3006534d454831393937316265302d333738642d346636362d393130302d38313535323234323136306330323032302d30342d31335431333a35323...
Hex after slice(18): 0a312e322e3006534d454831393937316265302d333738642d346636362d393130302d38313535323234323136306330323032302d30342d31335431333a35323a35362e3338335a0100000202efbfbdefbfbd...


Thanks,
Akshay

**Comment by mtth** [comment]
Can you include the schema too? The snippet above uses a `GroupResponse` type but it is not present in the other issue. W.r.t. upstream code, I meant `this.get` in your snippet. It's strange that your data includes `efbfbd` sequences; in general that's a strong signal of corruption due to encoding mismatches. The 18 offset is also non-standard, can you please explain how it is computed?

**Comment by akki192** [comment]
Hi Matthieu,

I am not suppose to share the schema file on internet. I had emailed it to your mail id. Let me know if there is any other secure way to share it. I came up with 18 offset by trial and error method.

Even I thought the data is curupted but, there is another listener to the same API in java which is able to successfully decode these responses.

Thanks,
Akshay

**Comment by mtth** [comment]
Hi Akshay. I don't open zip attachments for security reasons; I'm afraid I won't be able to help you further. If you have access to the Java listener's code, I would recommend taking a look at that code to understand where the offset comes from and which encoding is used to transmit data over the wire.
