### ISSUE TITLE
How to encode custom ArrayType [Question]

### ISSUE THREAD

**Issue by vladaman** [mtth/avsc#295]
I am trying to figure out how to encode String to Array. Given I have following JSON to encode:

```json
let dataToEncode = {"someField": "11,23,99"}
```

I'd like to encode this into:
```json
{
    "type": "record",
    "doc:": "A basic schema to test array encoding",
    "fields": [{
            "name": "someField",
            "type": {
                "type": "array",
                "items": "long"
            }
        },
  ]
}
```

Should I use logicalTypes, typeHooks how how to do custom encoding?

**Comment by mtth** [comment]
Logical types allow you to provide a custom _view_ of the data and doesn't affect how it is stored. The encoded data always matches the schema's type.

This is most useful when the underlying type is not very convenient to work with (e.g. milliseconds representing a time, which can be viewed as a `Date` with a logical type). In your example, the schema already has the type you want (array of longs). It seems strange to use a logical type to provide a less convenient representation.

If your goal is to ingest data with a suboptimal format to store it with a better one, logical types might be overkill. I would instead recommend doing this processing in an "sanitization layer" as close to the source of data as possible. The rest of your code (including your Avro schema) then wouldn't need to be aware of this transformation.
