### ISSUE TITLE
How to include schema with serialized data?

### ISSUE THREAD

**Issue by ajelden** [mtth/avsc#301]
We've been using the avsc package for about a year now, and like it alot.

I am currently successfully serializing data using the avsc package--all good, and I am posting the serialized data as a blob, and can see the data in the output of a kinesis consumer.  I have now been asked to "include the schema with the serialized data".  Have you heard of doing that before? Is there an option for including the schema as part of serialization, or do I need to construct an object that includes the schema and the data, and then serialize that?

Thanks for any help.

**Comment by mtth** [comment]
Hi @ajelden. It will depend on your use-case and what the readers are able to do to get the schema. One thing I've seen done is emitting your data within an [object container file](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) (see [this thread](https://github.com/mtth/avsc/issues/246) for a sample implementation and caveats). Another option is to use a [schema registry](www.confluent.io/schema-registry) and prepend schema IDs to your encoded data (via which the backend can retrieve the full schema).

**Comment by ajelden** [comment]
Thanks, Matthieu.

**Comment by ajelden** [comment]
Thanks again, Matthieu. We followed the example of the `encodeMessage()` function in #246 which worked well for us. Closing this question.
