### ISSUE TITLE
New instance from Type with Default values

### ISSUE THREAD

**Issue by gaotisan** [mtth/avsc#304]
How can I create a new instance of a Type with the Dafault values,? (no random values).
It is possible?? Sorry I can't see the methond.

Thanks,

**Comment by mtth** [comment]
You can use the record's constructor or clone an empty object:

```js
const type = avro.Type.forSchema({
  name: 'Example',
  type: 'record',
  fields: [
    {name: 'one', type: 'int', default: 1},
    {name: 'two', type: 'string', default: 'foo'},
  ],
});

const Example = type.recordConstructor;
const e1 = new Example(); // e1 == {one: 1, two: 'foo'}
const e2 = type.clone({}); // e2 == e1
```

If your record has fields without defaults, you'll need to specify those.
