### ISSUE TITLE
Function hangs when trying to parse a bad topic

### ISSUE THREAD

**Issue by Genysys** [mtth/avsc#306]
I am consuming topics from a kafka stream that I have no control over the upstream validation. I therefore need to be able to handle this client side. Unfortunately, the code hangs when it tries to resolved a corrupted message against a schema. This leads to it blowing the heap and raising an OOM exception. 

I have tried to implement validation by using the "isValid" method i.e. 

```
if (typeV1.isValid(typeV1.fromBuffer(buf))) {
      return {
        version: 1,
        suggestion: typeV1.fromBuffer(buf),
      };
```

but the code still hangs at the `fromBuffer(buf)` .

Is there a way to handle this error i.e. detect if the packet is corrupted and discard it?

**Comment by mtth** [comment]
Hi @Genysys. I'm afraid there is no way to handle this type of corruption at the moment. Do you have more information on the data and type responsible? We might be able to expose a detection hook if the cause is corrupted array/map sizes.

**Comment by Genysys** [comment]
Hi @mtth ,

Thanks for coming back to me quickly on this. I have created a script that reproduces the error here <https://gist.github.com/Genysys/e1a183cb5c15f2e239f1b7a2004bda83>.

I hope this helps
