### ISSUE TITLE
Support optional attributes at Field level

### ISSUE THREAD

**Issue by marcuskielly** [mtth/avsc#307]
The avro spec states you can add attributes at the schema level as long as they don't affect serialisation. Is it possible to support additional attributes for the elements in a Record's array of fields? 

"Attributes not defined in this document are permitted as metadata, but must not affect the format of serialized data."

**Comment by mtth** [comment]
Hi @marcuskielly, can you clarify your use-case? `avsc` already supports additional metadata in the schema (as field attributes and elsewhere), they are simply ignored during parsing.

**Comment by marcuskielly** [comment]
For example adding GDPR related metadata to fields. When you say they are ignored during parsing, does that mean avsc strips them out? Or do they get persisted in the schema?

**Comment by marcuskielly** [comment]
Having delved further -  can see that avsc is indeed not parsing the additional fields - although it still causes TS to fail type checking against the additional fields
