### ISSUE TITLE
Not able to deserialise avro 

### ISSUE THREAD

**Issue by Vidz51** [mtth/avsc#318]
Hi
I am using node-rdKafka to produce data in avro format. For Avro I am using avsc. I am getting error on consumer side while deserialising. I know I have to encode my msg before sending it as byteStream but not sure how.  
In code I am doing the following:  
1. Fetching and parsing avro schema from url.
2. converting to byte array :  magic byte (0X0), template id and data 
3. pushing it all in kafka.

I know i am doing something wrong in step 2. Some help would be great!

```
import avro from "avsc";
import axios from "axios";
import { KafkaProduce } from "../kafkaCofiguration";
import logger from "../logger";

let schema;

const readAvroSchema = async (templateId, hiveSchemaURL) => {
	const avroSchema = await axios({
		method: "get",
		url: `${hiveSchemaURL}/${templateId}`,
	}).catch((err) => {
		logger.error("Error occcured while fetching hive schema, ", err);
	});

	return avro.parse(JSON.stringify(avroSchema.data));
};

const convertJsonToAvro = async (data, hiveDetails) => {
	if (!schema) {
		schema = await readAvroSchema(hiveDetails.templateId, hiveDetails.hiveSchemaURL);
	}

	return schema.toBuffer(data);
};

const pushToHive = async (data, hiveDetails) => {
	if (!hiveDetails.isHiveEnabled) {
		return;
	}
	const avroByteArr = await convertJsonToAvro(data, hiveDetails);
	const output = [];
	output.push(Buffer.from([0x0])); //Magic byte
	output.push(Buffer.from(parseInt(hiveDetails.templateId, 10)));
	output.push(Buffer.from(avroByteArr));

	KafkaProduce(hiveDetails.topicName, null, Buffer.concat(output));
};
export { pushToHive };
```

**Comment by mtth** [comment]
Hi @Vidz51. It's hard to say without knowing more about the error and expected format our your message. If I had to point at one thing, it would be the template ID serialization since Avro uses a different encoding for numbers ([docs](https://avro.apache.org/docs/current/spec.html#binary_encoding)).
