### ISSUE TITLE
createFileDecoder for Azure Blob

### ISSUE THREAD

**Issue by NidalShater** [mtth/avsc#319]
I'm trying to read an avro file from Azure blob storage (which is generated by EventHub capture process), when I manually download the file and use the following code:
```
decode: async function (avroFile) {
    let readable = avro.createFileDecoder(avroFile);
    return new Promise((resolve, reject) => {
        const chunks = [];
        readable.on('data', function (chunk) {
          chunks.push(Buffer.from(chunk.Body));
        });
        readable.on('end', function () {
          resolve(chunks.join("\r\n"));
        });
        readable.on('error', function (err) {
          reject(err);
        });
    });
  }
```
it worked correctly, what I'm trying to do is to pass the file on azure using this code:
```
// Create the BlobServiceClient object
const blobServiceClient = BlobServiceClient.fromConnectionString(
  AZURE_STORAGE_CONNECTION_STRING
);
 const containerClient = blobServiceClient.getContainerClient(containerName);
    const blockBlobClient = containerClient.getBlockBlobClient(blobName);
    const downloadBlockBlobResponse = await blockBlobClient.download(0);
      const objects = await avro.decode(downloadBlockBlobResponse.readableStreamBody);
      return objects;
```
but this won't work properly, is there a way to use `createStringDecoder` or something like this to read the content of Blob after downloading it using the `BlobServiceClient`?

**Comment by mtth** [comment]
IIUC you are looking for a way to decode a buffer directly. If so, you can use a [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts).

```js
new avro.streams.BlockDecoder()
  .on('data', (val) => { /* Do something with each decoded value. */ })
  .end(buf); // The downloaded binary data.
```

`createFileDecoder` is a convenience wrapper on top of it. Take a look at this related issue for more details: https://github.com/mtth/avsc/issues/107
