### ISSUE TITLE
Allow hyphen characters in fully qualified names

### ISSUE THREAD

**Issue by joey-kendall** [mtth/avsc#323]
I have an invalid name error getting thrown for some of my fields.  My schema is quite complex and nested quite a bit, but the gist of the issue is that one of my deeply nested arrays has a name: `BlogsArray`.  It's not an invalid name until the fully qualified portion gets added on.  Then it becomes `department.bounded-context.BlogArray`.  The `department` and `bounded-context` are company requirements we have for publishing data to Kakfa.  The bounded context name usually ends up being hyphenated if it is multiple words.

To be honest I'm not 100% familiar with the reasoning why the field name can't have hyphens.  So I'm not sure if it would be best to only check the last index in the array after splitting or is there any reason the qualified parts of the name can't contain hyphens?

For clarity my schema looks like this:
```
{
	"type":"record",
	"namespace":"skills.expert-portal",
	"name":"`Expertj.v1.value`",
	"fields":[
	{
		"name":"handle",
		"type":"string",
		"doc":"The experts handle, generated by identity when their account was created."
	},
	{
		"name":"authorId",
		"type":[
			"null",
			"string"
		],
		"default":null,
		"doc":"The experts author id, if they have one.  Generated by Author Home when they are approved as an author."
	},
	{
		"name":"firstName",
		"type":"string",
		"doc":"The first name of the expert."
	},
	{
		"name":"lastName",
		"type":"string",
		"doc":"The last name of the expert."
	},
	{
		"name":"email",
		"type":"string",
		"doc":"The experts email address, entered when their account was created."
	},
	{
		"name":"blogs",
		"type":{
			"type":"array",
			"items":{
				"type":"record",
				"name":"BlogsArray",
				"fields":[
					{
						"name":"id",
						"type":{
							"type":"string",
							"logicalType":"UUID",
							"doc":"The unique id for a blog entry."
						}
					},
					{
						"name":"title",
						"type":"string",
						"doc":"The title of the blog."
					},
					{
						"name":"url",
						"type":"string",
						"doc":"The url of the blog"
					},
					{
						"name":"description",
						"type":"string",
						"doc":"The provided description for their blog and the topics they cover."
					}
				]
			}
		},
		"doc":"Experts can have 0 or more blogs they have provided details about.  0 will be represented by an empty array"
	}
]
}
```
And the name: `skills.expert-portal.BlogsArray` raises the exception from the `qualify` method in utils.js

**Comment by mtth** [comment]
Thanks for the detailed writeup. This restriction is inherited from the Avro specification, which does not allow hyphens within names or namespaces: https://avro.apache.org/docs/current/spec.html#names. These requirements are usually introduced to help with portability (particularly when code-generation is involved) but I don't know the specifics of this decision. I'd suggest asking on the [Avro mailing list](https://avro.apache.org/mailing_lists.html) to learn more.

W.r.t. getting things to work, my recommendation would be to make the schema compliant by renaming the namespaces. However since that you mention that the names are a company requirement, I'll assume that this is not possible and suggest an alternative: using a type hook to make the names compliant dynamically. For example, to replace hyphens with underscores (allowed by the Avro spec):

```js
/**
  * Returns a type hook replacing hyphens in namespaces with underscores.
  *
  * Sample usage:
  *  const type = avro.Type.forSchema(schema, {typeHook: createHook()});
  */
function createHook() {
  const visited = new Set();
  const sanitize = (s) => s.replace(/-/g, '_');
  return (schema, opts) => {
    if (typeof schema == 'string') {
      // This is a reference to a type.
      if (!schema.includes('.') && opts.namespace) {
        schema = `${opts.namespace}.${schema}`;
      }
      return opts.registry[sanitize(schema)];
    }
    const {name} = schema;
    if (!name || visited.has(name)) {
      return; // Nothing to do.
    }
    visited.add(name);
    if (schema.namespace) {
      schema.namespace = sanitize(schema.namespace);
    }
  };
}
```

The renaming function above can be tweaked to match your preferred conventions.

**Comment by joey-kendall** [comment]
Thank you for the response.  I see now that I have confused a few things in our implementation.  We have topic names (subjects) that we require to have the hyphenated bounded context I pointed to earlier.  The namespaces we don't have a requirement around and I was following the lead of a few other team members who took the first portion of the topic name and used it as the namespace which incorrectly brings the hyphen into the namespace.  

Thanks for the workaround too, but when I mentioned this to our platform team they were 😱 that we could create topics with hyphens in the namespaces, so... I think they are looking into a fix in the system they are designing.

Thanks again, I think I more fully understand avro and this is not actually an issue, I'm going to close this.
