### ISSUE TITLE
Property "order" is "field" property not "Record" property

### ISSUE THREAD

**Issue by pacocom** [mtth/avsc#325]
https://avro.apache.org/docs/1.8.2/spec.html#schema_record

https://github.com/mtth/avsc/blob/af9100173fbd495d54472efce8ded930c371e19e/types/index.d.ts#L36

![image](https://user-images.githubusercontent.com/7735329/97158375-9dbfb380-1779-11eb-8f65-a5d2d853f096.png)

**Comment by mtth** [comment]
Thanks for reporting. Fixed in https://github.com/mtth/avsc/commit/fce3292a6982c8b375691798b6d94a2bce6ac048.
