### ISSUE TITLE
Strict schema cloning/parsing

### ISSUE THREAD

**Issue by joey-kendall** [mtth/avsc#326]
Hello,  I'm not sure if this is a feature that belongs in Type.forSchema(...) or type.clone(...).

I have a schema that looks like this:
```
{
   "type":"record",
   "namespace":"exp.test_context",
   "name":"`TestEntityValue`",
   "fields":[
      {
         "name":"message",
         "type":"string",
         "doc":"The message."
      }
   ]
}
```
And data that looks like this:
```
{
   "message":"test message",
   "extraField":"this is an extra value, not defined on the schema."
}
```
and I'm calling:
```
  const parsedSchema = Type.forSchema(schema as Schema, { wrapUnions: true });

  const avro = parsedSchema.clone(value, {wrapUnions: true});
```
And I'd like to pass an option (and here I'm not sure where it belongs) to either forSchema or clone to raise an exception when there are properties on the data that are not on the schema rather than having them quietly ignored.

**Comment by mtth** [comment]
Hi @joey-kendall. You can use [`type.isValid`](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts)'s `noUndeclaredFields` option to check for such properties:

```js
const type = avro.Type.forSchema({
   "type":"record",
   "namespace":"exp.test_context",
   "name":"TestEntityValue",
   "fields":[
      {
         "name":"message",
         "type":"string",
         "doc":"The message."
      }
   ]
});

const val = {
   "message":"test message",
   "extraField":"this is an extra value, not defined on the schema."
};

console.log(type.isValid(val)); // true
console.log(type.isValid(val, {noUndeclaredFields: true})); // false
```

**Comment by joey-kendall** [comment]
@mtth Thanks for the response.  Is there a way from the isValid method to provide details as to where in the schema the value doesn't line up with the schema?

**Comment by mtth** [comment]
Yes: via an `errorHook`. [This thread](https://github.com/mtth/avsc/issues/148#issuecomment-362949027) has more information including a sample hook for this use-case.

**Comment by joey-kendall** [comment]
Okay, thanks.  I'll close this issue then.  Love the work you've done with this library!

**Comment by joey-kendall** [comment]
I've been working through the type.isValid option.  There is one piece of this that I'm struggling with still.
If I use the following example:
```
const type = avro.Type.forSchema({
   "type":"record",
   "namespace":"exp.test_context",
   "name":"TestEntityValue",
   "fields":[
      {
         "name":"message",
         "type":[null, "string"],
         "default": null
         "doc":"The message."
      }
   ]
});

const val = {
   "message":"test message",
};

console.log(type.isValid(val)); // false
```
So unless I already have converted my value to a union the isValid method will come back false (or in the case I've added an error hook an error with messaging about my value not being a valid `["null","string"]`

For context passing the above value to clone will convert the value to the expected result:
```
const value = {
    "message": "test message."
}
const result = parsedSchema.clone(value, {wrapUnions: true});   
// result.toString() is now:
{
    "message": {
        "string": "test message.",
    }
}
```

**Comment by mtth** [comment]
Are you specifying `{wrapUnions: true}` when creating the type locally? `type.isValid(val)` returns `true` with the snippet above.

```js
const schema = {
  name: 'Test',
  type: 'record',
  fields: [{name:'message', type: ['null', 'string'], default: null}]
};

const defaultType = avro.Type.forSchema(schema); // Equivalent to `{wrapUnions: 'auto'}`.
const wrappedUnionsType = avro.Type.forSchema(schema, {wrapUnions: true});

const val = {message: 'test message'};
console.log(defaultType.isValid(val)); // true
console.log(wrappedUnionsType.isValid(val)); // false
```

The default value for `wrapUnions` is `'auto'`, which only wraps unions [when needed](https://github.com/mtth/avsc/wiki/API#class-unwrappeduniontypeschema-opts). Your example is a "nullable union" (combination of `'null'` and another type) which never need wrapping, so is valid as-is with that setting. Depending on your production schema, using this default could give you the behavior you want. [`Type.forSchema`'s doc](https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts) has a little more information, including the other possible values for the option. Let me know if anything is still unclear.
