### ISSUE TITLE
jsonschema to Avro Schema (.avsc)?

### ISSUE THREAD

**Issue by spasquali-ww** [mtth/avsc#328]
Question: Can I use `avsc` to convert a JSONSchema to an Avro Schema? 

Apologies if I missed it in the docs.

**Comment by mtth** [comment]
Hi @spasquali-ww. This library doesn't include a JSON Schema converter (out of scope). It looks like there are a few packages with promising names though: https://www.npmjs.com/search?q=jsonschema%20avro. Hopefully one of them works for your use-case.

**Comment by spasquali-ww** [comment]
Makes sense, thank you for the great lib!
