### ISSUE TITLE
multiplex protocol

### ISSUE THREAD

**Issue by jfromaniello** [mtth/avsc#33]
Is there a way to define a multiplexed protocol? For instance having the server to reply a newer request before an older one? i.e. unorderdered. 

This is done usually with something like a "request id".

The AVRO specs mention this:

> The mechanism of correspondance is transport-specific. For example, in HTTP it is implicit, since HTTP directly supports requests and responses. **But a transport that multiplexes many client threads over a single socket would need to tag messages with unique identifiers.**

https://avro.apache.org/docs/1.7.7/spec.html

But I am not sure if is supported in this library.

**Comment by mtth** [comment]
It's supported, built-in even:

+ When you use a stateful transport (any node.js binary stream, for example a [`Socket`](https://nodejs.org/api/net.html#net_class_net_socket)), `avsc` will automatically tag each request and use the IDs to reassign the responses appropriately, even if they come out of order. (This is exactly what you mention.)
+ When you use a stateless transport (for example HTTP), then each request has a unique response associated with it already, so this reordering is done without even needing tags.

**Comment by jfromaniello** [comment]
Excellent! Indeed.. I tested before asking this but had something wrong on my test :)

Thanks for the explanation!
