### ISSUE TITLE
Avro.parse = Error: undefined type name: <namespace>.row

### ISSUE THREAD

**Issue by daffydee13** [mtth/avsc#330]
I am using Kafka-node + Avro-schema-registry library for nodejs consumer to decode Avro messages. Unfortunately I got an error in **Avro.parse = Error: undefined type name: ORCL.MOVIEDEMO.row**
_**Note - Schema is getting registered in Schema Registry through Oracle Golden Gate**_

After whole day of debugging I found out that schema has **following part which is giving error = {"name": "after", "type": ["null": "row"], "default": "null"}    --->  Avro parser is not able to parse "row" field**
How can I solve this issue by only changing consumer? Do we have any parsing option in AVRO Parser to resolve this? 

**Consumer Code**
var client = new Client({
    kafkaHost: KAFKA_CLIENT,
    groupId: 'msgs-groupid.group',
    fromOffset: 'latest'
});

var topics = [{
  topic: kafkaTopic
}];

var options = {
  autoCommit: true,
  encoding: 'buffer'
//  keyEncoding: 'buffer'
};

var consumer = new Consumer(client, topics, options);
consumer.on('message', function(rawMessage) {
  debugger;
  console.log("Raw Message", rawMessage);
  registry.decode(rawMessage.value)
    .then((msg) => {
      console.log(msg)
    })
    .catch(err=>console.log(err))
});

consumer.on('error', (e) => {
  console.log(e.message)
  consumer.close();
})`

**Schema:**
[https://jsoneditoronline.org/#right=local.pinipu&left=cloud.d384fa975c5548629450eda57f6bcf2a](url)

**Comment by mtth** [comment]
Hi @daffydee13. It looks like the registered schema is invalid, possibly missing the `row` type's definition (the link above doesn't work so I can't confirm). To work around it from the consumer's side, if you used `avsc` directly you could pass in the type in the `Type.forSchema`'s `registry` option. Since you're using higher level libraries you'll need to figure out how to pass in these options.

**Comment by daffydee13** [comment]
Thank you very much !!!, there seems to be some issue with parsing.
**Below is my Schema**, last field "After" has type ["null", "row"] and "row" is broadcasted in "Before" using **connect.name**. Ideally it should parse. But I am getting error not able to parse row field

{
  "type": "record",
  "name": "MOVIE",
  "namespace": "ORCL.MOVIEDEMO",
  "fields": [
    {
      "name": "table",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "op_type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "op_ts",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "current_ts",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "pos",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "primary_keys",
      "type": [
        "null",
        {
          "type": "array",
          "items": "string"
        }
      ],
      "default": null
    },
    {
      "name": "tokens",
      "type": [
        "null",
        {
          "type": "map",
          "values": "string"
        }
      ],
      "default": null
    },
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "row",
          "namespace": "",
          "fields": [
            {
              "name": "MOVIE_ID",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "TITLE",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "YEAR",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "BUDGET",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "GROSS",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "PLOT_SUMMARY",
              "type": [
                "null",
                "string"
              ],
              "default": null
            }
          ],
          "connect.name": "row"
        }
      ],
      "default": null
    },
    {
      "name": "after",
      "type": [
        "null",
        "row"
      ],
      "default": null
    }
  ],
  "connect.name": "ORCL.MOVIEDEMO.MOVIE"
}

**Comment by mtth** [comment]
`row` isn't found due to a namespacing issue. The outermost type is in the `ORCL.MOVIEDEMO` namespace so the unqualified type `row` in the `after` field gets resolved to `ORCL.MOVIEDEMO.row` which does not exist (`row` is defined with an explicit empty namespace). See [this section](https://avro.apache.org/docs/current/spec.html#names) of the specification for more information on enclosing namespaces.

To fix it, you can for example remove the explicit empty namespace for `row` or use an explicit but non-empty namespace for `row` (e.g. `ORCL.COMMON`) and use it in `after`'s definition (`ORCL.COMMON.row`).

**Comment by daffydee13** [comment]
Thank you very much for quick help !!! :)
