### ISSUE TITLE
Strings slower than ints/floats?

### ISSUE THREAD

**Issue by KyleAMathews** [mtth/avsc#332]
Just double-checking my work here. I've been testing avsc with hopes of speeding serialization speeds. I was surprised to see then that serialization was 2-3x slower than JSON.stringify!

I wrote a tiny test benchmark to investigate more and it seems that speedups mostly depend on data being number heavy & running it enough times to get v8 to fully compile avsc.

E.g. if I switch the test data from strings to ints/floats, it's ~3-5x faster than JSON.stringify but if the data is fully strings it's ~2x slower.

Just checking if this is what's expected?

Test script:

```js
const avro = require("avsc")
const _ = require(`lodash`)
const { performance } = require("perf_hooks")

const cheese = {
  pagePath: `hi`,
  publicDir: `what is the meaning of this???`,
}
const taskType = avro.Type.forValue([cheese])

console.log(taskType)

const numPages = 10000
const pages = []
_.range(numPages).map(page => {
  pages.push({ pagePath: page.toString(), publicDir: cheese.publicDir })
})

let start = 0
let end = 0

JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
JSON.stringify(pages)
start = performance.now()
JSON.stringify(pages)
end = performance.now()

console.log(`json`, end - start)
_.range(100).forEach(() => {
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
  taskType.toBuffer(pages)
})

start = performance.now()
taskType.toBuffer(pages)
end = performance.now()

console.log(`avro`, end - start)
```

**Comment by mtth** [comment]
Hi @KyleAMathews. The short answer is that `JSON.stringify` has an edge over `avsc` for string-heavy payloads but that `avsc` can still yield better overall system performance.

First, an important optimization when encoding large objects with `toBuffer` is to adjust the size of `avsc`'s internal working buffer via [`Type.__reset`](https://github.com/mtth/avsc/wiki/API#type__resetsize) (I should probably document this better...). The new size should be large enough to fit the largest object's encoding. If you already have a target `Buffer`, you can do even better by using [`encode`](https://github.com/mtth/avsc/wiki/API#typeencodeval-buf-pos) to avoid a copy.

The optimization above typically isn't enough to catch up to `JSON.stringify` for string-heavy payloads on encoding alone. However if the output ends up in a binary stream (for example written to a file, socket, ...), the `avsc` path will often be more performant overall. The main reason is that copying a `Buffer` into another is much (~5x) faster than a string. Additionally Avro encodings tend to be smaller, so there is less data to write.

To put a few numbers on it, here is what I get with the example above:

```js
const Benchmark = require('benchmark');

// Same setup as above...

avro.Type.__reset(2 ** 20); // 1MiB working buffer

new Benchmark.Suite()
  .add('json', () => { JSON.stringify(pages); })
  .add('json into buffer', () => { Buffer.from(JSON.stringify(pages), 'utf8'); })
  .add('avro', () => { taskType.toBuffer(pages); })
  .on('cycle', function (evt) { console.log(String(evt.target)); })
  .run({'async': true });

// Results (i3 MacBook air 2020):
//
// json x 473 ops/sec ±5.41% (78 runs sampled)
// json into buffer x 277 ops/sec ±2.76% (81 runs sampled)
// avro x 402 ops/sec ±2.93% (83 runs sampled)
```

**Comment by KyleAMathews** [comment]
Super helpful! Didn't know that strings were so much more expensive to copy to binary streams (my data is headed to http) so that helps actually explain why my tests were showing the system was faster despite the actual serialization being slower 😆
