### ISSUE TITLE
[Question] Is it possible to generate the avro schema from json schema using this lib?

### ISSUE THREAD

**Issue by ali-habibzadeh** [mtth/avsc#333]
I have a need to create avro schema from TypeScript types I have. I am not sure it's possible to use this lib for direct generation of the ts types into avro but can I utilise json schema for this purpose?

**Comment by mtth** [comment]
Hi @ali-habibzadeh. Not with `avsc` directly but you might still be able to find a library for this. It looks like there are a few Avro-JSON Schema (and TypeScript) related ones on NPM.
