### ISSUE TITLE
Parses schema with union of multiple numeric types but errors on serialization

### ISSUE THREAD

**Issue by andrewfulrich** [mtth/avsc#334]
Calling `forSchema` on a union type containing multiple numeric types (e.g. `["int","float"]`, `["double","long"]`, ["int","double"], etc.) will not error, but when I then call `toBufffer` on data using that schema, it errors on that union type. Here's an example:
```javascript
//schema
{
  "type": "map",
"values":["null","string","int","float"]
}
//sample data:
{  ";": -49461080.48250526,  "O": -519158442,  "Q": 54545911.311820686,  "*": -11196558.100517735,  "?": null}
or
{  "5": "occaecat consectetur dolor laboris cupidatat",  "O": -28919846.308708936,  "&": 1170840610,  ">": null,  "\\": null}
```
results with error:
```
index.html:46 Error: invalid ["null","string","int","float"]: "occaecat consectetur dolor laboris cupidatat"
    at throwInvalidError (avsc.js:8422)
    at WrappedUnionType._write (avsc.js:6933)
    at MapType._write (avsc.js:7291)
    at MapType.Type.toBuffer (avsc.js:6083)
```

**Comment by mtth** [comment]
Hi @andrewfulrich. This is expected: unions containing multiple numerical types are _ambiguous_ and expect wrapped values to correctly infer their type. For example:

```js
const type = avro.Type.forSchema(['float', 'int']);
type.isValid(123); // false - we would not know whether to encode it as a float or int.
type.isValid({int: 123}); // true
type.isValid({float: 123}); // true
```

The [`UnwrappedUnionType` documentation](https://github.com/mtth/avsc/wiki/API#class-unwrappeduniontypeschema-opts) has more information on which unions are ambiguous and their representation. You can also override this behavior via custom logical types, see [this comment](https://github.com/mtth/avsc/issues/129#issuecomment-329944723) for an example.

**Comment by andrewfulrich** [comment]
I see, thanks very much for the information!

**Comment by andrewfulrich** [comment]
Probably shouldn't have passed the parsing phase in that case, but I suppose that's not a huge deal.

**Comment by mtth** [comment]
Happy to help. W.r.t. your second comment: you can set `wrapUnions` to `false` to have it fail at schema parsing time on ambiguous unions.

```js
Type.forSchema(['int', 'float'], {wrapUnions: false}); // Throws ambiguous unwrapped union: ["int","float"]
```

**Comment by eurostar-fennec-cooper** [comment]
I just ran into this as well and it was a pain to figure out. Perhaps the error could be updated to be a little clearer and point out the ambiguity.

Is it not possible to just parse a numeric value into the smallest (byte-wise) supporting type?
