### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Falci** [mtth/avsc#335]
Hi,

I'm trying to use this lib in a React app, on client side, to validate a schema.
I'm trying to import it like:

```
import avro from 'avsc/etc/browser/avsc-types';
```

The problem is that file depends on `util` and `Buffer`, which are available for NodeJS but not for the browser.

I'm using webpack in the version 5 and it doesn't include NodeJS polyfill.

How can I import and validate a schema in the client side?

**Comment by mtth** [comment]
Hi @Falci. I haven't used webpack in a long time so I can't be sure but it looks like you now have to opt-in to the polyfills. See [this related issue](https://github.com/isaacs/core-util-is/issues/27#issuecomment-652181111) for an example and link to the relevant docs.

**Comment by pitamer** [comment]
Hi @Falci, hi @mtth 😄

If there's any update on the matter or a known way to fix this, I'd be happy to know! Thanks :)
