### ISSUE TITLE
"error" record type for typescript

### ISSUE THREAD

**Issue by ivank** [mtth/avsc#339]
Seems like the typescript types do not have "error" record type, though avsc itself supports it.

I've recently encountered this in one of my libs that uses AVSC. https://github.com/ovotech/castle/issues/71 

Fudging the types worked form me, but it might be better to fix it here properly.

The problem was seen when working with this Avro:

```
{
  "type" : "error",
  "name" : "EpicFailure",
  "namespace" : "namespace",
  "fields" : [ {
    "name" : "code",
    "type" : {
      "type" : "enum",
      "name" : "ErrorCode",
      "symbols" : [ "ERROR" ]
    }
  }, {
    "name" : "message",
    "type" : "string"
  } ]
}
```

**Comment by mtth** [comment]
Thanks for reporting - fixed in https://github.com/mtth/avsc/commit/5ffe9c374fd96aac84948cfe7330e1acaa69d511 and released in `5.6.0`. Please reopen if this doesn't address your use-case.
