### ISSUE TITLE
Error when using `type.compareBuffers` with fields with multiple types

### ISSUE THREAD

**Issue by mario128mex** [mtth/avsc#341]
Hi, I have the following schema: 
```javascript
const campaign = {
  type: 'record',
  name: 'Campaign',
  fields: [
    {name: 'Id', type: 'int'},
    {name: 'Name', type: 'string'},
    {name: 'AdvertiserId', type: 'int'},
    {name: 'IsActive', type: 'boolean'},
    {name: 'IsDeleted', type: 'boolean'},
    {name: 'EndDateISO', type: ['null', 'string'], default: null},
    {name: 'Price', type: 'int'},
    {name: 'IsArchived', type: 'boolean'},
    {name: 'StartDate', type: 'string'},
    {name: 'CustomFieldsJson', type: ['null', 'string'], default: null},
    {name: 'StartDateISO', type: 'string'},
    {name: 'EndDate', type: ['null', 'string'], default: null},
  ],
}
```

I'm writing some tests where, I check that the Avro data buffer sent to the cloud server is the one that I expect, in order to do so, I use `type.compareBuffers`, but my tests threw the following error: 
`TypeError: Cannot read property '_match' of undefined`
This error started to happen after I made some fields optional in my Avro schema, and after I did some debugging, I found out that the `RecordType.prototype._match` doesn't know what to do with fields with multiple types (see image attached)

can you guys help me out?

![Screen Shot 2021-03-28 at 3 39 34 p m  (2)](https://user-images.githubusercontent.com/6043102/112769253-4c904600-8fdd-11eb-9d7f-b3a425c3788e.png)

**Comment by mtth** [comment]
Can you share a test case reproducing the error?

**Comment by mario128mex** [comment]
sorry about the late reply, I just got a chance to get back to this, here it is 

```javascript
const { streams, Type } = require('avsc')

const Person = {
  type: 'record',
  name: 'Person',
  fields: [
    // first line works, second doesn't
    // { name: 'Name', type: 'string' },
    { name: 'Name', type: ['null', 'string'], default: null },
  ]
}

const getBuffer = (data, schema) =>
  new Promise((resolve, reject) => {
    const dataChunks = []

    const encoder = new streams.BlockEncoder(schema)
      .on('data', buf => dataChunks.push(buf))
      .on('error', reject)
      .on('end', () => resolve(Buffer.concat(dataChunks)))

    data.forEach(item => encoder.write(item))
    encoder.end()
  })

const run = async () => {
  const person1 = {Name: 'John'}
  const person2 = {Name: 'Adam'}

  const buffer1 = await getBuffer([person1], Person)
  const buffer2 = await getBuffer([person2], Person)

  const comparison = Type.forSchema(Person).compareBuffers(buffer1, buffer2)

  console.log('expected value of comparison: 0, actual value: ', comparison);
}

run()
```

**Comment by mtth** [comment]
Thanks for the snippet @mario128mex. Looking at the code, the error is expected here: `type.compareBuffers` accepts only valid encodings of the matching type (in particular not object container files as produced by `BlockEncoder`).

For example, here is how you would use it with your example's data:

```js
const type = Type.forSchema(Person);
const buf1 = type.toBuffer(person1);
const buf2 = type.toBuffer(person2);
const result = type.compareBuffers(buf1, buf2);
```

Behavior when passing in different buffers is undefined. I do think it would be worth providing a nicer error message when decoding fails though - I'll try to release a new version with this soon.

**Comment by mario128mex** [comment]
I see, yeah please add a message to let this clearer, cause I had a hard time trying to figure out the issue, also, will these lines work with an array of data? something like
```javascript
type.toBuffer([person1])
type.toBuffer([person2])
```

because, if I remember correctly, `toBuffer` doesn't work with an array
btw, thanks for the explanation 👍

**Comment by mtth** [comment]
> also, will these lines work with an array of data? something like
> 
> ```js
> type.toBuffer([person1])
> type.toBuffer([person2])
> ```
> 
> because, if I remember correctly, `toBuffer` doesn't work with an array

`type.toBuffer` accepts any value valid for `type`. To pass in an array of `Person`s, use an `'array'` type:

```js
const arrayType = avro.Type.forSchema({type: 'array', items: Person});
const buf = arrayType.toBuffer([person1]); // OK.
```

**Comment by mario128mex** [comment]
thanks for the explanation, this should do the trick next time I need to use and compare buffers
