### ISSUE TITLE
throw in logical type is swallowed and logical type is skipped

### ISSUE THREAD

**Issue by dhoepelman** [mtth/avsc#343]
Take the following code:

```javascript
class Fail extends avsc.types.LogicalType {
  constructor(schema, opts) {
    super(schema, opts)
    throw Error('fail')
  } 
}

const type = Type.forSchema({
    name": "Record",
    type: "record",
    logicalType: "fail",
    fields: []
  }, {
  logicalTypes: { fail: Fail },
});

const serialized = type.toBuffer({})
const deserialized = type.fromBuffer(serialized)
```

current behavior: avsc (de)serialized the avro type as if the logical type doesn't exist
expected behavior: type construction or (de)serialization fails with the thrown error

avsc version 5.6.2

**Comment by mtth** [comment]
Hi @dhoepelman. The Avro spec mandates that invalid logical types be ignored ([reference](https://avro.apache.org/docs/current/spec.html#Logical+Types)) and `avsc` implements this behavior by default. You can however set [`Type.forSchema`](https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts)'s `assertLogicalTypes` option to detect these when constructing the type.
