### ISSUE TITLE
Union of Enum and String types throws an error

### ISSUE THREAD

**Issue by damion-add-on-depot** [mtth/avsc#345]
I created an avro schema with an enumerated type, but in some cases, JSON data for the property associated with the type is set as an empty string. I figured I could work around that by creating a union as follows:

```json
{
    "type":[
        {
            "type": "enum",
            "name": "WeekDay",
            "symbols": ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
        },
        "string"
    ],
    "name": "weekday"
}
``` 

But I got the following error when parsing the source data, where the `weekday` property was set to an empty string:

```
Error: invalid [{"name":"WeekDay","type":"enum","symbols":["sunday","monday","tuesday","wednesday","thursday","friday","saturday"]},"string"]: ""
```

Is that the intended behavior? 

I read the Avro spec and it appears that it should be possible to create a union of types `enum` and `string`.

**Comment by damion-add-on-depot** [comment]
I also tried adding an empty string to the list of symbols. But got the following error:
```
Error: invalid "Week" symbol: ""
(anonymous)	@ dependencies/Avro.gs:16952
EnumType	@ dependencies/Avro.gs:16950
(anonymous)	@ dependencies/Avro.gs:15765
Type.forSchema	@ dependencies/Avro.gs:15766
(anonymous)	@ dependencies/Avro.gs:15752
Type.forSchema	@ dependencies/Avro.gs:15751
Field	@ dependencies/Avro.gs:17957
(anonymous)	@ dependencies/Avro.gs:17361
RecordType	@ dependencies/Avro.gs:17360
(anonymous)	@ dependencies/Avro.gs:15765
```

The error stems from the failure to validate against the following regular expression:
```javascript
var NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;
```
I'm tempted to modify it to also match empty strings. Do you think that's a viable solution?

**Comment by damion-add-on-depot** [comment]
Did some debugging and narrowed in on the following function:

```javascript
WrappedUnionType.prototype._write = function (tap, val) {
    var index, keys, name;
    if (val === null) {
        index = this._branchIndices["null"];
        if (index === undefined) {
            throwInvalidError(val, this)
        }
        tap.writeLong(index)
    } else {
        keys = Object.keys(val);
        if (keys.length === 1) {
            name = keys[0];
            index = this._branchIndices[name]
        }
        if (index === undefined) {
            throwInvalidError(val, this)
        }
        tap.writeLong(index);
        this.types[index]._write(tap, val[name])
    }
};
```

This function/method throws an error for unions with `enum` and `string` types.

**Comment by damion-add-on-depot** [comment]
Came up with a workaround.

I abandoned trying to get a union of types `enum` and `string` to work and focused on making empty strings a valid symbol for enums. 

Updated the **`lib/util.js`** module with the following changes:
```javascript
// add a new regex pattern specific to enum symbols that matches names and the empty string
var SYMBOL_PATTERN = /^$|^[A-Za-z_][A-Za-z0-9_]*$/;
.
.
.
// add a new function to validate symbol names
/** Check whether a string is a valid Avro enum symbol identifier.
function isValidSymbol(str) { return SYMBOL_PATTERN.test(str); }
.
.
.
module.exports = {
   .
   .
   .
   isValidSymbol: isValidSymbol
   .
   .
   .
};
```

And finally, update the **`lib/types.js`** module to use `isValidSymbol` function for the `EnumType` class as follows:
```javascript
function EnumType(schema, opts) {
    Type.call(this, schema, opts);
    if (!Array.isArray(schema.symbols) || !schema.symbols.length) {
        throw new Error(f("invalid enum symbols: %j", schema.symbols))
    }
    this.symbols = Object.freeze(schema.symbols.slice());
    this._indices = {};
    this.symbols.forEach(function (symbol, i) {
        if (!utils.isValidSymbol(symbol)) {
            throw new Error(f("invalid %s symbol: %j", this, symbol))
        }
        if (this._indices[symbol] !== undefined) {
            throw new Error(f("duplicate %s symbol: %j", this, symbol))
        }
        this._indices[symbol] = i
    }, this);
    this._branchConstructor = this._createBranchConstructor();
    Object.freeze(this)
}
```

Again, this is a hack but it will suffice until the issue with the union of `enum` and `string` types is resolved.

**Comment by mtth** [comment]
Unions with `string` and `enum` types need to be [wrapped](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts) to ensure that they don't lose branch information. This is necessary as the default unwrapped representation is identical for both types.

Here are examples of valid values for the union above:

```js
const str = {string: ''}; // Empty string.
const day = {WeekDay: 'monday'}; // Enum value.
```

Take a look at [this comment](https://github.com/mtth/avsc/issues/129#issuecomment-329944723) for more context as well as a couple examples.

**Comment by damion-add-on-depot** [comment]
Thank you for the solutions! The explanation about logical types from the comment you referenced should really come in handy for more complex types.
