### ISSUE TITLE
invalid magic bytes issue

### ISSUE THREAD

**Issue by hanhpham327** [mtth/avsc#346]
Currently I am streaming avro file from s3.
my function takes in a stream - which is `data`, 
Example of `data`<Buffer 4f 62 6a 01 04 14 61 76 72 6f 2e 63 6f 64 65 63 08 6e 75 6c 6c 16 61 76 72 6f 2e 73 63 68 65 6d 61 ec 06 7b 22 74 79 70 65 22 3a 22 72 65 63 6f 72 64 ... 14624 more bytes>

The issue I am running into is Error: invalid magic bytes
Thank you for all your time creating this library.  
```
return transform(data => {
        const decodeMessage = buffer => {
          return new Promise((resolve, reject) => {
            let result;
            const blockDecoder2 = new avro.streams.BlockDecoder(
                {
                  parseHook: (schema) => {
                    console.log(schema)
                    console.log('the avro file schema')
                    return avro.Type.forSchema(schema, {wrapUnions: true})
                  }
                }
            ); // The streaming decoder.

            blockDecoder2.on("data", val => {
              // console.log(val)
              result = val;
              console.log(result)
            });
            blockDecoder2.on("error", err => {
              reject(err)
              console.log(err)
            });
            blockDecoder2.on("end", () => {
              resolve(result)
              console.log(result)
            });
            blockDecoder2.end(buffer);
          })
        };

        async function startSingleTest() {
          const message = await decodeMessage(data) 
         
        }

        startSingleTest();
      })
```
I am able to get the output below

> <Buffer 4f 62 6a 01 04 14 61 76 72 6f 2e 63 6f 64 65 63 08 6e 75 6c 6c 16 61 76 72 6f 2e 73 63 68 65 6d 61 ec 06 7b 22 74 79 70 65 22 3a 22 72 65 63 6f 72 64 ... 3941 more bytes>
> {
>   type: 'record',
>   name: 'EventData',
>   namespace: 'Microsoft.ServiceBus.Messaging',
>   fields: [
>     { name: 'SequenceNumber', type: 'long' },
>     { name: 'Offset', type: 'string' },
>     { name: 'EnqueuedTimeUtc', type: 'string' },
>     { name: 'SystemProperties', type: [Object] },
>     { name: 'Properties', type: [Object] },
>     { name: 'Body', type: [Array] }
>   ]
> }
> the avro file schema

> Error: invalid magic bytes
>     at BlockDecoder._decodeHeader (.../containers.js:174:24)
>     at BlockDecoder._write (.../avsc/lib/containers.js:219:13)
>     at doWrite (_stream_writable.js:441:12)
>     at writeOrBuffer (_stream_writable.js:425:5)
>     at BlockDecoder.Writable.write (_stream_writable.js:316:11)
>     at BlockDecoder.Writable.end (_stream_writable.js:623:10)
>     at .../avsc/file_processor/avro_file_processor.js:116:27
>     at new Promise (<anonymous>)
>     at decodeMessage (.../avsc/file_processor/avro_file_processor.js:91:18)
>     at startSingleTest (.../avscsrc/file_processor/avro_file_processor.js:121:33)
>     at Transformer.handler (.../avsc/file_processor/avro_file_processor.js:125:9)
>     at Transformer._transform (.../avscngest-engine/node_modules/stream-transform/lib/index.js:141:39)
>     at Transformer.Transform._read (_stream_transform.js:191:10)
>     at Transformer.Transform._write (_stream_transform.js:179:12)
>     at doWrite (_stream_writable.js:441:12)
>     at writeOrBuffer (_stream_writable.js:425:5)
>     at Transformer.Writable.write (_stream_writable.js:316:11)
>     at Gunzip.ondata (_stream_readable.js:714:22)
>     at Gunzip.emit (events.js:311:20)
>     at Gunzip.EventEmitter.emit (domain.js:482:12)
>     at addChunk (_stream_readable.js:294:12)
>     at readableAddChunk (_stream_readable.js:275:11)
>     at Gunzip.Readable.push (_stream_readable.js:209:10)
>     at Gunzip.Transform.push (_stream_transform.js:152:32)
>     at Zlib.processCallback (zlib.js:531:10)
> undefined

**Comment by hanhpham327** [comment]
I've seen other answers where you would do a .toString('hex') on the buffer and it would work. However when I do try that it still returns invalid magic bytes. It also doesn't print out the avro schema
```
return transform(data => {

        // This sample transformation selects out fields
        // that will make it through to the output.  Simply
        // list the field names in the array above.
        let dataFields = Object.keys(data);
        return reductionFields.map(fm => {
          let inputFields = _.get(fm, 'inputFieldNames', {});
          let outputField = _.get(fm, 'outputFieldName');
          let matchingInputFields = _.intersection(inputFields, dataFields);

          if (matchingInputFields.length > 0) {
            let value = data[matchingInputFields[0]];

            // hash value
            let hashFieldConf = _.get(hashConfig, [outputField]);
            if (hashFieldConf) {
              let hashedValue = this.hash.call(this, value, hashFieldConf);
              if (hashedValue) {
                return hashedValue;
              }
              return value;
            }
            return value;
          } else {
            // throw an error - couldn't find a mapping for that field
            throw new IngestProcessorError(`Couldn't find mapping for input field mapping '${inputFields}'.`, true);
          }
        }, this);
      });
    } else if (hashConfig) {

      let hashedValue;
      let hashFields = Object.keys(hashConfig);
// is it snappy gzip? -> can athena do snappy gzip?
//  note besides modifiying in place, have to think about the output of the file
      return transform(data => {
        console.log(data)
        const decodeMessage = buffer => {
          return new Promise((resolve, reject) => {
            let result;
            const blockDecoder2 = new avro.streams.BlockDecoder(
                {
                  parseHook: (schema) => {
                    console.log(schema)
                    console.log('the avro file schema')
                    return avro.Type.forSchema(schema, {wrapUnions: true})
                  }
                }
            ); // The streaming decoder.

            blockDecoder2.on("data", val => {
              // console.log(val)
              result = val;
              console.log(result)
            });
            blockDecoder2.on("error", err => {
              reject(err)
              console.log(err)
            });
            blockDecoder2.on("end", () => {
              resolve(result)
              console.log(result)
            });
            blockDecoder2.end(buffer.toString('hex'));
          })
        };

        async function startSingleTest() {
          const message = await decodeMessage(data) // github documentation
          //
        }

        startSingleTest();
})
```

**Comment by mtth** [comment]
Hi @hanhpham327. Given the output of your example, I suspect each `data` element belongs to the same stream. For example decoding succeeds for the first chunk (the schema is printed out). Assuming `data` is a stream, try something like;

```js
data
  .pipe(new BlockDecoder())
  .on('data', (val) => { /* ... */ });
```

**Comment by hanhpham327** [comment]
@mtth thank you for your help. Will let you know if this solution suffice / will close out the ticket
