### ISSUE TITLE
Is is possible to write raw buffers using BlockEncoder

### ISSUE THREAD

**Issue by gambrose** [mtth/avsc#349]
I have an Avro file I would like to sort by a specific property.

I was hoping to be able to avoid fully decoding the items to do the sort.

I think I am able to read in the raw items by using the `noDecode` option of the `BlockDecoder` then use a resolver to just decode the property I need to sort with. The issue I am coming up against is that there doesn't seem to be a way to write raw buffers to an Avro object container file. The `BlockEncoder` does not seem to have an option to pass in the sorted raw buffers from `BlockDecoder`.

**Comment by mtth** [comment]
Hi @gambrose. You're right - there unfortunately isn't a `noDecode` equivalent for block encoders. That option would carry some risk as the block encoder would no longer guarantee that its blocks are valid. At this point, I don't think it would be worth the tradeoff and would instead recommend decoding the records fully. For most schemas the roundtrip will be cheap and negligible relative to other calls in the pipeline.

**Comment by gambrose** [comment]
Fair enough. Thanks for confirming that this is not possible.

BTW my main motivation for not fully deserialising the items was not to avoid the roundtrip cost but to avoid a large object graph in memory that would put more load on the GC.
