### ISSUE TITLE
Newlines

### ISSUE THREAD

**Issue by x10ba** [mtth/avsc#35]
Hi,
I am parsing an avroEncoded message and I am getting a bit of awkwardness in my result.
//result of decoded object
// issue being, "firstAVSC" is seemingly inserted in front of the object
// second issue, \n and whitespaces are seemingly inserted in front/ after each k:v
// even if I parse/trim the firstAVSC and secondAVSC of newlines and whitepaces in-line, I get the same result ("\n" and what I am calling the "firstAVSC" header Object)

// Getting this result
{"decodedMessage": "**firstAVSC** {**\n** stuff:1233455,**\n** someStuff:'example'"}}

// expecting this result
{"decodedMessage":{stuff:1233455,someStuff:'example'}}

Thanks,
x10ba

//using this script example
var avsc = require('avsc');
var secondAVSC = avsc.parse(
	{
"namespace": "x10ba",
"type": "record",
"name": "second",
"fields": [
{ "name": "someStuff", "type": [ "string", "null" ] },
]
},{registry:registry});

var firstAVSC = avsc.parse(
{
"namespace": "x10ba",
"type": "record",
"name": "first",
"fields": [
{ "name": "stuff", "type": [ "long", "null" ] },
{ "name": "moreStuff", "type": [
"x10ba.second", "null" ] }
]
},{registry:registry})

var message = avroEncodedString // this is what I am parsing
var object = {
	"decodedMessage": firstAVSC.fromBuffer(message)
}

console.log(object)

**Comment by mtth** [comment]
Hey, you should transform your output to a string before passing it to `console.log`, for example via: `console.log(JSON.stringify(object))`.

Related to https://github.com/mtth/avsc/issues/32, this is due to `console.log` behavior. Its output is meant to be "human friendly", so it decorates the objects returned (for example by adding the constructor's name in front) and indents it in a "hard-to-parse" way.

**Comment by x10ba** [comment]
Hi,
That makes sense, however, I get the same result if I insert the object into a DB (in this case mongo).

// I tried inserting both with and without the transform and get the same result.
{decodedMessage: '"firstAVSC {\\n ...}}

Hmmm. Probably not an AVSC issue?

Thanks for your help.
x10ba

**Comment by mtth** [comment]
I'm not familiar with Mongo, but yes - this appears to be an issue with how you insert the data. It looks like `util.inspect` is getting called on the object returned by `fromBuffer`.

**Comment by x10ba** [comment]
Hi.
Yep. 
Source code on the initial side had util.inspect as part of the string and was sending that across to me (I wasn't expecting it).
AVSC did exactly as it should and decoded what it received.
As always, nothing but praise for you and your module.
Thanks,
x10ba
