### ISSUE TITLE
BlockDecoder with Snappy codec doesn't work

### ISSUE THREAD

**Issue by altmax79** [mtth/avsc#352]
Hello,
I serialized an object in AVRO in bigtable (snappy compression). Then when I deserialize it the snappy codec, configured in BlockDecoder, doesn't decompress the value.

`const buffered = Buffer.from(value, 'utf-8');`
`const blockDecoder = new avro.streams.BlockDecoder({`
`codecs: {`
`             snappy: function (buf, cb) {`
`                 snappy.uncompress(compressed, function (err, original) {`
`                 console.log('uncompress original value is', original)`
`                 return original;`
`              });`
`          }}`         
`}).on("data", val => {`
`    console.log("value " + val) `
`}).on("error", err => {`
`   console.log("err" + err)`
`}).on("end", () => {`
 `   console.log("end ")`
`});`
`blockDecoder.push(buffered);`

**Comment by mtth** [comment]
Can you switch to `write` or `end` to write the data to the stream and try again? `push` is an internal function.
