### ISSUE TITLE
Annotation support on parsed schemas

### ISSUE THREAD

**Issue by Epokhe** [mtth/avsc#354]
Hey, thanks for creating this library!

I'm trying to parse a IDL schema with custom annotations. While the intermediate avsc includes them, the `Type` object does not.

I'm using custom annotations in my Avro schemas for internal business logic. Is there any way to access them, not from the raw avsc schema, but from the `Type` object?

https://runkit.com/epokhe/60c1e8db1ffa39001a3b5b84

```
Object
  myAnnotation: true
  type: "record"
  name: "Record1"
  fields: [Object {type: Object {myOtherAnnotation: ["a", "b"], type: "string"}, name: "field1"}]
```

```
RecordType
  _hash: Hash {str: undefined}
  name: "Record1"
  aliases: []
  doc: undefined
  _fieldsByName: Object {field1: Field {name: "field1", …}}
  fields: [Field {name: "field1", …}]
  _branchConstructor: function()
  _isError: false
  recordConstructor: function()
  _read: function()
  _skip: function()
  _write: function()
  _check: function()
  RecordType Prototype
```

**Comment by mtth** [comment]
Hi @Epokhe. You're correct, `Type` instances only expose standard Avro attributes and therefore don't include custom annotations. This also helps guarantee that types are immutable. I'd recommend keeping track of the schemas/annotations separately but if you'd like to combine them with the type you should be able to via a [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types).
