### ISSUE TITLE
[BUG] LogicalTypes not retained in encoded output. (AVSC version 5.6.3)

### ISSUE THREAD

**Issue by damion-add-on-depot** [mtth/avsc#356]
Below is an example to illustrate the issue. Basically I created a simple schema, with a logicalType for a date field as follows

```javascript
    const BlockEncoder = avro.streams.BlockEncoder;
    const SYNC = avro.Utils.bufferFrom('atokensyncheader');

    let type = avro.Type.forSchema({
        namespace: 'acme.industries',
        type: 'record',
        name: 'Product',
        fields: [
            {
                type: 'int', 
                name: 'id', 
                doc: 'Unique integer identifier of product.'
            },
            { 
                type: 'string', 
                name: 'name', 
                doc: 'Name of product.'
            },
            {
                type: 'string',
                name: 'description',
                doc: 'Description of product.'
            },
            {
                type:[
                    'null',
                    {
                        type: 'int',
                        logicalType: 'date'
                    }
                ],
                name: 'date_created',
                doc: 'Date of creation.',
                'default': null
            }
        ]
    });

   .
   .
   .
   // Note: date is measured in days since unix epoch
    encoder.write({
        id: 0,
        name: "HammerSpace",
        description: "Pocket reality where toons store over-sized mallets and other objects for various gags.",
        date:75390
    });

    encoder.write({
        id: 1,
        name: 'DoubleTake',
        description: 'Highly animated expression of shock.',
        date: 75392
    });

    encoder.end();
```

When I log the encoded bytes of the file as a string, the schema in the file header appears as follows(after some formatting):

```javascript
Objavro.schema�
{
    "name":"acme.industries.Product",
    "type":"record",
    "fields":[
        {
            "name":"id",
            "type":"int",
            "doc":"Unique integer identifier of product."
        },
        {
            "name":"name",
            "type":"string",
            "doc":"Name of product."
        },
        {
            "name":"description",
            "type":"string",
            "doc":"Description of product."
        },
        {
            "name":
            "date_created",
            "type": [
                "null",
                "int"
            ],
            "default":null,
            "doc":"Date of creation"
        }
    ]
}
avro.codecnull
```

You'll notice that the logicalType was stripped from the schema for the date field. I checked the documentation and wasn't able to find an option that would allow me to retain the original type definition (with logicalType) for the field.

Some applications can detect Logical Types if set in the header of an *.avro file so it would be great to have the option to retain them as is.

**Comment by mtth** [comment]
Hi @damion-add-on-depot. You have two options currently:

1. Pass in the schema directly as constructor argument to `BlockEncoder`. It will be included as-is in the header.
2. Use the logical type when parsing the type (by specifying a `date` key in the `logicalTypes` option). You can then also use the type's [`_export`](https://github.com/mtth/avsc/wiki/API#type_exportschema) function to control what is added to the header.

**Comment by damion-add-on-depot** [comment]
Thank you! The second option worked for me.

However, it would be great if this were the default behavior for the [standard logical types listed in the avro spec](https://avro.apache.org/docs/1.8.1/spec.html#Logical+Types). 

Any chance we'll see that implemented in a future version of this library?

**Comment by mtth** [comment]
Glad to hear it worked.

> Any chance we'll see that implemented in a future version of this library?

I think it's unlikely to make it into `avsc` to avoid too many logical type specifics in the core. I would favor a separate package of standard logical types which can be added if/when needed.

**Comment by Mouvedia** [comment]
This behaviour needs to be mentioned in the README.
This was highly unexpected.
