### ISSUE TITLE
assembleProtocolSchema exists in tests but not API

### ISSUE THREAD

**Issue by delaneyj** [mtth/avsc#357]
Was seeing how to load `.avdl` and saw `assembleProtocolSchema` however it doesn't match any exposed functions in the TS types.

**Comment by mtth** [comment]
You're looking for [`assembleProtocol`](https://github.com/mtth/avsc/wiki/API#assembleprotocolpath-opts-cb). `assembleProtocolSchema` are references from benchmarks with older versions of the API which I will delete shortly.
