### ISSUE TITLE
Pathing issue on nested directories

### ISSUE THREAD

**Issue by delaneyj** [mtth/avsc#358]
I have a deeper nested set of hundreds of avdl protocols that I'd like to parse (currently using avro-tool-1.10.2).

I have a file at
`a/foo.avdl`

that imports
"../b/bar.avdl";

and bar.avdl imports
"baz.avdl";

When I run `assembleProtocol` I get 
```
[ERROR] 06:33:47 Error: ENOENT: no such file or directory, open 'a/baz.avdl'
```

**Comment by mtth** [comment]
This was a bug - thank you for reporting. Fixed in `5.7.1`.
