### ISSUE TITLE
Add snappy codec

### ISSUE THREAD

**Issue by nucleardreamer** [mtth/avsc#36]
It would be extremely nice to have built into this library. Was there a conscious choice to leave out snappy and just have deflate?

**Comment by mtth** [comment]
It was, it's a pretty heavy dependency, only used by a small fraction of the code, and the faster ones are C++ addons (which don't run in the browser).

It's straightforward to use snappy compression using the existing `codec[s]` options though. For example, I think this would do the trick for `node-snappy`:

```javascript
// Decompression.
avro.createFileDecoder('data.avro', {codecs: {snappy: snappy.uncompress}});
// Compression.
avro.createFileEncoder('data.avro', {codecs: {snappy: snappy.compress}, codec: 'snappy'});
```

Let me know if this doesn't solve your use-case.

**Comment by nucleardreamer** [comment]
Oh! Yes it does. I didn't quite catch that in the `BlockDecoder` API writeup. Thank you!
