### ISSUE TITLE
Type equality don't guarantee same binary coding

### ISSUE THREAD

**Issue by ivan-klass** [mtth/avsc#362]
Given that `this` and `type` are valid `Type` instances, `this.equals(type)` only checks whether their fingerprints are equal.
https://github.com/mtth/avsc/blob/e16dbf642c5999c7e5ab09c536d7310f6b7a1fde/lib/types.js#L574

while `fingerprint` is a hash of stringified `this.schema`:
https://github.com/mtth/avsc/blob/e16dbf642c5999c7e5ab09c536d7310f6b7a1fde/lib/types.js#L581-L582

Any `opts` seems to be ignored when comparing.

If I understand correctly, it means that `this.equals(type)` returning `true` does **not** guarantee the following: 
- `this.fromBuffer(buf)` equals to `type.fromBuffer(buf)`
- `this.toBuffer(val)` equals to `type.toBuffer(val)`

Did I get the problem right? If so, what could be a quicker workaround to get a more strict type-equality? Should we add a documentation note for `equals` or current `(i.e. have the same canonical schema).` is enough?
Thanks

**Comment by mtth** [comment]
You're right. The main causes for (de)serializations to differ even when the canonical schemas are identical are logical types and default values.

It's not very efficient but I think you can get the behavior you are looking for with the following snippet (assuming any logical types implement `_export`):

```js
function areStrictEqual(t1, t2) {
  return JSON.stringify(t1.schema({exportAttrs: true})) === JSON.stringify(t2.schema({exportAttrs: true}));
}
```

If you call it often, a simple optimization would be to first call (the much cheaper) `equals` followed by the check above.

Let me know if this works for you. I can consider adding it to `avsc`, for example via an option to `equals`.

**Comment by ivan-klass** [comment]
@mtth Thank you very much for the snippet!
I think an optional argument to equals would be great!
Does it mean a fingerprint for extras would be also maintained for optimization?
Appreciate your help!

**Comment by mtth** [comment]
Happy to help. I've added a `strict` option for this to `type.equals` in `5.7.2`. The implementation performs the optimization mentioned above but only keeps track of a single fingerprint to avoid adding unnecessary complexity.
