### ISSUE TITLE
Generated schema not compatible with bigquery avro upload

### ISSUE THREAD

**Issue by NavaBeginsky** [mtth/avsc#363]
I've been using the library to help on our move to big query but when I generate a schema using Type.forvalue, passing in an array of the items I need to convert and then write the converted data to a file and then upload to bigquery it puts all the items into one row. I've tested other avro schemas, not created through this library and it does upload normally and create a proper table in big query.
I think the problem is that when I pass in an array to create the schema, the top level of the schema is an array type, and then a record type before the actual items, as opposed to the top level just being a record type. I can't pass in only one item though to Type.forvalue because some of the items have undefined values in some of the columns.
Is there a way to remove the arraytype or somehow make the generated schema and records compatible with bigquery upload?

**Comment by mtth** [comment]
Can you pass in the items' type?

```js
const arrayType = Type.forValue([/* ... */]);
const recordType = arrayType.itemsType; // Use this one.
```

**Comment by NavaBeginsky** [comment]
When I try that I get errors when certain values are undefined, which is also what happened when I tried to pass only one item into forValue unfortunately. Is there some way to set it so that all fields can be undefined/nullable?

**Comment by mtth** [comment]
`forValue` will set a field to optional if at least one of the items in the array is missing it. If you're still getting an error, it likely means that the items you passed in do not cover all cases. This will happen in particular if you only pass one item.

> Is there some way to set it so that all fields can be undefined/nullable?

You could post-process the returned schema and force all fields to be optional.
