### ISSUE TITLE
Omit null values on decode

### ISSUE THREAD

**Issue by hpx7** [mtth/avsc#364]
I have the following schema:
```
const type = Type.forSchema({
  name: "PlayerAndVote",
  type: "record",
  fields: [
    { name: "player", type: "string" },
    { name: "vote", type: ["null", "int"], default: null },
  ],
});
```

This is what I get after encoding+decoding a sample object:
```
> type.fromBuffer(type.toBuffer({player: "Bob"}))
type { player: 'Bob', vote: null }
>
```

Is there some way I can reconstruct the same initial object I encoded, i.e. without the `vote` key? Setting the `default` to undefined doesn't work as that errors during encoding.

**Comment by mtth** [comment]
Standard decoded record values will always have all fields defined. You could get the behavior you want via a [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types), stripping fields equal to their default in `_fromValue`.
