### ISSUE TITLE
Intermittent issues for Invalid Union Index & Truncated Buffer while using same data.

### ISSUE THREAD

**Issue by ChristianTucker** [mtth/avsc#365]
Hello, I've just recently started using avsc/avro and I've run into an intermittent issue of sorts. I'm using Avro to serialize a large array of objects to be stored on disk (to be picked up by other processes) as it ended up being quite a bit faster than using inter-process communication or trying to manage my own SharedArrayBuffer. 

The array that we're serializing is an array containing cumulative data over the last hour. Once an item is added to the array, it's there for the next hour and for that hour is included in any serialization calls. `.toBuffer`

However, I have noticed that sometimes I am getting errors regarding `invalid union index` and `truncated buffer` which automatically corrects itself the next time that the file is written (even though it contains all of the same items to be encoded/serialized). Which tells me that it's not an issue with the data itself, but likely some form of corruption in the written output. 

The collection that we're serializing contains a `timestamp` field to let other processes know the last time it was updated as well as the `collection` which is the array of objects. I've applied a union to everything with null and provided default values after looking at several issues here. 

```js
export const ETHTransactionsSchema = avro.Type.forSchema({
    name: 'ETHTransactionsCollection',
    type: 'record',
    fields: [
        { name: 'timestamp', type: 'long', default: 0 },
        { 
            name: 'collection', 
            type: {
                type: 'array', 
                items: { 
                    name: "ETHTransaction", 
                    type: "record", 
                    fields: [
                        { name: 'hash', type: ['string', 'null'], default: "" }, 
                        { name: 'insertedAt', type: ['long', 'null'], default: 0 }, 
                        { name: 'timestamp', type: ['long', 'null'], default: -1 }, 
                        { name: 'gas', type: ['long', 'null'], default: 0  }, 
                        { name: 'gasPrice', type: ['long', 'null'], default: 0  }, 
                        { name: 'maxFeePerGas', type: ['long', 'null'], default: 0 },
                        { name: 'dropped', type: ['boolean', 'null'], default: false },
                        { name: 'processed', type: ['boolean', 'null'], default: false } 
                    ]
                } 
            } 
        }
    ]
})
```

Here's an exam,ple of the errors (with callstack). I call `decode` on an error to try to get more information. 

```
[ERROR][September 28th 2021, 5:08:49 am]: Error: truncated buffer
    at RecordType.Type.fromBuffer (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:601:11)
    at C:\Users\Tucker\...\cronjobs-refactor\dist\jobs\ETH\workers\medianFee.js:58:66
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
[INFO][September 28th 2021, 5:08:49 am]: Decoded information for error: { value: undefined, offset: -1 }
```

```
[ERROR][September 28th 2021, 5:07:40 am]: Error: invalid union index: -6083
    at UnwrappedUnionType._read (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:1316:11)
    at RecordType.readETHTransaction [as _read] (eval at RecordType._createReader (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:1:1), <anonymous>:6:8)
    at ArrayType._read (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:1980:24)
    at RecordType.readETHTransactionsCollection [as _read] (eval at RecordType._createReader (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:1:1), <anonymous>:6:8)
    at readValue (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:2900:17)
    at RecordType.Type.fromBuffer (C:\Users\Tucker\...\cronjobs-refactor\node_modules\avsc\lib\types.js:599:13)
    at C:\Users\Tucker\...\cronjobs-refactor\dist\jobs\ETH\workers\medianFee.js:58:66
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
[INFO][September 28th 2021, 5:07:40 am]: Schema could not be decoded.
```

Both clients are using avsc, here is how I am writing the file...

```js
_writeTask = async (): Promise<void> => {
    if(!this._drityFlag) return;
    this._drityFlag = false; 

    const collection = Object.values(this._items)
    const contents = this._schema.toBuffer({ timestamp: Date.now(), collection });
    fs.writeFileSync(this._filePath, contents);  // Use sync here to hang eventloop on master. 
}
```

And here is how the file is being read...

```js
 fs.readFile(dataPath, (err: NodeJS.ErrnoException, data: Buffer) => {
    if(err) return reject(err); 

    try {
         // Use avsc to parse the schema.
         let parsed = ETHTransactionsSchema.fromBuffer(data); 
         ...
     } catch(...) { ... }
});
```

The buffer is written to disk on average about 10 times per second, while it's read from disk about once per second. 

I should add that I've verified that all data is correct and have run it through methods to check the data before sending it off to the schema before, all of the data comes from our MongoDB database with $project and default values.

**Comment by mtth** [comment]
Sorry for the delayed response. Is the data written and read from the same Node process? If not, I suspect that's the cause of the issue. I don't think`fs.writeFileSync` is always atomic.

**Comment by ChristianTucker** [comment]
@mtth It is not, the data is accessed by multiple slaves and written by the master. I'll look into solutions regarding `fs.writeFileSync` and if you have any ideas on how to best approach, please let me know.

**Comment by mtth** [comment]
Off the top of my head, you could try using something like [this package](https://www.npmjs.com/package/write-file-atomic) (disclaimer: I haven't tried it) or a custom shared memory synchronization scheme.

**Comment by ChristianTucker** [comment]
@mtth Thanks I'll check it out, I'll be closing this since it's assumed to not be an issue related to the library.
