### ISSUE TITLE
Name is required to Type.forSchema

### ISSUE THREAD

**Issue by OuthBack** [mtth/avsc#366]
Please update the example in the readme. Name is now required in Type.forSchema

![image](https://user-images.githubusercontent.com/65133825/135351194-6b52576d-58f8-4f31-a7d0-481bccabf2bc.png)
![image](https://user-images.githubusercontent.com/65133825/135351210-492f53be-9bce-49bf-a848-c7e07b5c099b.png)

**Comment by mtth** [comment]
Added to README. FYI the name is only required in the typings, not by the underlying function (see anonymous types in the doc).
