### ISSUE TITLE
reading file with optional int field fails

### ISSUE THREAD

**Issue by Laubeee** [mtth/avsc#368]
so I wrote a file ([test_voxels_out2.zip](https://github.com/mtth/avsc/files/7311130/test_voxels_out2.zip)) with python (fastavro) that I attached. Reading it with avsc fails with `avsc.min.js:1 Uncaught Error: invalid "int": null` - so basically it complains about the null values which are explicitly allowed in the schema.

The Schema is as follows:
```
{
  "name": "Voxels",
  "type": "array",
  "namespace": "com.viskar",
  "items": {
    "type": "array",
    "items": {
      "type": "array",
      "items": {
        "name": "_record",
        "type": "record",
        "fields": [
          { "name": "val", "type": "int" },
          { "name": "gwb", "type": ["int", "null"], "default": None },
          { "name": "gradient", "type": [{ "type": "array", "items": "float" }, "null"], "default": None }
        ]
      }
    }
  }
}
```
There are no actual null values for the "val" field and I can read the file again without issues with the python lib... I think it's a bug in avsc

**Comment by mtth** [comment]
This isn't an encoding issue: this schema is invalid. From the [spec](https://avro.apache.org/docs/current/spec.html#schema_record):

> Default values for union fields correspond to the first schema in the union.
