### ISSUE TITLE
Understanding type ambiguity

### ISSUE THREAD

**Issue by Laubeee** [mtth/avsc#369]
Hi! Thanks for providing this library.
I have some trouble understanding type ambiguity (and the subsequent need for wrapping)

Forcing unwrapped types I get an error:
```ambiguous unwrapped union: [{"name":"val_only","type":"record","fields":[{"name":"val","type":"int"}]},{"name":"val_gwb","type":"record","fields":[{"name":"val","type":"int"},{"name":"gwb","type":"int"}]},{"name":"val_gradient","type":"record","fields":[{"name":"val","type":"int"},{"name":"gradient","type":{"type":"array","items":"float"}}]},{"name":"all","type":"record","fields":[{"name":"val","type":"int"},{"name":"gwb","type":"int"},{"name":"gradient","type":{"type":"array","items":"float"}}]}]```

As you can see, there are 4 types defined:
1. "val_only": `[{"name":"val","type":"int"}]`
2. "val_gwb": `[{"name":"val","type":"int"},{"name":"gwb","type":"int"}]`
3. "val_gradient": `[{"name":"val","type":"int"},{"name":"gradient","type":{"type":"array","items":"float"}}]`
4. "all": `[{"name":"val","type":"int"},{"name":"gwb","type":"int"},{"name":"gradient","type":{"type":"array","items":"float"}}]`

I don't quite get how they're ambiguous. Examples for each of the types would be:
1. `{ val: 2 }`
2. `{ val: 2, gwb: 1 }`
3. `{ val: 2, gradient: [1,2,3] }`
4. `{ val: 2, gwb: 1, gradient: [1,2,3] }`

They are, I'd say "easily distinguishable", by the fields they contain. Moreover the Branch$ Class provides an "unwrap" function, which converts the whole thing to exactly the object I am looking for. Is there a way to directly store the unwrapped thing in the respective places?

The idea is to have optional types without having to store their values, as the vast majority of fields will only have the first value and it will save quite some memory not having tons of unnecessary empty references (talking about several million objects). Wrapping the whole thing kind of destroys the whole advantage of the idea..

**Comment by mtth** [comment]
Thanks for the detailed comment, this is one of the trickier parts of `avsc`. You're right, in this case the types are not ambiguous however `avsc` is not (yet?) smart enough to know that. Implementing an algorithm which _efficiently_ resolves ambiguities would add a lot of complexity to schema generation.

In most cases, you can also get the behavior you want via a logical type. [This comment](https://github.com/mtth/avsc/issues/129#issuecomment-329944723) has an example which disambiguates based on an enum field; you could do the same checking for field presence instead.

If you control the schema, a simpler alternative dcould be to make `gwb` and `gradient` both optional. All 4 examples above would then become valid and you could omit the outer union and bypass this ambiguity.
