### ISSUE TITLE
Alias name issue (need help)

### ISSUE THREAD

**Issue by mallikarjuna11421** [mtth/avsc#370]
Hi,
 When i am validating the object defined schema .isValid function alias names are not considering.

Example:
-------
AVSC schema
-----------
{
  "name": "Person",
  "type": "record",
  "fields": [
    {"name": "name", "type": "string"},
    {"name": "age", "type": ["null", "int"], "default": null},
    {
      "name": "gender",
      "type": {"name": "Gender", "type": "enum", "symbols": ["FEMALE", "MALE"]}
    },
    {
     "aliases": "address_line_1",
      "name": "address",
      "type": {
        "name": "Address",
        "type": "record",
        "fields": [{"name": "zipcode", "type": "int"}]
      }
    }
  ]
}

 working object
-----
const obj = { "name": "Abhi", "age": 20,"gender":"MALE", "address":{"zipcode":523300}};

here i am giving the same name address as per the given schema

failing object
-----------
const obj = { "name": "Abhi", "age": 20,"gender":"MALE", "address_line_1":{"zipcode":523300}};
sometimes i am getting instead of address the object is coming with alias name "address_line_1" at that time .isValid(obj) is failing.

Need help on this.

**Comment by mtth** [comment]
Hi @mallikarjuna11421. Aliases are only used with type resolution (`createResolver`) and not taken into account by `isValid`. See [the relevant spec section](https://avro.apache.org/docs/current/spec.html#Aliases).

**Comment by mallikarjuna11421** [comment]
> Hi @mallikarjuna11421. Aliases are only used with type resolution (`createResolver`) and not taken into account by `isValid`. See [the relevant spec section](https://avro.apache.org/docs/current/spec.html#Aliases).

Hi Thanks for reply.
Do you have any sample code for resolve this issue in javascript/node.js

**Comment by mallikarjuna11421** [comment]
Hi @mtth 
  Thanks for reply.
Do you have any sample code for resolve this issue in javascript/node.js.

**Comment by mallikarjuna11421** [comment]
Hi @mtth 

This is the code i am using for  Serialized object.
const avro = require('avsc')

var type = avro.parse({
    name: 'Pet',
    type: 'record',
    fields: [
      {name: 'kind', type: {name: 'Kind', type: 'enum', symbols: ['CAT', 'DOG'],aliases:["kind1"]}},
      {name: 'name', type: 'string'}
    ]
  });
  var pet = {kind1: 'CAT', name: 'Albert'}; // given object // given aliases name instead of name
  var buf = type.toBuffer(pet); // Serialized object.
  var obj = type.fromBuffer(buf); // expected output  {kind: 'CAT', name: 'Albert'}

**Comment by mallikarjuna11421** [comment]
Hi @mtth 

Do you have Avro functionality which validates the schema and **using name if name is mismatching** and it checks the aliases.
If it success returns the encoded value. 
If there is any error due to mismatch it gives me field name and error.
