### ISSUE TITLE
Aliases issue  ( Need Help)

### ISSUE THREAD

**Issue by mallikarjuna11421** [mtth/avsc#371]
Hi All,
We have a requirement on avro schema.
1.We are able to read the schema from avsc file and we are able to convert Buffer by using "toBuffer" method in avsc package;
 
 previous working Scenario
 -------------------
  Example : Schema 
  {
        "name": "email_addresses",
        "type": [
            {
                "items": "string",
                "type": "array"
            },
            "null"
        ],
		"aliases": [
            "emailaddresses"
        ]
    }
      
	
	Object
	===
let Object={email_addresses:"test@gmail.com"}

Code:
--------
const avro = require('avsc');
let avroSchemaKey=avro.Type.forSchema({
        "name": "email_addresses",
        "type": [
            {
                "items": "string",
                "type": "array"
            },
            "null"
        ],
		"aliases": [
            "emailaddresses"
        ]
    });

avroSchemaKey.toBuffer(Object); // working fine

we are able to convert Buffer if the schema name and object key name giving same,but now the new requirement came able to read the data if they give the key(emailaddresses) name with aliases name;

New Object:

 let object1 = {emailaddresses:"test@gmail.com"}

if i am getting the object with aliases name my code is failing

avroSchemaKey.toBuffer(object1 ); // getting error in this.

Tried multiple options but no luck.
Any thoughts or suggestions around this.

need help on this.

Thanks!

**Comment by JishantSingh** [comment]
You should probably be using old name in alias instead of new one. 
As mentioned in the [doc](http://avro.apache.org/docs/1.8.1/spec.html#Aliases),  

`Aliases function by re-writing the writer's schema using aliases from the reader's schema. For example, if the writer's schema was named "Foo" and the reader's schema is named "Bar" and has an alias of "Foo", then the implementation would act as though "Foo" were named "Bar" when reading.`

**Comment by mtth** [comment]
Hi. As I mentioned in [this comment](https://github.com/mtth/avsc/issues/370#issuecomment-974586430), aliases are only used during schema evolution. You'll need to implement your own logic to use them when also reading values directly. I'm not aware of any sample code for doing this.
