### ISSUE TITLE
Support generating avro schema from typescript type definitions

### ISSUE THREAD

**Issue by lewispham** [mtth/avsc#377]
As I can see from arvo schema then most of its type definitions can be reflected from typescript type definitions. Other libraries often use `reflect-metadata` or `ts-morph` for the task. I think `avsc` will be ways more useful if it supports similar stuffs.

**Comment by mtth** [comment]
Hi @lewispham. This sounds useful but out of scope for this repo. It'd also be cleaner to have this functionality separate from the core.
