### ISSUE TITLE
Schema type error when externalizing the schema from a .ts or .json file

### ISSUE THREAD

**Issue by jcjp** [mtth/avsc#392]
When using `Type.forSchema` I'm getting a type error. I have externalized my JSON schema and then import it when I need to use the `avsc`. Here is what I did:

```javascript
// schema.ts
export default { 
  "name": "temp",
  "type": "record",
  "fields": [
    {
      "name": "action",
      "type": "string"
    },
    {
      "name": "data",
      "type": {
        "name": "data",
        "type": "record",
        "fields": [
          {
            "name": "name",
            "type": "string",
            "default": "null"
          },
          {
            "name": "fullname",
            "type": "string",
            "default": "null"
          }
        ]
      }
    }
  ]
}
```

And use the `schema.ts` like this:

```typescript
import avro from 'avsc'
import schema from './schema'
// import schema from './schema.json' still doesn't work
// added the necessary imports on tsconfig for a JSON file
avro.Type.forSchema(schema)
```

This is the type error from TypeScript:
```typescript
Diagnostics:
Argument of type '{ name: string; type: string; fields: ({ name: string; type: string; } | { name: string; type: { name: string; type: string; fields: { name: string; type: string; }[]; }; })[]; }' is not assignable to parameter of type 'Schema'.
  Type '{ name: string; type: string; fields: ({ name: string; type: string; } | { name: string; type: { name: string; type: string; fields: { name: string; type: string; }[]; }; })[]; }' is not assignable to type 'FixedType & LogicalTypeExtension'.
    Property 'size' is missing in type '{ name: string; type: string; fields: ({ name: string; type: string; } | { name: string; type: { name: string; type: string; fields: { name: string; type: string; }[]; }; })[]; }' but required in type 'FixedType'.
```

I also tried transforming it to a JSON file but still producing the error above.

**Comment by TheTFo** [comment]
I'm also seeing this error.

**Comment by jcjp** [comment]
> I'm also seeing this error.

Have you tried adding `.default` on schema like this `avro.Type.forSchema(schema.default)`? But my guess it should work without `.default`.

**Comment by TheTFo** [comment]
I think I see how to workaround this, or it may just be the proper way to write an avro schema:

This code has the error:
```
avro.Type.forSchema({
  type: 'record',
  name: 'Pet',
  fields: [
    {
       name: 'kind',
       type: { type: 'enum', name: 'PetKind', symbols: ['CAT', 'DOG'] },
    },
    { name: 'id', type: 'string', logicalType: 'uuid' },
  ],
});
```
but this code seems to be fine:
```
avro.Type.forSchema({
  type: 'record',
  name: 'Pet',
  fields: [
    {
       name: 'kind',
       type: { type: 'enum', name: 'PetKind', symbols: ['CAT', 'DOG'] },
    },
    { name: 'id', type: { type: 'string', logicalType: 'uuid' } },
  ],
});
```

**Comment by jcjp** [comment]
> ```
> avro.Type.forSchema({
>   type: 'record',
>   name: 'Pet',
>   fields: [
>     {
>        name: 'kind',
>        type: { type: 'enum', name: 'PetKind', symbols: ['CAT', 'DOG'] },
>     },
>     { name: 'id', type: { type: 'string', logicalType: 'uuid' } },
>   ],
> });
> ```

Would it still work even if we just convert the `{ name: 'id', type: { type: 'string', logicalType: 'uuid' } },` to `{ name: 'id', type: { type: 'string' } },`

**Comment by mtth** [comment]
Looks like are a couple unrelated issues here.

W.r.t. the original issue, I suspect it's due to the `type` field being typed as `string` rather than the literal `'record'`. In TypeScript files, this is best solved by appending `as const`. I don't know if there is an equivalent option for JSON imports.

https://github.com/mtth/avsc/issues/392#issuecomment-1131731486 is different - the first example is indeed incorrect. Logical type attributes belong on type schemas, not fields'. The second example is right, as is @jcjp's later one. The [spec](https://avro.apache.org/docs/current/spec.html#schema_primitive) explains why:

> Primitive type names are also defined type names. Thus, for example, the schema "string" is equivalent to: {"type": "string"}

**Comment by jcjp** [comment]
> Looks like are a couple unrelated issues here.
> 
> W.r.t. the original issue, I suspect it's due to the `type` field being typed as `string` rather than the literal `'record'`. In TypeScript files, this is best solved by appending `as const`. I don't know if there is an equivalent option for JSON imports.

Thanks for the answer, my prime suspect was TypeScript so instead of `import` we use `require` unless we convert the literal types to `{"type": "string"}`.

Feel free to close this question.
