### ISSUE TITLE
Clear type data

### ISSUE THREAD

**Issue by sgavila** [mtth/avsc#394]
Hello friends,

I don't finish getting clone method to work removing metadata related to types in an avro. The opposite of https://stackoverflow.com/questions/33236284/how-to-convert-a-json-object-into-avro-object-if-avro-schema-contains-union-in-i

Use the method as follows.
let wrapFalse = type.clone(decoded, { wrapUnions: false });

However, the result is:

{id: {string:"whatever"}}.

I was hoping it was

{id: "whatever"}

Thank you.

**Comment by mtth** [comment]
`clone` always produces valid values for the underlying type. Depending on your union's schema, you might be able to get what you want by using another type with its `Type.forSchema`'s `wrapUnions` option to `false`.

```js
const schema = {
  type: 'record',
  name: 'Foo',
  fields: [
    {name: 'bar', type: ['string', 'int', 'null']},
  ],
};
const wrappedType = avro.Type.forSchema(schema, {wrapUnions: true});
const unwrappedType = avro.Type.forSchema(schema, {wrapUnions: false});

const wrapped = {bar: {string: 'hi'}};
const buf = wrappedType.toBuffer(wrapped);
const unwrapped = unwrappedType.fromBuffer(buf); // {bar: 'hi'}
```

If you get an ambiguous union error, you can also do it this way but will need to register an additional logical type to resolve the ambiguity.

**Comment by sgavila** [comment]
Good morning,

Thank you very much for the reply. As you predicted, it got an error in the "fromBuffer" method saying truncated buffer.

I have reviewed the documentation for logical types, and make use of the LongType provided by the npm "long" package.

However, I don't know what concrete logical type I should create on.

My schema is like this.

const schema = {
  type: 'record',
  name: 'Foo',
  fields: [
    {name: 'bar', type: ['string', 'null']},
  ],
};

In my case I already get the buffered message, so I don't need to generate it:

const unwrappedType = avro.Type.forSchema(schema, {wrapUnions: false});
const unwrapped = unwrappedType.fromBuffer(bufferReceived); 

Now im getting "truncated buffer error"

**Comment by mtth** [comment]
Truncated buffer errors mean that the buffer doesn't match the schema used to decode it. You should compare the schema you are using here with the one producing it. For example the order of the types in the unions need to match (there is also a slight problem in the one above - the default should be of the type of the first branch).
