### ISSUE TITLE
Block decoder with custom longs

### ISSUE THREAD

**Issue by Firetruck783** [mtth/avsc#395]
I don't see a way you can supply custom long handling when using "createBlobDecoder" to read from an Avro blob.
The examples all suggest passing in a custom registry, but I don't see a way of doing that in this case.

**Comment by mtth** [comment]
You can do it via `createBlobDecoder`'s `parseHook` option, for example:

```js
function parseHook(schema) {
  const registry = {/* ... */};
  return avro.Type.forSchema(schema, {registry});
}

const decoder = avro.createBlobDecoder(blob, {parseHook});
```
