### ISSUE TITLE
Possible to parse GenericRecords?

### ISSUE THREAD

**Issue by dberardo-com** [mtth/avsc#397]
Is it possible to parse records without knowing their schema upfront? i.e. as generic JSON object?

**Comment by mtth** [comment]
Yes - you can generate a `Type` for  JSON objects via [`Type.forValue`](https://github.com/mtth/avsc/wiki/API#typeforvalueval-opts).

**Comment by dberardo-com** [comment]
i will test it for my use case and give you a feedback here
