### ISSUE TITLE
Possible to fetch schema to Confluent schema registry?

### ISSUE THREAD

**Issue by dberardo-com** [mtth/avsc#398]
Can the Type object be initialized with a schema-registry url and name?

**Comment by mtth** [comment]
Integration with a schema registry is out of scope for this repo but you might be able to find another existing package to do so. Perhaps `@kafkajs/confluent-schema-registry` - I haven't used it but it looks applicable from [this page](https://kafkajs.github.io/confluent-schema-registry/docs/usage-with-kafkajs).
