### ISSUE TITLE
No releases or changelog? 

### ISSUE THREAD

**Issue by olivierlacan** [mtth/avsc#399]
Seems like Releases haven't been updated since 2019 despite many [new tagged versions](https://github.com/mtth/avsc/tags) since then, is there a place where you keep releases or a proper changelog? https://github.com/mtth/avsc/releases

You also seem to have the Releases page disabled on this repo for some reason despite linking to it from the README: 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/65950/176981858-0fb7622f-3667-4a8a-bd31-609109213c55.png">

Thanks.

**Comment by mtth** [comment]
No change log currently. I've stopped creating releases as they did not seem worth the overhead over git history with version tags. Thanks for pointing out the inconsistency in the README - it's now fixed.
