### ISSUE TITLE
 Invalid long value error for default value

### ISSUE THREAD

**Issue by harshinim** [mtth/avsc#406]
I have a backend that is returning a default value in the schema which is a very long integer. Custom long types has been implemented as per the below document

https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types

I still get " invalid "long": 32503679999999000" error.

**Comment by mtth** [comment]
Hi @harshinim. This error is `avsc` protecting you from potentially invalid deserialized JSON data. The built-in `JSON.parse` does not handle long integers:

```js
> JSON.parse('9007199254740995')
9007199254740996
```

To work around this you can use a custom JSON parser (for example [`json-bigint`](https://www.npmjs.com/package/json-bigint)) to parse the schema. The only requirement from `avsc`'s side is that the long type emitted by the parser be compatible with your custom long type.

**Comment by harshinim** [comment]
Thanks @mtth for getting back. 

Sorry for being a noob, but this error is thrown when calling Type.forSchema - not sure what you mean by using a custom parser. Is there an option to pass a custom parser to the library?
