### ISSUE TITLE
Can this be used for bytecode?

### ISSUE THREAD

**Issue by mattfysh** [mtth/avsc#407]
Hi there, I'm looking at generating bytecode for a toy language and searched for a while to find a binary packing/unpacking library written in JS but there are not that many great options.

So I started using avsc and it seems to be outputting what I need, e.g. I have a type `Instruction` which is a union type of all possible instruction set types.

Has Avro been used in this way before, and do you see any issues using it this way? My compiler and tooling is all written in javascript but the goal of producing bytecode is to write interpreters in other languages (e.g. Python) that can use Avro to decode the binary into a program structure and execute

**Comment by mtth** [comment]
Hi @mattfysh. I don't have any concrete examples to point to but this usage seems reasonable. Avro supports unions which are convenient for modeling ASTs (as you're doing for instructions). [Logical types](https://github.com/apache/avro/blob/master/lang/js/doc/Advanced-usage.md#logical-types) can be handy as well. If Avro supports all the languages you target, this sounds like a good fit.

**Comment by mattfysh** [comment]
Great, thanks @mtth. Let me know if you do happen to come across any other examples of Avro generating bytecode

The only two things I've stumbled on so far are:
- avoiding branches where possible, e.g. the constant space used to be an array of items with type `['string', 'boolean']` but this added an extra byte before each item because of the union, so now its just `'string'` and the bytecode is much smaller
- when decoding, the Python `DatumReader` doesn't wrap union types with the type name in the same way your library does, I had to subclass it and override the `read_union` method
