### ISSUE TITLE
Schema fails to parse

### ISSUE THREAD

**Issue by okdistribute** [mtth/avsc#409]
This is a valid schema for Java but fails in JS:

```
import avro, { Schema } from 'avsc'

let schema ={
    "type":"record",
    "name":"test",
    "namespace":"failed.sad.panda",
    "fields":[
       {
          "name":"msg_id",
          "type":[
             "null",
             {
                "type":"string",
                "avro.java.string":"String"
             }
          ],
          "default":""
       }
    ]
 }

 //@ts-ignore
avro.Type.forSchema(schema)
```

Errors at runtime:

```

Error: invalid "null": ""
    at throwInvalidError (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:3028:9)
    at NullType._check (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:809:5)
    at NullType.PrimitiveType._copy (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:794:8)
    at UnwrappedUnionType._copy (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:1395:21)
    at new Field (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:2829:20)
    at RecordType.<anonymous> (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:2126:17)
    at Array.map (<anonymous>)
    at new RecordType (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:2125:45)
    at /Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:223:14
    at Function.Type.forSchema (/Users/rae/dev/ditto/clients/royal-kafka-client/node_modules/avsc/lib/types.js:224:7)
```

**Comment by mtth** [comment]
Hi @okdistribute. This schema is invalid according to the [Avro spec](https://avro.apache.org/docs/1.10.2/spec.html#schema_record):

> Default values for union fields correspond to the first schema in the union. 

The first branch of the union is `"null"` here so the default should be `null`, not the empty string.

If you have control over the schema, the smallest change is to set the field's default to `null`. Depending on your use-case it might also be reasonable to skip the union and use the empty string to indicate absence. If you are reading the schema from an external source, you can use a type hook to patch it.

**Comment by mtth** [comment]
It appears so. In many cases default resolution (i.e. finding the branch a default belongs to) is unambiguous, even without the requirement above. The Java implementation might accept those as a convenience, or picks the first match in all cases, or perhaps some other disambiguation logic. We'd need to take a look at the code to confirm.

**Comment by okdistribute** [comment]
Unfortunately, I can't change the schema because the data coming from the producer are already using this schema to generate them. I get invalid union type: 7 when I change the schema.

**Comment by mtth** [comment]
Reordering/removing the union schema would need to be done throughout your systems (including in the producer). The alternative that only updates the default shouldn't however so would be a less invasive change.

In case it's useful, here's a minimal type hook which allows your schema to pass validation:

```js
function typeHook(schema) {
  if (schema?.type !== 'record') {
    // No need to patch non-records.
    return;
  }
  for (const field of schema.fields) {
    // Unless you're using schema evolution or explicitly referring to
    // the defaults in your code, it's safe to just strip the default.
    field.default = undefined;
  }
}

// Use it as follows:
const type = avro.Type.forSchema(schema, {typeHook, /* ... */})
```

**Comment by okdistribute** [comment]
That worked! Amazing support. Thank you so much.

**Comment by mtth** [comment]
Happy to help; glad that it works now.
