### ISSUE TITLE
float value is inaccurate after serializing and deserializing using avro schema

### ISSUE THREAD

**Issue by JyothsnaGoalla** [mtth/avsc#430]
Hello,

I have a avro schema which has some float values and i am using java code to send events and receiving using python consumer.
 For some reason float value serialization and deserialization is not working.
**Avro schema:-**
{
  "type": "record",
  "name": "Marks",
  "namespace": "com.Marks.sample",
  "fields": [
    {
      "name": "Name",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "Marks",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Marks",
          "fields": [
            {
              "name": "Maths",
              "type": "float"
            }
          ]
        }
      ],
      "default": null
    }
  ]
}

**Sample Data:-**
{"Name": "Avro",  "Marks": { "Maths": 20.0}}

Expected: {"Name": "Avro",  "Marks": { "Maths": 20.0}}
Actual:{"Name": "Avro",  "Marks": { "Maths": -1.8671875}}

please help me resolve this issue.

**Comment by mtth** [comment]
Hi @JyothsnaGoalla. It's hard to say without more context. You only mention Java and Python, how are you using `avsc`?
