### ISSUE TITLE
How to add custom attributes to serialised schema type eg. sqlType

### ISSUE THREAD

**Issue by buzzware** [mtth/avsc#431]
For avro files destined for BigQuery import, Google suggests defining the type as 

```
{"type": "string", "sqlType": "JSON"}
```
https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#extract_json_data_from_avro_data

This is very useful as it means avro files including JSON fields can be loaded straight into BigQuery using the schema in the file. While AVRO doesn't literally support json fields, strings in the file loaded into JSON type fields in the database is a decent compromise. 

However, avsc ignores the sqlType attribute.

How do I maintain that attribute when the buffer schema is written? Or how do I create a Type with additional attributes that will will be serialised ?

**Comment by buzzware** [comment]
I see a similar question in #307 but it seems to have been closed without an answer

**Comment by mtth** [comment]
Hi @buzzware. The best option with decorated schemas is typically to keep a copy alongside the generated type and reference it directly when the custom attributes are needed. However this doesn't work well with `BlockEncoder`s which expect a single schema or type argument currently. I think it would be worth extending the `BlockEncoder` API to better support this, for example via an additional `schema` option. In the meantime here are a couple workarounds:

1. If you don't need any type options when writing records, you can pass in the raw schema directly to the `BlockEncoder` which will then be written as-is.
2. If you do need type options, it's a bit trickier but you can use two encoders where the first will only write the header. Something like:

```javascript
async function pipedBlockEncoder(type, schema, writable) {
  const syncMarker = crypto.randomBytes(16);
  // Header-only encoder (note the schema argument)
  const prelude = new BlockEncoder(schema, {writeHeader: true, syncMarker});
  prelude.end();
  await pipeline(prelude, writable, {end: false}); // from node:stream/promises
  // Data encoder (we pass in the type here, not the schema)
  const content = new BlockEncoder(type, {writeHeader: false, syncMarker});
  content.pipe(writable);
  return content;
}
```

**Comment by buzzware** [comment]
Thanks @mtth, I just got it working for the first time with that.
