### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by samuelgja** [mtth/avsc#435]
### Motivation
Support for new bun runtime

### What's wrong
I'am using avsc in node, but starting digging into new [bun runtime](https://bun.sh/docs) and I tried to move some of my lib to bun, but avsc has error while using `fromBuffer` method.
error is:
```
1 | return function readTesJt(t) {
2 |   return new TesJt(
3 | 
4 |     t0._read(t)
       ^
TypeError: Expected string
```

Note this error is from `bun run test.js` script, not node.

I tried to dig into the lib itself and try to find the issue, but it's too big for me :D without knowing context. So maybe it can be easy fix, maybe not. Maybe it's issue with bun and not with avsc.

If it's issue with bun itself, please close.

### Code to reproduce
I found out it only happend on `string` type.

```js
const avro = require("avsc");

const object = {
  //   integer: 1,
  //   float: Math.PI,
  string: "Hello, world!",
  //   array: [10, 20, 30],
  //   map: { foo: "bar" },
  //   timestampExt: 12312312,
};

const type = avro.Type.forSchema({
  type: "record",
  name: "Test",
  fields: [
    // { name: "integer", type: "int" },
    // { name: "float", type: "float" },
    { name: "string", type: "string" },
    // { name: "array", type: { type: "array", items: "int" } },
    // { name: "map", type: { type: "map", values: "string" } },
    // {
    //   name: "timestampExt",
    //   type: { type: "long", logicalType: "int" },
    // },
  ],
});

const buf = type.toBuffer(object); 

const val = type.fromBuffer(buf); 
```

**Comment by joscha** [comment]
#410 might aid this

**Comment by mtth** [comment]
Do tests also run for `avsc` `5.x` on current `bun`? If so, closing SGTM. If not, let's close when `6.0` is released.

Adding official support will be best done separately if/when there is demand for it.

**Comment by joscha** [comment]
Yes 5.x (778f8daa057b39b9538ebaa04f7c382bd95482b2) passes well:

<img width="279" alt="Screenshot 2024-09-28 at 9 55 44 PM" src="https://github.com/user-attachments/assets/b0ed274e-4024-47c2-ac99-75718ab66a8f">

**Comment by mtth** [comment]
Great, thank you for confirming. Closing.
