### ISSUE TITLE
can schema support dynamic keys?

### ISSUE THREAD

**Issue by suguanYang** [mtth/avsc#443]
I have a data object like this:
```javascript
const person = {
    name: 'John',
    age: 30,
    address1: 'xxxx',
    address2: 'xxxx',
    address3: 'xxxx',
}
```
the question is how to support the fields `address${number}`  in schema definition?
```javascript
const type = avsc.Type.forSchema({
    name: 'PersonList',
    type: 'array',
    items: {
        name: 'Person',
        type: 'record',
        fields: [
            { name: 'name', type: 'string' },
            { name: 'age', type: 'int' },
        ]
    }
});

```

**Comment by mtth** [comment]
Hi @suguanYang. AFAIK Avro doesn't allow arbitrary keys in records so you'll need to use a [map](https://avro.apache.org/docs/1.11.1/specification/#maps). If possible, I'd recommend splitting the addresses into their own map so you can tighten the values' type.
