### ISSUE TITLE
StatefulEmitter handshake does not conform to spec

### ISSUE THREAD

**Issue by zeroaccord** [mtth/avsc#46]
StatefulEmitter's handshake request is not attached to a call. See https://avro.apache.org/docs/1.7.7/spec.html#Call+Format
"When the empty string is used as a message name a server should ignore the parameters and return an empty response. A client may use this to ping a server or to perform a handshake without sending a protocol message."

On the listener side on the Java implementation, you can see that the listener always looks for the request metadata and message name on every request: https://github.com/apache/avro/blob/master/lang/java/ipc/src/main/java/org/apache/avro/ipc/Responder.java#L124.

META_READER.read() will then throw an exception because there's no metadata in avsc's handshake request. This exception is caught and returned to the client as an error response. But this error response includes the handshake response as a prefix so everything looks fine from StatefulEmitter's side. The impact is simply noisy warnings on the Java listener's logs from the exception.

**Comment by mtth** [comment]
You're correct. That will be fixed in the upcoming `4.0` release (which will also include a built-in adapter compatible with Netty).

**Comment by mtth** [comment]
Fixed in [`4.0.0`](https://github.com/mtth/avsc/releases/tag/4.0.0), now released. The [`etc/integration`](https://github.com/mtth/avsc/tree/master/etc/integration) folder has sample working Java client and server implementations in case it's useful.
