### ISSUE TITLE
Missing default value in avro scheam

### ISSUE THREAD

**Issue by sahellebusch** [mtth/avsc#465]
I expect the following code to print the schema w/ a `default` value per the [avro spec](https://avro.apache.org/docs/1.4.0/spec.html). 

```ts
const userAvroSchema = Type.forSchema({
  type: 'record',
  name: 'User',
  fields: [
    { name: 'id', type: 'int' },
    { name: 'name', type: 'string' },
    { name: 'email', type: 'string' },
    { name: 'newValue', type: 'string', default: 'somevalue' },
    {
      name: 'registeredAt',
      type: { type: 'long', logicalType: 'timestamp-millis' },
    },
  ],
});

console.log(JSON.stringify(userAvroSchema.schema()));
```

Prints:
```
{"name":"User","type":"record","fields":[{"name":"id","type":"int"},{"name":"name","type":"string"},{"name":"email","type":"string"},{"name":"newValue","type":"string"},{"name":"registeredAt","type":"long"}]}
```

Is this something I'm doing wrong or is this a bug in the library?

**Comment by jonashellstrom** [comment]
Passing `{exportAttrs: true}` will include the defaults. 
Found a reference to it here: https://github.com/mtth/avsc/blob/master/etc/scripts/infer#L72

**Comment by mtth** [comment]
`schema` without any arguments returns the type's canonical schema, which doesn't include defaults.
