### ISSUE TITLE
Handling logical types

### ISSUE THREAD

**Issue by sujin-sam** [mtth/avsc#466]
I'm pretty much _unclear with documentation_ as I'm beginner for JS

I'm trying to serialize some of these logical types, I'm looking for proper examples to handle it

- timestamp-millis
Was able to handle with _new Date('2024-08-29T13:50:00.100Z').get time()_

How to handle below, can you pls share an example ?

- date
{"name": "createDate", "type": {"type": "int", "logicalType": "Date"}}

value to pass: 2024-08-29

- decimal
{"name”: "price", "type": ["null", {"type": "bytes", "precision": 21, "scale": 8, "logicalType": "decimal"}], "default": "null"}

value to pass: 450.00000001

I saw some notes on DecimalType but I couldn't understand how to implement

**Comment by mtth** [comment]
Have a look here for an end-to-end example and links to a few implementations: https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types
