### ISSUE TITLE
StatelessEmitter issue when serverHash != clientHash

### ISSUE THREAD

**Issue by Codonaut** [mtth/avsc#47]
Hey there.  First off thanks for writing this library, it is immensely useful.  In using it however I'm coming across an issue that seems difficult to address with the current implementation.  Pardon me if this is a bit wandering-- I'm still working to fully grok the avro handshake process, and want to make sure any errors in my reasoning are clear to you.

Using the `StatelessEmitter` you can emit an RPC request, which will contain the protocol hash and the message.  When the server(general avro server, not necessarily using `avsc`) receives the message it tries to retrieve a protocol from its cache using the hash.  If it does not find a protocol in its cache, then it sends back a handshake response with `match == 'NONE'` and its own protocol and hash.  Then, the client receives the server's protocol/hash and must use that to make a new request.  So, in this scenario there are two HTTP request/response cycles.

The problem is that `StatelessEmitter` is only set up for one request/response cycle.  It has a writable that it uses to send out its initial request, which it closes with a `.end()`(https://github.com/mtth/avsc/blob/master/lib/protocols.js#L460).  But, if there is a `match == 'NONE'` (https://github.com/mtth/avsc/blob/master/lib/protocols.js#L442) then the same writable stream is used again after `.end()` has been called, resulting in a `write after end` error.

It seems to me that the `StatelessEmitter` must somehow request a new writable object to send out a new request containing its full protocol, and not just a protocol hash.

If the hashes match then this is never an issue, because there is only a single request needed to get a proper response.

You can see in the python implementation what I mean as well-- if the requestor received a full response then it reads it, otherwise there was not an acceptable handshake match and a new request must be made: https://github.com/apache/avro/blob/master/lang/py/src/avro/ipc.py#L235

**Comment by mtth** [comment]
`StatelessEmitter`s actually do call the `writableFactory` again when the handshake fails (see [here](https://github.com/mtth/avsc/blob/master/lib/protocols.js#L419)). If you test against a Java server implementation, you should see the correct behavior.

Could you share the code you use to create the emitter? Which server implementation are you exchanging messages with? (The python implementation has a few issues you might also have to watch for, for example it doesn't support chunk-encoded requests.)

**Comment by Codonaut** [comment]
:facepalm: !!!

My `writableFactory` wasn't quite doing what it should-- it returns the same request object on every call, as you can see.  Moving the `http.request` creation into the `writableFactory` function fixed this... 
```
var req = http.request(self.reqOptions);
var messageEmitter = self.protocol.createEmitter(function(cb) {
  req.on('response', function(res, socket, head) {
    cb(res);
  });
  return req;
});
```

Thanks for the quick help here.  I'm glad that this was just a case of me not understanding things correctly, and didn't need any code changes.  Also, I'm actually hitting

**Comment by mtth** [comment]
You're very welcome, glad to hear it works.
