### ISSUE TITLE
`aliases` for fields is not used when serializing

### ISSUE THREAD

**Issue by joscha** [mtth/avsc#482]
```ts
const t = Type.forSchema({
  type: 'record',
  name: 'Person',
  fields: [
    {name: 'from', aliases: ['_from'], type: 'string'}
  ]
});
t.toBuffer({ _from: 'bla@foo.com' });
```
I expected the alias to be used when determining the value to write - do I need to create a resolver from the type on itself to make that work?

refs https://github.com/OpenAPITools/openapi-generator/pull/19721

**Comment by joscha** [comment]
I used a logical type to transform them:

```ts
export class EmailLogicalType extends Avro.types.LogicalType {
    static readonly NAME = "fixed-from-field";
  
    _fromValue(val: any) {
      return val;
    }
  
    _toValue(val: any) {
      if ("_from" in val) {
        val.from = val._from;
        delete val._from;
      }
      return val;
    }
    _resolve(type: any) {
      if (Avro.Type.isType(type, "string", `logical:${EmailLogicalType.NAME}`)) {
        return this._fromValue;
      }
    }
  }
```
is there a better way?

**Comment by mtth** [comment]
Using a logical type makes sense. You may be able to encapsulate this logic into a common `AliasableRecord` implementation, which processes aliases from the schema in its constructor and uses them in its `_toValue` implementation.

**Comment by joscha** [comment]
> which processes aliases from the schema in its constructor and uses them in its `_toValue` implementation.

I can't visualize that in my case - this works only if I have control of the input object, right? I don't control the model this is in, it comes from generated code from an OpenAPI schema: https://github.com/planet-a-ventures/affinity-node/blob/f20056ed510928d1745d248e6ec86ab4c29a2916/src/v2/generated/models/Email.ts#L33

**Comment by mtth** [comment]
You don't need control of the object. For example if you can determine from its schema that fields need to be aliased (say via a short list of reserved keywords checked against field names), you can dynamically add a logical type to do the aliasing via a type hook.

**Comment by joscha** [comment]
I can definitely detect fields that are that way - there are two markers:
1. the `baseName` in the attribute map is different to the `name` in the attribute map (i.e. has a `_` prefix)
2. reserved words from the generator. I think the first is already quite sufficient.

> you can dynamically add a logical type to do the aliasing via a type hook.
That's how I currently add this one, I am doing it based on the schema name however, which definitely doesn't scale well:

from my `typeHook`:
```ts
  if (model.name === "Email") {
    (model as unknown as Avro.schema.LogicalTypeExtension).logicalType =
      EmailLogicalType.NAME;
  }
```

are you suggesting to do the same, but look at all fields programmatically and attaching a logical type?
It hasn't happened, yet, but is there a recommended way of chaining multiple logical types? E.g. let's say a datetime type and one of the reserved words would overlap on the same field.

**Comment by mtth** [comment]
> are you suggesting to do the same, but look at all fields programmatically and attaching a logical type?

Something like that. Here's an example:

```js
class AliasableRecord extends avro.types.LogicalType {
  constructor(schema, opts) {
    super(schema, opts);
    // Use other metadata here as needed to detect the mappings...
    this.fields = schema.fields.map((f) => [f.name, f.aliases?.[0] ?? f.name]);
  }

  _toValue(val) {
    return Object.fromEntries(
      this.fields.map(([name, key]) => [name, val[key]])
    );
  }

  _fromValue(val) {
    return val; // Or reverse the transformation
  }
}

const schema = {
  type: 'record',
  name: 'Person',
  fields: [
    {name: 'from', aliases: ['_from'], type: 'string'},
    {name: 'to', type: 'string'}
  ]
};

const type = avro.Type.forSchema(schema, {
  typeHook: (schema, opts) => {
    if (schema.type === 'record' /* more checks here */) {
      schema.logicalType = 'aliasable';
    }
  },
  logicalTypes: {aliasable: AliasableRecord},
});

type.toBuffer({_from: 'here', to: 'there'});
```

> is there a recommended way of chaining multiple logical types?

Not at the moment; this use-case hasn't come up so far. I would be curious to hear more if you end up hitting it.

**Comment by joscha** [comment]
Will close this for now as the workaround is probably sufficient. Ideally, I think the aliases would be respected on serialization/deserialization as well.
