### ISSUE TITLE
process is not defined in browser

### ISSUE THREAD

**Issue by bill-min** [mtth/avsc#484]
Issue when `import avro from "avsc/etc/browser/avsc-types";`.

https://github.com/mtth/avsc/pull/486

I think there are many ways to resolve the issue, but the key is not to use `util` when in browser.

**Comment by mtth** [comment]
Which bundler are you using?

**Comment by bill-min** [comment]
Its customized stuff and I am using esbuild for one use case. I don't really like the fix personally, but seems like most straightforward change, if we are going to refactoring this lib to use esm and latest stuff anyway. One other way is to use `util-browser` instead of `util` when `require` from `/etc/browser`, but you are going to add one more dependency.

**Comment by mtth** [comment]
Resolved in #486.
