### ISSUE TITLE
Registry is not respected when the schema input type is an object

### ISSUE THREAD

**Issue by NickKelly1** [mtth/avsc#485]
The following code **will** use the the registry

```js
avro.Type.forSchema('long', { registry })
```

Due to this https://github.com/mtth/avsc/blob/aeada8c973d9cff559e9140b99a2853843987535/lib/types.js#L148

Whereas the following code will **not** use the registry

```js
avro.Type.forSchema({ type: 'long' }, { registry })
```

Due to this https://github.com/mtth/avsc/blob/aeada8c973d9cff559e9140b99a2853843987535/lib/types.js#L217

I found this when using the registry for bigint longs with a logical uint64 type.

Tested on `avsc@5.7.7` and NodeJS `22.9.0`

Minimal reproduction here https://github.com/NickKelly1/avsc-registry-reproduction

**Comment by mtth** [comment]
Hi @NickKelly1. This is expected: the registry is only used for type names (string references). Passing an object declares a new type.

**Comment by NickKelly1** [comment]
> Hi @NickKelly1. This is expected: the registry is only used for type names (string references). Passing an object declares a new type.

Thanks for the quick reply. Do you have a recommendation how I should support encoding of uint64's in my application? I was considering a custom bigint long type with logical type mapping the long to ulong however I don't think it works with what's mentioned above. I could use bytes with a logical type but the encoding is slightly longer

**Comment by mtth** [comment]
Using string references in the schema is not an option?

**Comment by NickKelly1** [comment]
How could I use them for a ulong? Create a new type and add it to the registry then string reference it?

**Comment by NickKelly1** [comment]
I've come to this solution

```ts
/** Copied from wiki */
const uint64 = avro.types.LongType.__with({
	fromBuffer(buf: Buffer): BigInt {
		const value = buf.readBigUInt64LE()
		return value
	},
	toBuffer(n: bigint) {
		const buf = Buffer.alloc(8)
		buf.writeBigUInt64LE(n)
		return buf
	},
	fromJSON: BigInt,
	toJSON: BigInt,
	isValid(n: unknown): boolean {
		return typeof n === 'bigint'
	},
	compare(n1: bigint, n2: bigint): number {
		if (n1 === n2) return 0
		if (n1 < n2) return -1
		return 1
	},
})

const avroRegistry = { uint64 }

const myType = avro.Type.forSchema('uint64', { registry: avroRegistry })
```

Seems to work well. Thank you!
