### ISSUE TITLE
`BlobDecoder` does not seem to respect logical types

### ISSUE THREAD

**Issue by joscha** [mtth/avsc#489]
Given this test:

```js
    class SanitizedEnumLogicalType extends LogicalType {
      static NAME = "sanitized-enum";
    
      _fromValue(val) {
        return val.replaceAll("_", "-");
      }
      _toValue(val) {
        return val.replaceAll("-", "_");
      }
      _resolve(type) {
        if (
          Avro.Type.isType(
            type,
            "string",
            `logical:${SanitizedEnumLogicalType.NAME}`,
          )
        ) {
          return this._fromValue;
        }
      }
    }

    test.only('resolve', (cb) => {
      const schema = {
        type: "string",
        logicalType: SanitizedEnumLogicalType.NAME,
      };

      const opts = {
        logicalTypes: {
          [SanitizedEnumLogicalType.NAME]: SanitizedEnumLogicalType,
        }
      }

      const t = Type.forSchema(schema, opts);

      const string = "a-b-c";

      const b = t.toBuffer(string);
      const b_ = t.fromBuffer(b);
      assert.equal(b_, string); // this passes
      
      const strings = [];
      let encoder = new streams.BlockEncoder(t);
      let decoder = new streams.BlockDecoder(opts)
        .on('data', (s) => { strings.push(s); })
        .on('end', () => {
          assert.deepEqual(strings, [string]); // this fails
          cb();
        });
      encoder.pipe(decoder);
      encoder.end(string);      
    })
```

it shows that the first equals passes (e.g. `b_` is `"a-b-c"`).
You can test the case where the decoder doesn't know anything about the logical types via:
```
const b__ = Type.forSchema(schema).fromBuffer(b);
console.log(b__);
```
in this case `b__` is `"a_b_c"` as that is what is in buffer `b`.

Now in case of the rest of the test, both `BlockEncoder` and `BlockDecoder` receive the same `opts` with the logical types, but the `BlockDecoder` still does not apply the logical type, e.g. this test fails with:
```
      Uncaught AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

[
  'a_b_c'
]

should loosely deep-equal

[
  'a-b-c'
]
      + expected - actual

       [
      -  "a_b_c"
      +  "a-b-c"
       ]
```
because the encoded format applied the logical type transformation but the decoder does not apply the inverse. Am I holding it wrong? 

references https://github.com/mtth/avsc/issues/471

**Comment by mtth** [comment]
`logicalTypes` is not a valid `BlockDecoder` constructor option. Can you try with `parseHook`?

```js
let decoder = new avro.streams.BlockDecoder({
  parseHook: (schema) => avro.Type.forSchema(schema, opts),
})
```

**Comment by joscha** [comment]
I am actually using the file encoder/decoder methods, the block decoder was
just more easy to show a reproduction of. What's the reason this option is
not available? Is there a reason not to add and respect it?

**Comment by joscha** [comment]
> ```js
> parseHook: (schema) => avro.Type.forSchema(schema, opts),
> ```

This works, thank you. Still unexpected though.

**Comment by mtth** [comment]
`parseHook` is the way to handle `Type.forSchema`'s options. This approach keeps signatures focused and more modular than if we embedded `logicalTypes` and the other options; benefits are similar to those motivating [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance). It's also more flexible for advanced use-cases.

**Comment by joscha** [comment]
I see. I think the APIs are not super obvious right now. Sometimes I use a type hook, sometimes a parse hook, sometimes logical types, sometimes I control the registry, etc.

It may maybe make sense to unify this a bit more for 6.x or at the very least use `zod` or similar to validate passed options, so when I pass an unsupported option I am presented with an error?
