### ISSUE TITLE
Decode base64 string

### ISSUE THREAD

**Issue by Osmosis311** [mtth/avsc#53]
I have binary Avro data from an Amazon Kinesis stream, however, when I save the data to a file using Node, and then create a fileDecoder object, it says that the magic bytes are invalid.

I am able to convert the data to a base64 string, which, when decoded from a generic online base64 decoder, is able to be run through the file decoder no problem.

What's the best way to parse a binary Avro data object (part of a JSON object) without knowing the fields ahead of time, and without having the data saved to a file?

Thanks!

**Comment by mtth** [comment]
This sounds feasible. Could you provide some sample data?

**Comment by Osmosis311** [comment]
I can't share any sample data at the moment (need to generate some), but do you have a basic example where I can parse as base64 encoded string (with type/schema inference and wrapUnions: true)

Thank you very much!!!

**Comment by mtth** [comment]
You'll need to have either the schema or a decoded value (from which you can `infer` the schema) ahead of time, then something like this should work:

```javascript
// A random value.
var v1 = {foo: 'hi', bar: 123};
// Its corresponding type (skip this if you already know the schema).
var type = avro.infer(v1);
// Base 64 encoding of the value, this should be similar to your input.
var str = type.toBuffer(v1).toString('base64');
// Recover the value, first decoding the string into a buffer.
var buf = new Buffer(str, 'base64'); // `Buffer.from(str, 'base64')` if node>=6.
var v2 = type.fromBuffer(buf)); // == v1
```

If you provide me more information about your input, I can adapt the example to your use-case.

**Comment by Osmosis311** [comment]
Can you email me directly?

danny.ackerman@gmail.com

**Comment by mtth** [comment]
Response timeout.

**Comment by jgavin** [comment]
What was the resolution for this issue? I have been encountering the same issue with an extremely similar use case.
