### ISSUE TITLE
toBuffer methods throws an exception TypeError: Objects.keys called on non-objects. when the schema has avsc schema has been generated using union {null, long} name=null.

### ISSUE THREAD

**Issue by amitvc** [mtth/avsc#55]
See attached schema.

{
  "type" : "record",
  "name" : "id_tran",
  "namespace" : "com.store",
  "fields" : [ {
    "name" : "hdr",
    "type" : {
      "type" : "record",
      "name" : "header",
      "fields" : [ {
        "name" : "chn",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "str",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "lne",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "ctry",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "pos",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "seq",
        "type" : "long",
        "default" : 0
      }, {
        "name" : "ts",
        "type" : "int",
        "default" : 0
      }, {
        "name" : "ses_id",
        "type" : [ "null", "long" ],
        "default" : null
      } ]
    }
  } ]
}

**Comment by mtth** [comment]
Can you also include the value that throws the error?

**Comment by amitvc** [comment]
Actually I upgraded the version of the node module and it started to work. We were running on version 3. something earlier.

**Comment by amitvc** [comment]
I can close the issue if you want. Thanks for the prompt response. Are you still actively maintaining the project.

**Comment by mtth** [comment]
Cool, thanks for the update. Yes, I'm still maintaining it.

**Comment by amitvc** [comment]
Quick question - In order to maintain backward compatibility do you use union or you can declare new element in the schema and assign it 0 value.
e.g - 
union{null, long} ses_id = null;

vs

long ses_id = 0;

Note - client is node and server is java -

For clients which do not have ses_id the java side code fails to parse them. I am using the union to declare the new field as described above. Am I missing something ?

**Comment by mtth** [comment]
It's up to you, both work. Using a union makes it more explicit that the field is optional, but some cases might already have a natural default value (in which case you don't need the union).

**Comment by amitvc** [comment]
The problem is on the java side with the avro generated code it is not able to read the old messages. 

e.g class header {
    int x;
   int y; // New added value.
}

When the old header message is read it gives me EOFException.

**Comment by mtth** [comment]
The writer's and reader's schema still have to be compatible (in your latest example you didn't add a default to `y` so adding it isn't). Also, how are you decoding the message from Java?
