### ISSUE TITLE
Help decoding from snappy compressed base64 bytes

### ISSUE THREAD

**Issue by jgavin** [mtth/avsc#61]
I'm having trouble decoding base64 into an avro schema. Here are the decoded base 64 bytes that I am inputting base64 encoded bytes that are also snappy compressed.

`let compressedBuffer = new Buffer(res.packet.base64EncodedBytes, 'base64'),
           bufferStream = new stream.PassThrough(),
           blockDecoder = new avro.streams.BlockDecoder({codecs: {snappy: snappy.uncompress}});
bufferStream.end(compressedBuffer);
blockDecoder.on('data', function(data, err){
             if (err) {
                            throw 'error processing data: ' + err;
              }
            console.log(data);
});
bufferStream.pipe(blockDecoder);`

I get an impossible to debug "Uncaught Error: Invalid input
      at Error (native)"

If you have any suggestions or alternative methods to accomplishing what I want to accomplish I would greatly appreciate it.

**Comment by mtth** [comment]
Could you post a full stack trace? And paste the base64 _encoded_ bytes of your data, if it's not too big?

**Comment by jgavin** [comment]
Here is an example of the bytes I am using: T2JqAQQWYXZyby5zY2hlbWHGK3sidHlwZSI6InJlY29yZCIsIm5hbWUiOiJBZ0RhdGFTdW1tYXJ5UGFja2V0IiwibmFtZXNwYWNlIjoiY29tLmRlZXJlLmRhdGFwcm9kdWN0cy50cmFuc2Zvcm1lZCIsImRvYyI6IlN1bW1hcnkgUGFja2V0IiwiZmllbGRzIjpbeyJuYW1lIjoiUmVzb3VyY2VOYW1lIiwidHlwZSI6InN0cmluZyIsImRvYyI6ImV4YW1wbGU6IDxjb250ZXh0Pjo8bGF5ZXItbmFtZT46PGxheWVyLXJlcHJlc2VudGF0aW9uPjo8dGltZS1rZXk+Ojx0aWxlLWtleT4ifSx7Im5hbWUiOiJDcmVhdGVkVGltZXN0YW1wIiwidHlwZSI6InN0cmluZyIsImRvYyI6IklTTyA4NjAxIHRpbWVzdGFtcCBpbiBVVEMgb2YgdGhlIGxhc3QgdXBkYXRlIHRvIHRoZSBwYWNrZXQuIn0seyJuYW1lIjoiTWVhc3VyZW1lbnRzIiwidHlwZSI6eyJ0eXBlIjoibWFwIiwidmFsdWVzIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1lIjoiQWdEYXRhTWVhc3VyZW1lbnRTdW1tYXJ5IiwiZG9jIjoiVGhlIHN1bW1hcnkgb2YgYSBzaW5nbGUgbWVhc3VyZW1lbnQuIiwiZmllbGRzIjpbeyJuYW1lIjoiTWVhc3VyZW1lbnROYW1lIiwidHlwZSI6InN0cmluZyIsImRvYyI6IlRoZSBuYW1lIG9mIHRoZSBtZWFzdXJlbWVudCBpbiB0aGlzIGFnZ3JlZ2F0ZS4ifSx7Im5hbWUiOiJUb3RhbEFnZ3JlZ2F0ZSIsInR5cGUiOnsidHlwZSI6InJlY29yZCIsIm5hbWUiOiJNZWFzdXJlbWVudEFnZ3JlZ2F0ZSIsImRvYyI6ImFuIGFnZ3JlZ2F0ZSBvZiBhIG1lYXN1cmVtZW50LiIsImZpZWxkcyI6W3sibmFtZSI6IlRvdGFsQXJlYV9jbTIiLCJ0eXBlIjpbIm51bGwiLCJkb3VibGUiXSwiZG9jIjoiYXBwbGljYWJsZSBmb3IgYXJlYSB3ZWlnaHRlZCBtZWFzdXJlbWVudHMsIHRoaXMgaXMgdGhlIHRvdGFsIGFyZWEgdXNlZCB0byB3ZWlnaHQgdGhlIG1lYXN1cmVtZW50LiJ9LHsibmFtZSI6Ik1pbiIsInR5cGUiOiJkb3VibGUiLCJkb2MiOiJ0aGUgbWluaW11bSB2YWx1ZSBvZiB0aGUgbWVhc3VyZW1lbnQgYW1vbmcgYWxsIHNhbXBsZXMgaW4gdGhpcyBhZ2dyZWdhdGUuIn0seyJuYW1lIjoiTWF4IiwidHlwZSI6ImRvdWJsZSIsImRvYyI6InRoZSBtYXhpbXVtIHZhbHVlIG9mIHRoZSBtZWFzdXJlbWVudCBhbW9uZyBhbGwgc2FtcGxlcyBpbiB0aGlzIGFnZ3JlZ2F0ZS4ifSx7Im5hbWUiOiJUb3RhbCIsInR5cGUiOiJkb3VibGUiLCJkb2MiOiJ0aGUgc3VtIHRvdGFsIG9mIG1lYXN1cmVtZW50IHNhbXBsZSB2YWx1ZXMgaW4gdGhpcyBhZ2dyZWdhdGUgbWVhc3VyZW1lbnQuIn0seyJuYW1lIjoiQ291bnQiLCJ0eXBlIjoiaW50IiwiZG9jIjoidGhlIG51bWJlciBvZiBkYXRhIHNhbXBsZXMgaW5jbHVkZWQgaW4gdGhlIGFnZ3JlZ2F0ZSBtZWFzdXJlbWVudC4ifSx7Im5hbWUiOiJGaXJzdFRpbWVzdGFtcCIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJJU08gODYwMSB0aW1lc3RhbXAgaW4gVVRDIG9mIHRoZSBlYXJsaWVzdCBzYW1wbGUgaW5jbHVkZWQgaW4gdGhpcyBhZ2dyZWdhdGUgbWVhc3VyZW1lbnQuIn0seyJuYW1lIjoiTGFzdFRpbWVzdGFtcCIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJJU08gODYwMSB0aW1lc3RhbXAgaW4gVVRDIG9mIHRoZSBsYXRlc3Qgc2FtcGxlIGluY2x1ZGVkIGluIHRoaXMgYWdncmVnYXRlIG1lYXN1cmVtZW50cy4ifSx7Im5hbWUiOiJGaXJzdCIsInR5cGUiOiJkb3VibGUiLCJkb2MiOiJ0aGUgdmFsdWUgb2YgdGhlIGVhcmxpZXN0IG1lYXN1cmVtZW50IHNhbXBsZSB3aGVuIG9yZGVyZWQgYnkgdGltZXN0YW1wLiJ9LHsibmFtZSI6Ikxhc3QiLCJ0eXBlIjoiZG91YmxlIiwiZG9jIjoidGhlIHZhbHVlIG9mIHRoZSBsYXRlc3QgbWVhc3VyZW1lbnQgc2FtcGxlIHdoZW4gb3JkZXJlZCBieSB0aW1lc3RhbXAuIn1dfSwiZG9jIjoidGhlIHRvdGFsIGFnZ3JlZ2F0ZSBvZiB0aGlzIG1lYXN1cmVtZW50IGluIHRoaXMgcGFja2V0In0seyJuYW1lIjoiTWVhc3VyZW1lbnREaW1lbnNpb25zIiwidHlwZSI6eyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6Ik1lYXN1cmVtZW50RGltZW5zaW9uIiwiZG9jIjoiYW4gYWdncmVnYXRlIG9mIGEgbWVhc3VyZW1lbnQuIiwiZmllbGRzIjpbeyJuYW1lIjoiRGltZW5zaW9uTmFtZSIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJ0aGUgbmFtZSBvZiB0aGUgZGltZW5zaW9uLiAgZXhhbXBsZTogJ1Byb2R1Y3QgTmFtZScifSx7Im5hbWUiOiJEaW1lbnNpb25WYWx1ZSIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJ0aGUgdmFsdWUgb2YgdGhpcyBkaW1lbnNpb24uICBleGFtcGxlOiAgYSBzcGVjaWZpYyBwcm9kdWN0IG5hbWUuIn0seyJuYW1lIjoiRGltZW5zaW9uQWdncmVnYXRlIiwidHlwZSI6Ik1lYXN1cmVtZW50QWdncmVnYXRlIiwiZG9jIjoidGhlIGFnZ3JlZ2F0ZSBvZiB0aGlzIGRpbWVuc2lvbiJ9XX19LCJkb2MiOiJBbGxvd3Mgc3ViIGFnZ3JlZ2F0ZXMgb2YgdGhlIG1lYXN1cmVtZW50IHRvIGJlIG1hZGUgaW4gZGlmZmVyZW50IGRpbWVuc2lvbnMgb2YgdGhlIG1lYXN1cmVtZW50LiAgRm9yIGV4YW1wbGUsIHRvIGFkZCBzdWJhZ2dyZWdhdGVzIGJ5IHByb2R1Y3QgbmFtZSwgY3JlYXRlIGEgZGltZW5zaW9uIGNhbGxlZCAnUHJvZHVjdCBOYW1lJyBhbmQgaW5jbHVkZSBpdHMgc3ViYWdncmVnYXRlcyBieSBwcm9kdWN0IG5hbWUuICBUaGUgc3VtIG9mIGVhY2ggZGltZW5zaW9uIChncm91cGVkIGJ5IERpbWVuc2lvbk5hbWUpIG11c3QgbWF0Y2ggdGhlIFRvdGFsQWdncmVnYXRlLiJ9XX19LCJkb2MiOiJNYXAgb2YgbWVhc3VyZW1lbnQgbmFtZSB0byBtZWFzdXJlbWVudCBzdGF0aXN0aWNzIn1dfRRhdnJvLmNvZGVjDHNuYXBweQDbdJhGoi+ZMdXr7J0sYk+VAtIL9hPAyAIvb3JnSWQvMS9zZXNzaW9uR3VpZC81NzMyMDY2ZS0wMDAwLTEwMDAtN2ZjMC1lMQEC8MAxODZiYmIvb3BlcmF0aW9uVHlwZS9IYXJ2ZXN0L3JlY29yZGVkRm9ybWF0L0dTM18yNjMwOmVuaGFuY2VkLWVwb2NoLXNwYXRpYWwtc3VtbWFyeTphdnJvL2Vwb2NoLXN1bW1hcnkvMS4wOjoxLzAvMDAyMDE2LTA4LTA4VDIzOjQ4OjMwLjAzNloSMEZ1ZWxSYXRlUGVySG91cl9sX3Blcl9ocjBGdWVsUmF0ZVBlckhvdXJfbF9wZXJfaHICAAAAcgMACBgwMgVuRDUtMTBUMTY6MDM6NTIuMjAwWlIZAAw1OTdaPlAAWAIWUHJvZHVjdEdVSUQQNWYxNjJmYjMCPicAPgEA7noADXo8ABxMZW5ndGhPZkN1dF9tbToPADqDAAQwQAmDEQgEaEDigwARQwQwQJL9ABkvCYL+egAFegQAKk2FNE1vaXN0dXJlX3ByY250VhYAOgsBAEcNiQ0IDEBxQAxi7wFiGQAJzA1DBABHlgsBGS8FP/56AAl6TAAkWWllbGRNYXNzRm9yYWdlX2tnShMANQUcemXNfhOefkARCBgbDBqfjvamzgUBEUMRCHoQAhEnEQj+egAdejgAGkRlbHRhVGltZV9zZWM2DgAV+xEBOJzEILByaNk/dZMYBFYOA+YLAwAAFUt6+wARAf56AEp6ADwAHEFyZWFXb3JrZWRfY20yOg8AQv0APgEA4ggEGQGa/QA+AQDuegANekQALklub2N1bGFudERvc2luZ1+p/QB0XhgA/g8B/g8B/g8Beg8BACqFDAhXZXQyDwRWFgA1CxwbEvdYelmMQBEIGJRNucIbQ8XOFwMRQxEIehoCEScRCP56AB16TAAkRGlzdGFuY2VUcmF2ZWxlZF9tShMANQVeAQDupQJNpXoFAV4BAO56AA16BAAAaJC/qtt0mEaiL5kx1evsnSxiT5U=

I've found that there may be a bug with the way the library handles snappy codecs. The error that we were encountering had to do with the fact that the Java avro serializer I use to serialize and snappy compress the data I'm using adds a 4-byte, big-endian CRC32 checksum on the end of each compressed block of data. However, this is not accounted for in the library. We've found a workaround by using the following callback in the blockDecoder: 

`var blockDecoder = new avro.streams.BlockDecoder({codecs: { snappy: function (compressed, cb) {
                        var b = new Buffer(compressed.length - 4);
                        compressed.copy(b, 0, 0, compressed.length - 4);
                        return snappy.uncompress(b, cb);
                 }}});`

This code strips the checksum so that snappy does not throw an invalid input error while decompressing. You may not want to implement a fix for this internally as it would involve adding snappy as a default codec with special handling, but it seems people should be aware of it as it's possible other people could have the same use case (data that is serialized and snappy compressed in the java avro library)

**Comment by mtth** [comment]
You're absolutely correct. The Avro specification defines the snappy codec as [including a checksum](https://avro.apache.org/docs/1.8.0/spec.html#snappy). It doesn't make sense to make this library depend on snappy though (and adding a custom option just for this doesn't seem adequate either) so I'll update the API to document this. Thanks for bringing this up!

BTW, you can slightly optimize your code to avoid copying data:

```javascript
var blockDecoder = new avro.streams.BlockDecoder({
  codecs: {
    snappy: function (buf, cb) {
      // We could also do some validation here using the checksum.
      return snappy.uncompress(buf.slice(0, buf.length - 4), cb);
    }
  }
});
```
