### ISSUE TITLE
Parsing Type Fixed from JSON String

### ISSUE THREAD

**Issue by steve-gray** [mtth/avsc#62]
Where I'm working we've noticed that it seems to be impossible to convert a schema that uses type: fixed to a JSON value and then persist/recover it from disk or other transports. It appears that there's some explicit checking of the type of the value to be a native buffer. We've tried:

- [0x0, 0x0....] arrays
- \u0000\u0000.... strings

And a few other permutations. Are we missing a trick here, or is this something we need to work around? Looking at ./lib/types.js#778, this seems to be the likely place - but not sure. We're about to start an evil workaround involving pre/post processing - but would appreciate a steer.

**Comment by mtth** [comment]
Are you using the [`type.toString`](https://github.com/mtth/avsc/wiki/API#typetostringval) and [`type.fromString`](https://github.com/mtth/avsc/wiki/API#typefromstringstr) functions? These will correctly handle binary encodings (along with a few other things that `JSON.parse` and `JSON.stringify` don't).

For example:
```javascript
var idType = avro.parse({type: 'fixed', name: 'Id', length: 4});
var id = new Buffer('abcd');
var str = idType.toString(id); // JSON-encoded ID.
var sameId = idType.fromString(str); // Same ID.
```

(Note that JSON serialization is very slow, I would encourage you to use the binary equivalent as much as possible.)

**Comment by steve-gray** [comment]
@mtth - We're using binary internally, but when people send the data up to a REST service we're absorbing it as JSON and then persisting it as the binary form.

@jasonhold / @dpangier - Can you see if this works?

**Comment by mtth** [comment]
@steve-gray - Any updates?

**Comment by mtth** [comment]
Closing as inactive. Feel free to reopen if you have any further questions.
