### ISSUE TITLE
Support for confluent schema registry

### ISSUE THREAD

**Issue by DavidHembree** [mtth/avsc#63]
It would be useful to have support for Confluent schema registries in this library.
http://docs.confluent.io/2.0.0/schema-registry/docs/design.html

We'd like to leverage schema versioning as referenced in the Kafka wire protocol guide:
https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets

Ideally, if the codec comes across a message whose schema (or schema version) it does not have, it can attempt to fetch that schema from the registry.

**Comment by mtth** [comment]
This would definitely be good to have but belongs in a higher level, separate, library. I'm happy to provide feedback if you want to give it a shot.
