### ISSUE TITLE
Uncaught TypeError: this.buf.utf8Write is not a function

### ISSUE THREAD

**Issue by gustavobilert** [mtth/avsc#64]
Hi, I am trying the example from the main page.
The call to
`var buf = type.toBuffer({kind: 'CAT', name: 'Albert'}); // Encoded buffer.`
throws this error:
```
Uncaught TypeError: this.buf.utf8Write is not a function
Tap.writeString @ showcase.bundle.js:91977
StringType._write @ showcase.bundle.js:89413
writePet @ VM11995:5
Type.toBuffer @ showcase.bundle.js:88986
(anonymous function) @ showcase.bundle.js:102
__webpack_require__ @ showcase.bundle.js:20
(anonymous function) @ showcase.bundle.js:47
__webpack_require__ @ showcase.bundle.js:20
(anonymous function) @ showcase.bundle.js:40
(anonymous function) @ showcase.bundle.js:43
```

**Comment by gustavobilert** [comment]
I have found a possible fix:
On utils.js change line 538 to `this.buf.write(s, pos, len);` and line 522 to `return this.buf.slice(pos, pos + len);`
But when I convert back from the buffer, I get this:
`Pet {kind: "CAT", name: Uint8Array[6]}`
Please apply the fix and check the string conversion problem

**Comment by gustavobilert** [comment]
The second problem was because the fix was not right.
Line 522 should be:
`return this.buf.slice(pos, pos + len).toString();`
May you apply the fix and publish a new version please?

**Comment by mtth** [comment]
From your stack trace, it looks like you are using `webpack`, which is likely the problem. `avsc` is compatible out of the box with `node` and `browserify` but last I heard `webpack` doesn't support a [browser-specific entry point](https://github.com/defunctzombie/package-browser-field-spec).

I'm not familiar with `webpack` but I think you should be able to work around this by using [aliases](https://webpack.github.io/docs/configuration.html#resolve-alias), substituting `'avsc'` with `'avsc/etc/browser/avsc'` (or just requiring the latter directly). You might also be interested in the [other available distributions](https://github.com/mtth/avsc/wiki#distributions).

**Comment by gustavobilert** [comment]
Ok, I have found the "Shim without file-system operations" in your code:
```
// Since there are no utf8 and binary functions on browserify's `Buffer`, we
// must patch in tap methods using the generic slice and write methods.
```
Which has exactly the code I had proposed.

Using 'avsc/etc/browser/avsc-protocols' solved the problem, thanks!
