### ISSUE TITLE
Documentation does not specify which version of the Avro spec the lib is compliant with

### ISSUE THREAD

**Issue by ultrafez** [mtth/avsc#68]
The current version of the Avro specification is 1.8.1, but the documentation for `avsc` doesn't specify whether it is compatible with 1.8.1 or an earlier version.

**Comment by mtth** [comment]
Thanks for bringing this up, it's compliant with the latest version. I added a note in the [wiki](https://github.com/mtth/avsc/wiki). Note that the spec is relatively stable: all `1.x.x` versions are compatible with each other (in terms of encoding and call format).

**Comment by ultrafez** [comment]
That's great - thanks for the clarification.
