### ISSUE TITLE
buffer corruption during serialization

### ISSUE THREAD

**Issue by stevelr** [mtth/avsc#7]
during serializing of an object, the buffer write position is reset and new fields overwrite previous ones. The returned buffer is corrupt.

A simplified version of the stack trace is 
```
Type.toBuffer       <- (3)
RecordType._createWriter  <- (2)
RecordType 
(anonymous function)
Type.fromSchema 
(anonymous function)
...
Type.fromSchema 
UnionType._write 
writeEvent
Type.toBuffer 
(anonymous function) <-(1)
```
in (1), my app calls toBuffer() to serialize an object 
in (2), toBuffer is called again to serialize a default value
in (3) the global buffer TAP is re-used for the default value and pos gets set to zero.

There's a comment inside createWriter that mentions the possibility of a buffer pool. Using a buffer pool to allocate a new buffer for saving the default value, instead of re-using the global one, would have avoided this issue.

The original call toBuffer() from my app returns without throwing any exceptions, but the data in the buffer has been corrupted and the total buffer length is shorter than expected. In my avro schema, I have several nested unions (unions aren't nested immediately, there is a record between). If that is relevant, it might explain why people haven't run into this before.

**Comment by stevelr** [comment]
Here's a patch with a very simple buffer pool. After implementing this change, it works for me.
```
49,50c49,50
< // Encoding tap (shared for performance).
< var TAP = new Tap(new buffer.SlowBuffer(1024));
---
> // Buffer pool for Encoding taps
> var bufferPool = [];
121c121
< Type.__reset = function (size) { TAP.buf = new buffer.SlowBuffer(size); };
---
> Type.__reset = function (tap, size) { tap.buf = new buffer.SlowBuffer(size); };
164,172c164,175
<   TAP.pos = 0;
<   this._write(TAP, obj);
<   if (!TAP.isValid()) {
<     Type.__reset(2 * TAP.pos);
<     TAP.pos = 0;
<     this._write(TAP, obj);
<   }
<   var buf = new Buffer(TAP.pos);
<   TAP.buf.copy(buf, 0, 0, TAP.pos);
---
>   var tap = bufferPool.length ? bufferPool.pop() : new Tap(new buffer.SlowBuffer(1024));
>   tap.pos = 0;
>   this._write(tap, obj);
>   if (!tap.isValid()) {
>     Type.__reset(tap, 2 * tap.pos);
>     tap.pos = 0;
>     this._write(tap, obj);
>   }
>   var buf = new Buffer(tap.pos);
>   tap.buf.copy(buf, 0, 0, tap.pos);
>   // all done, return it to the pool
>   bufferPool.push(tap);

```

**Comment by mtth** [comment]
I'm a bit confused; `toBuffer` doesn't get called when serializing default values, it only gets called once when the schema is parsed. Could you share a snippet reproducing the error? ([This script](https://github.com/mtth/avsc/blob/master/etc/scripts/obfuscate_schema.js) might come in handy if you'd like to obfuscate your schema.)

**Comment by mtth** [comment]
@stevelr - Any updates on this? If you could just provide the code or even an exact stack trace, that would be most helpful. Your current stack trace is not possible.

**Comment by stevelr** [comment]
I'm pretty sure this was my bug. I hacked the apache-avro java code generator to compile avro to typescript, then used typescript to javascript compiler to get javascript classes. The generated code for javascript unions was incorrect, resulting in UnionType._write getting called with RecordType objects.

**Comment by mtth** [comment]
Thanks for letting me know.
