### ISSUE TITLE
Options are not properly passed to createType in BlockDecoder

### ISSUE THREAD

**Issue by bball7210** [mtth/avsc#72]
In the BlockDecoder, the opts passed during instantiation are not used when types are created during _decodeHeader.

I have included a patch below that fixes this.

-------------------------------------------------------------------
Patch:
-------------------------------------------------------------------
@@ -127,7 +127,7 @@
  *
  */
 function BlockDecoder(opts) {
-  opts = opts || {};
+  this._opts = opts || {};
 
   var noDecode = !!opts.noDecode;
   stream.Duplex.call(this, {
@@ -194,7 +194,7 @@
     if (this._parseHook) {
       schema = this._parseHook(schema);
     }
-    this._type = types.createType(schema);
+    this._type = types.createType(schema, this._opts);
   } catch (err) {
     this.emit('error', err);
     return;

**Comment by mtth** [comment]
The `BlockDecoder`'s `opts` argument isn't meant to be passed to the parse hook (it contains different options than those used by [`avro.parse`](https://github.com/mtth/avsc/wiki/API#parseschema-opts)). Instead you would pass in custom options to create the type as follows:

```javascript
const decoder = new avro.streams.BlockDecoder({
  parseHook: function (attrs) { return avro.parse(attrs, {/* Type options. */}); }
});
```

I added an example to the [API doc](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) to help clarify this.
