### ISSUE TITLE
isSafeLong incompatible with Java MinLong/MaxLong

### ISSUE THREAD

**Issue by danluszcz** [mtth/avsc#76]
The MaxLong in Java is 2^63 - 1 (9223372036854775807).  The MinLong in java is -9223372036854775808.  The isSaveLong function in types.js uses a much smaller range:

function isSafeLong(n) {
  return n >= -9007199254740990 && n <= 9007199254740990;
}

**Comment by mtth** [comment]
This is a limitation of JavaScript (which represents all numbers as doubles). See the [documentation for custom long types](https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types) for information on how to support 64-bit integers.
