### ISSUE TITLE
Update wiki page Advanced-usage.md

### ISSUE THREAD

**Issue by callumsmits** [mtth/avsc#79]
I have two suggestions for the suggested javascript to use the 'long' package:
- replace ```const buf = new Buffer(8);``` with ```const buf = Buffer.alloc(8);``` to address the fact this is now deprecated in [node](https://nodejs.org/api/buffer.html#buffer_new_buffer_size).
- replace ```compare: Long.compare``` with ```compare: (n1, n2) => Long.compare(n1, n2)```

If it makes life easier, I have updated the [wiki on our fork](https://github.com/packetloop/avsc/wiki/Advanced-usage) to reflect these changes.

**Comment by mtth** [comment]
Done, thanks for the heads up.

Did you mean `compare: (n1, n2) => n1.compare(n2)` for the second part? That's what [`long`'s documentation](https://github.com/dcodeIO/long.js#longcomparecompother) currently seems to say.
