### ISSUE TITLE
enum values not compatible with Typescript

### ISSUE THREAD

**Issue by stevelr** [mtth/avsc#8]
When typescript generates javascript code for enums, it generates code that stores values as integers (the zero-index offset of the string label), which corresponds with the avro spec for serializing enums.

    Avro IDL source:
    enum Fruit { APPLE, BANANA, PEAR }
    record Snack {
        Fruit fruit
    }

Typescript source

     export enum Fruit { APPLE, BANANA, PEAR }
     export class Snack {
         private fruit: Fruit;
         public getFruit():Fruit { return this.fruit; }
         public setFruit( value: Fruit ) { this.fruit = value; }
     }

After this compiles to javascript, I can call setFruit(Fruit.APPLE) and it stores an int value for the fruit member. (in javascript, any reference to ENUM_TYPE.VALUE is an integer). However, if you try to serialize it with avsc, it fails, because

    EnumType.prototype.isValid() 
assumes that enum fields are stored as strings.

The following patch works for me
```
--- types.js    2015-10-25 09:29:38.000000000 -0700
***************
*** 819,821 ****
  EnumType.prototype.isValid = function (s) {
!   return typeof s == 'string' && this._indices[s] !== undefined;
  };
--- 819,825 ----
  EnumType.prototype.isValid = function (s) {
!   if (typeof(s) === 'number' && Number.isInteger(s) && s >= 0 && s < Object.keys(this._indices).length)
!     return true;
!   if (typeof(s) === 'string' && typeof(this._indices[s]) !== 'unknown')
!     return true;
!   return false;
  };
```

I am using Typescript compiler version 1.5.3.

**Comment by mtth** [comment]
Since TypeScript already does the encoding for you, you don't need an `EnumType` anymore (you're not even using its schema). You should override the type used for `enum`s instead. You can do this as follows:

```javascript
var longType = new avsc.types.LongType();

function typeHook(schema, opts) {
  if (schema.type === 'enum') {
    // Use `LongType` instead (also add it to the `registry` for references to work).
    return opts.registry[schema.name] = longType;
  }
}

// `type` below will decode/encode any `enum`s into/from integers.
var type = avsc.parse(yourSchema, {typeHook: typeHook});
```

Hope this helps! (The documentation for `typeHook` is minimal currently, I'm planning on adding a few examples in the future.)

**Comment by stevelr** [comment]
Thanks : that works!
