### ISSUE TITLE
How to write the value into avro file?

### ISSUE THREAD

**Issue by white819** [mtth/avsc#81]
Hi, I follow the examples code  and want to write the value 
`{kind: 'CAT', name: 'Albert'}` 
with the schema 
```
{
  name: 'Pet',
  type: 'record',
  fields: [
    {name: 'kind', type: {name: 'Kind', type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
}
```
into a local file.
I found function createFileEncoder() , but still have no idea to make it. 
Please give me some help.

**Comment by mtth** [comment]
Sure, the following should help get you started:

```javascript
var type = avro.parse({
  name: 'Pet',
  type: 'record',
  fields: [
    {name: 'kind', type: {name: 'Kind', type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});
var encoder = avro.createFileEncoder('./pets.avro', type);
encoder.write({kind: 'CAT', name: 'Albert'});
// Write other pets as desired...
encoder.end();
```

The above will create a standard [Avro container file](https://avro.apache.org/docs/1.8.0/spec.html#Object+Container+Files). If you'd like to see the contents of the file:

```javascript
avro.createFileDecoder('./pets.avro')
  .on('data', function (pet) { console.log(pet); });
```

**Comment by white819** [comment]
Oh,thanks, it works!
