### ISSUE TITLE
Parsing container files that are delivered as string

### ISSUE THREAD

**Issue by bubblegumsoldier** [mtth/avsc#84]
From my (flask) web backend I am receiving a container file content as a string (which is actually the binary) that I generated with the avro python module. I would like to decode the content. When I use the `fromBuffer()` function it doesn't quite work out. I already found out that this cannot be used to parse container files.

I have got the schema and the binary and would like to receive all contained objects as an array. I already tried this code snippet which was mentioned here: "ambiguous unwrapped union #52" and replaced the file decoder with the blob decoder, but I have no idea whether that's the right way to go.

```
var readable = avro.createBlobDecoder(this.binaryResponse, {parseHook: (attrs) => { return avro.parse(attrs, {wrapUnions: true}); }})
```

This just returns a strange object of which I don't know how to use it and I find it very strange that I don't have to insert my avro type anywhere...

So maybe someone can help me filling out this missing puzzle peace:

```
//my parsed avro type where I used avro.parse()
var type = AvroManager.avroModels[globalConfig["serviceSchemaURL"]].type;
//binary containing many serialized objects of type "type"
var binary = this.binaryResponse;

var result = doCoolStuffAndReturnArray(type, binary)
```

This is frontend scripting by the way, so browser scripting.

Thanks a lot!

**Comment by mtth** [comment]
The `BlobDecoder` will only work on [blob-like](https://developer.mozilla.org/en-US/docs/Web/API/Blob) objects. The simplest here would be to decode the string back into a buffer, wrap it in a readable stream, and pass to a `BlockDecoder`. Here's a function that should let you do that (the encoding you pass in should match the one used by the server, e.g. `'base64'` or `'binary'`):

```javascript
var stream = require('stream');

/** Create a stream of decoded values from a container file string. */
function createStringDecoder(str, encoding) {
  return new stream.Readable({
    read: function () {
      this.push(new Buffer(str, encoding));
      this.push(null);
    }
  }).pipe(new avro.streams.BlockDecoder());
}

// Sample usage:

/** Gather all values into an array. */
function gatherValues(str, encoding, cb) {
  var vals = [];
  createStringDecoder(str, encoding)
    .on('data', function (val) { vals.push(val); })
    .on('end', function () { cb(null, vals); });
}

var str; // A base64 encoded string from your server.
gatherValues(str, 'base64', function (err, vals) {
  // Here `vals` is the array of all values in the container file.
});
```

Also:

+ Container files already include the [writer's schema](http://avro.apache.org/docs/1.8.1/spec.html#Object+Container+Files) so you usually don't need to provide one (unless you're trying to [evolve the schema](http://avro.apache.org/docs/1.8.1/spec.html#Schema+Resolution)).
+ You won't need to pass in the `unwrapUnions`, except if you get the "ambiguous union" error (in which case you would pass it similarly to `BlockDecoder`'s constructor).

Let me know if anything is still unclear.
