### ISSUE TITLE
Is it necessary to have all record types in one json?

### ISSUE THREAD

**Issue by StarpTech** [mtth/avsc#85]
Hi,
I want to split my records in different files because reusability. Does exists a global register in avsc at runtime?

e.g here https://github.com/linkedin/goavro/blob/master/examples/nestedRecords/nestedRecords.go
its needed to parse the records from seperate schemas.

**Comment by StarpTech** [comment]
I got it. I think this should be in the docs.

```json
{
        "name": "trace",
        "type":  avro.parse(recordTraceSchema);
    }, 
```

**Comment by mtth** [comment]
That'll work. Otherwise you can use [`parse`](https://github.com/mtth/avsc/wiki/API#parseschema-opts)'s `registry` option too:

```javascript
const avro = require('avsc');

const registry = {};
// Define a type separately.
const fooType = avro.parse({type: 'fixed', name: 'Foo', size: 2}, {registry});
// Then reference it.
const fooMapType = avro.parse({type: 'map', values: 'Foo'}, {registry});
```

I'll try to find a better way to highlight this feature.
