### ISSUE TITLE
TypeError: this.buf.utf8Write is not a function

### ISSUE THREAD

**Issue by Tamriel** [mtth/avsc#86]
I'm using your library with Scala.js, but get the above exception. It would be great if you can take a look! http://stackoverflow.com/questions/42040851/typeerror-this-buf-utf8write-is-not-a-function

**Comment by mtth** [comment]
Hey, this is related to https://github.com/mtth/avsc/issues/64. It should work fine if you `require('avsc/etc/browser/avsc')` (or any of the [other distributions](https://github.com/mtth/avsc/wiki#distributions)).

**Comment by Tamriel** [comment]
Thanks, that worked!
You could add the sentence 'When used on the client side with webpack or browserify, you have to use `require('avsc/etc/browser/avsc')`.' on the installation section of the README.md.
