### ISSUE TITLE
TypeError: this.buf.copy is not a function

### ISSUE THREAD

**Issue by Tamriel** [mtth/avsc#88]
When I decode [this](https://gist.github.com/Tamriel/35c86738ca9ab04692c485b77d605341) avro type from a websocket message like below
```
websocket.onmessage = function (e) {
    const val = serverToClientType.fromBuffer(e.data);
```
I get `TypeError: this.buf.copy is not a function`. I imported avsc with `require('avsc/etc/browser/avsc')`.

**Comment by mtth** [comment]
What's the type of `e.data`? `type.fromBuffer` expects a `Buffer`, so you might need to wrap it (e.g. if it's a `Uint8Array`).

**Comment by Tamriel** [comment]
Thank you very much! Two things were necessary:
1. [Setting](http://stackoverflow.com/a/13591140/1655547) the binaryType attribute of the WebSocket to "arraybuffer"
2. Wrapping `e.data`: 
```
const buf = Buffer.from(e.data);
const val = serverToClientType.fromBuffer(buf);
```
This [Buffer library](https://github.com/feross/buffer) is then needed.
