### ISSUE TITLE
Add RPC support.

### ISSUE THREAD

**Issue by mtth** [mtth/avsc#9]
+ [x] Protocol request and response types.
+ [x] Stateful transports (e.g. `WebSocket`s, node `Duplex` streams).
+ [x] Stateless transports.
+ [x] IDL (probably only in node).

**Comment by skaapgif** [comment]
In #14 you mentioned that you're still figuring out how to approach this. Have you given it any more thought?

I'm interested in having a universal RPC mechanism (between backend microservices as well as between frontend and backend). Usually such interfaces are written as RESTful web services which has the advantage of being universal and easy to integrate with, but comes with other disadvantages. Representing all possible operations as CRUD is sometimes cumbersome and RESTful web services don't lend themselves well to realtime reactive applications.

Perhaps implementing this as a Node Duplex stream is the best abstraction making it easy to connect with different stateful transport mechanisms such as TCP Sockets or WebSockets. https://github.com/primus/primus for instance is an abstraction on top of several WebSocket libraries that exposes a stream interface.

**Comment by mtth** [comment]
@skaapgif - I'm still working on including this. Using duplex streams is definitely a possibility. There are still a few things to figure out though, for example making sure that we can also include stateless transports in a way that makes sense or supporting large messages. Thank you for the Primus link, I wasn't aware of the project.

**Comment by mtth** [comment]
@skaapgif  - This is still work in progress, but I'm thinking of something along these lines:

+ Client:

  ```javascript
  var protocol = avsc.parse('./dat/mail.avpr');

  // Sample transport.
  var socket = net.createConnection({port: 8000});

  // Avro RPC client.
  var rpcClient = protocol.createClient(socket)
    .on('end', function () { socket.destroy(); });

  // Send messages...
  rpcClient.emitMessage('letter', {text: 'hi'}, function (err, res) {
    // This function will be called asynchronously when the remote call
    // returns, with the corresponding error and response values.
  });

  // And so on...
  rpcClient.emitMessage('letter', {text: 'hey'}, function (err, res) {
    // Messages are sent as quickly as possible (they don't wait for responses
    // to previous messages to be back), so one long-running remote call won't
    // block others.
  });

  // ... And once done:
  rpcClient.destroy();
  ```

+ Server:

  ```javascript
  var protocol = avsc.parse('./dat/mail.avpr');

  // Create server and attach message handlers.
  var rpcServer = protocol.createServer()
    .onMessage('letter', function (letter, cb) {
      // Do something with the request... The arguments passed to `cb` will be
      // transparently passed to the callback defined inside the RPC client's
      // initial request.
    })
    .onMessage('parcel', function (parcel, cb) {
      // ...
    });

  // Attach RPC server to each new connection.
  net.createServer()
    .on('connection', function (socket) { rpcServer.addTransport(socket); })
    .listen(8000);
  ```

The examples above use sockets as transport but the API would support arbitrary streams and even stateless transports (for example over HTTP) by passing in "stream factory functions" instead. Let me know if you have any thoughts!

**Comment by skaapgif** [comment]
I really like the idea of passing in stream factories, essentially the library will only be responsible for implementing the RPC protocol, the underlying transport is transparent and up to the user to choose or implement. The documentation could always include a few examples for state-full/less transports.

I'm not too sure about the server API. In my opinion, Node.js programs follow two types of event emitter conventions and sometimes both of them are available at the same time:
```
server.on('letter', function(e, cb){...})
// OR
server.onLetter(function(e, cb){...})
```

Given this convention, I would expect `onMessage` to take a callback function, not be an event emitter itself. If I only saw the api function names, I would expect `onMessage` to call the attached function every time a message comes in, a bit like a catch-all for all communication to the server.

Here's some other ideas:
```
rpcClient.request('letter', {text: 'hi'}, function (err, res) {...}
// OR, similar to websocket api
rpcClient.send('letter', {text: 'hi'}, function (err, res) {...}
// OR, similar to stream api
rpcClient.write('letter', {text: 'hi'}, function (err, res) {...}

rpcServer.on('letter', function(letter, cb) {...})
```

I've seen some JS libraries use `rpcClient.call`, but since `call` is almost like a reserved word in JS, I don't think it's good to repurpose it.

What do you think? Hope this feedback is helpful.

**Comment by mtth** [comment]
Thanks for the feedback.

> I really like the idea of passing in stream factories, essentially the library will only be responsible for implementing the RPC protocol, the underlying transport is transparent and up to the user to choose or implement. The documentation could always include a few examples for state-full/less transports.

Yes :).

> Given this convention, I would expect onMessage to take a callback function, not be an event emitter itself. If I only saw the api function names, I would expect onMessage to call the attached function every time a message comes in, a bit like a catch-all for all communication to the server.

So that's almost exactly what it would do. The only differences are:

+ The first parameter which is used to say which message to listen to (rather than have a catch-all). This is consistent with `EventEmitter`s' `on` method which expects the event's name first.
+ The callback doesn't take `err` as first argument, but rather the remote message's parameters. This is again consistent with how event emitters work: `ee.on('foo', function (n) { /* ... */ })` will be called with `n` being `123` by `ee.emit('foo', 123)` (or readable streams, which pass `data` as first and only argument).

The general idea was actually to mimic as closely as possible the `EventEmitter` API. The methods are the same but suffixed with `Message`: `emit -> emitMessage`, and `on -> onMessage`. (I'm not sure whether the above confusion came from "message" being too similar to "letter", and being understood as a message's name rather than a generic suffix.)

If you're wondering why have a suffix at all, this is also for two main reasons:
+ Since Avro protocols can have messages with arbitrary names, these could override "special" events (namely `error`).
+ It's still useful to keep the local emitting capabilities, so rather than rename that method and override it with a different behavior, it felt more natural to just create a new one.

Does this make sense?

**Comment by skaapgif** [comment]
> If you're wondering why have a suffix at all, this is also for two main reasons:
>
> - Since Avro protocols can have messages with arbitrary names, these could override "special" events (namely error).
> - It's still useful to keep the local emitting capabilities, so rather than rename that method and override it with a different behavior, it felt more natural to just create a new one.

Yeah I didn't think about the clashes of the RPC function names and potential internal server error events.

**Comment by mtth** [comment]
@skaapgif - Motivated by your feedback, I simplified the API to match the core `EventEmitter`'s (i.e. using `emit` and `on`, [preview here](https://github.com/mtth/avsc/wiki/Home/40dbbd24e3295d7cb56d14a23c98127b8188e48e#and-rpc)). Briefly, the main change enabling this was to split remote and local events entirely (remote events are now emitted and handled via `Protocol` instances directly).

Let me know if you have any other thoughts, otherwise this should be ready to go out soon!

**Comment by mtth** [comment]
`3.2.0` is now released with protocol support.

**Comment by mtth** [comment]
IDL support added in [`3.3.0`](https://github.com/mtth/avsc/releases/tag/3.3.0).
