### ISSUE TITLE
Extra double quotes on .toString()

### ISSUE THREAD

**Issue by alsonkemp** [mtth/avsc#90]
Not sure if this is intended behavior but we get extra double quotes on .toString().  Example:

    > let m = avsc.parse({
             name: 'Ping',
             type: 'record',
             fields: [ ]
         }, {namespace: 'com.teckst.channel'});
    > m.toString()
    '"com.teckst.channel.Ping"'   <---------
    > m.getName()
    'com.teckst.channel.Ping'

Thoughts?

**Comment by mtth** [comment]
Thanks for asking, this is WAI. The type's `toString` returns a shortened version of the type's schema (but still valid JSON, hence the extra quotes).

`type.getName()` is the right method to call if you'd like the type's name as a raw string (note also that unlike `toString`, `getName` will return `undefined` for unnamed types, e.g. `int`s).
