### ISSUE TITLE
float issue

### ISSUE THREAD

**Issue by joaomilho** [mtth/avsc#91]
So I have a schema with `latitude` and `longitude` keys, both being of type `float`. 

When I run `schema.fromBuffer(schema.toBuffer(event))`, I get a precision difference on both. For instance, the original latitude is 40.2964197 and the resulting one is 40.29642105102539.

Thanks!

**Comment by mtth** [comment]
JavaScript numbers are `double`s so there can be precision loss if you store them using `float`s:

```sh
$ node
> l = 40.2964197
40.2964197
> b = Buffer(8)
<Buffer 00 00 00 00 00 00 00 00>
> b.writeFloatLE(l)
4
> b.readFloatLE(0)
40.29642105102539 # Precision loss.
> b.writeDoubleLE(l)
8
> b.readDoubleLE(0)
40.2964197 # No precision loss.
```

If you want to guarantee a round-trip, Avro has a `double` type you can use:

```sh
> l = 40.2964197
40.2964197
> t = require('avsc').Type.forSchema('double')
<DoubleType>
> t.fromBuffer(t.toBuffer(l))
40.2964197
```

**Comment by joaomilho** [comment]
danke!
