### ISSUE TITLE
procedure calls

### ISSUE THREAD

**Issue by joaomilho** [mtth/avsc#92]
README mentions "procedure calls", but I can't find anything in the Docs. Can you explain that?

Thanks!

**Comment by mtth** [comment]
The quickstart guide's [services section](https://github.com/mtth/avsc/wiki/Quickstart#services) should give you an overview of RPC (remote procedure calls) with `avsc`. Let me know if there are any specific questions I can answer too.

I'll also point the RPC link in the README to it; I forgot to update it during the last major release. Thanks for bringing this up!

**Comment by joaomilho** [comment]
Thanks, will take a look shortly.
