### ISSUE TITLE
Error while decoding Avro data with NodeJS

### ISSUE THREAD

**Issue by ArunAdPushup** [mtth/avsc#93]
Hi,

I am using ``Azure EventHubs archive`` to store my event hubs data to an azure blob storage. Eventhubs archive stores the data in ``avro`` format. I've written an ``Azure function`` in ``NodeJS`` that listens to the blob trigger event (fired whenever data is sent to Eventhubs and written to the blob storage in ``avro`` format). 

I am using the [avsc](https://github.com/mtth/avsc) library for doing this. 

As soon as the trigger is fired, I want to decode the data sent in ``avro`` format (which is a binary buffer) and convert it into ``json``. 
I tried using the ``fromBuffer`` method by specifying my ``avro`` schema, but it keeps giving me this error - 
```
TypeError: this.buf.utf8Slice is not a function
```
Here's my code - 

```
const avro = require('avsc');

module.exports = function (context, myBlob) {
    const schema = avro.Type.forSchema({
        "type" : "record",
        "name" : "EventData",
        "namespace" : "Microsoft.ServiceBus.Messaging",
        "fields" : [ {
            "name" : "SequenceNumber",
            "type" : "long"
        }, {
            "name" : "Offset",
            "type" : "string"
        }, {
            "name" : "EnqueuedTimeUtc",
            "type" : "string"
        }, {
            "name" : "SystemProperties",
            "type" : {
            "type" : "map",
            "values" : [ "long", "double", "string", "bytes" ]
            }
        }, {
            "name" : "Properties",
            "type" : {
            "type" : "map",
            "values" : [ "long", "double", "string", "bytes", "null" ]
            }
        }, {
            "name" : "Body",
            "type" : [ "null", "bytes" ]
        } ]
    });

    if(myBlob.length){
        context.log("JavaScript blob trigger function processed blob \n Name:", context.bindingData.name, "\n Blob Size:", myBlob.length, "Bytes");
        context.log(schema.fromBuffer(myBlob)); // myBlob contains the binary avro buffer data
    }
    context.done();
};
```

**Comment by mtth** [comment]
What's the type of `myBlob` above?

`type.fromBuffer` expects a [`Buffer`](https://nodejs.org/api/buffer.html). I'm not familiar with Azure functions but from quickly looking around it looks like [by default the blob is a string and you'd need to add a `binary` `dataType` option](http://stackoverflow.com/a/39240551/1062617).

**Comment by ArunAdPushup** [comment]
Yes its a buffer. I've already set the dataType option to binary in my function config.

**Comment by mtth** [comment]
`Buffer` objects have a `utf8Slice` method since before `0.1.90` (~2011). Is the code running on node? If so, which version?

**Comment by ArunAdPushup** [comment]
It's running on node ``v6.5.0``.

I was able to make it work anyways using the ``BlockDecoder``. While going through one of the issues, there was one example where a similar technique was mentioned -

 ```javascript
       const decoder = new avro.streams.BlockDecoder();
       decoder.end(blob);
            
        decoder.on('data', eventData => { 
            const val = JSON.parse(eventData.toString()).Body.bytes;
            context.log(val); 
        })
        .on('end', () => { 
            context.log(`File decoding ended for - ${context.bindingData.name}`);
        });
```

Just wanted to clarify one thing regarding it, the line  - ``decoder.end(blob);`` is supposed to bind the binary buffer data to the block decoder right ?

**Comment by mtth** [comment]
The `BlockDecoder` is a vanilla duplex stream so `decoder.end(blob)` writes the `blob` to it and ends it (see the [API reference](https://nodejs.org/api/stream.html#stream_writable_end_chunk_encoding_callback) for more information). Also `BlockDecoder` still expects a `Buffer` as input, so this doesn't explain the error above if nothing else changed.

Finally, looking briefly at the snippet you've quoted, `JSON.parse(eventData.toString()).Body.bytes` is likely to be slow. If the goal is to convert `bytes` in the message to a string, you're probably better off using the returned field's `toString`: `eventData.Body.bytes.toString('binary')`.

**Comment by ArunAdPushup** [comment]
Thanks a lot for the explanation @mtth.
