### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by juanpjacob** [mtth/avsc#95]
Why is it that avsc is not supported in android (and some other mobile) devices?
The avro library encodes the data and sends it without any error, but we get an incorrect message when we receive it. The payload received just misses the first field, which comes in null, the rest of the data is OK. Is there any way to solve this?

**Comment by mtth** [comment]
Hard to say without more information. How are you serializing/deserializing the data? What protocol are you using to send it over the wire? It seems odd that only the first field would be read wrong, perhaps a magic header needs to be inserted before the record.

**Comment by juanpjacob** [comment]
I am sending the info through https (sending the data in the body of a POST with the header `content-type:avro/binary`) to a backend server in Java which uses the Java library for avro.
Everything works fine for payloads sent from web browsers, the problem occurs in mobile browsers.

In JavaScript, I define an `EventProtocol` with `avro.parse` which returns a protocol.
Then I obtain an `EventSchema` with `EventProtocol.getType`, check if the payload to be sent is valid with `EventProtocol.isValid` and finally encode the payload with `EventProtocol.toBuffer`.

Note that no errors come up before the payload is sent.

**Comment by mtth** [comment]
So the same JavaScript code works on desktop browsers but not mobile ones?

**Comment by juanpjacob** [comment]
Exactly, here there is a list of some user agents which are having this problem:
- Mozilla/5.0 (Linux; Android 4.4.4; SM-G530M Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                             - Mozilla/5.0 (Linux; Android 6.0; F3213 Build/36.0.A.2.146) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko)
- Mozilla/5.0 (Linux; Android 5.1; XT1032 Build/LPBS23.13-56-2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/117.0.0.18.47;]                                                                       - Mozilla/5.0 (Linux; Android 6.0.1; SM-T800 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36                                                                                                                                     - Mozilla/5.0 (Linux; Android 5.1.1; MOT-A6020l37 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36                                                                                                                         - Mozilla/5.0 (Linux; Android 5.1.1; SM-J500M Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G925I Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36                                                                                                 - Mozilla/5.0 (Linux; Android 5.1.1; SM-J500M Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                             - Mozilla/5.0 (Linux; Android 6.0; Lenovo A7010a48 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                        - Mozilla/5.0 (Linux; Android 6.0.1; SM-A500M Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.126 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (Linux; Android 6.0; LG-K430 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                                - Mozilla/5.0 (Linux; Android 4.1.2; GT-I8550L Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (Linux; Android 6.0; XT1069 Build/MPB24.65-34) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (Linux; Android 5.1.1; SM-G531H Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                                             - Mozilla/5.0 (Linux; Android 4.4.4; Personal Huawei G620S Build/HuaweiG620S-L03) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36                                                                                                       - Mozilla/5.0 (Linux; Android 6.0.1; SM-G610M Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36                                                                                                                            - Mozilla/5.0 (Linux; Android 6.0.1; Moto G Play Build/MPIS24.241-15.3-16) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36                                                                                                             
- Mozilla/5.0 (Linux; Android 5.1.1; SM-G531M Build/LMY48B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

**Comment by mtth** [comment]
That's very strange, `avsc` is very much downstream of these environment changes.

+ How are you compiling client code? Browserify/webpack/something else?
+ Could you inspect what the payload looks like before being sent over the wire? Is it different in these browsers than the rest?

**Comment by mtth** [comment]
@juanpjacob - any updates?

**Comment by juanpjacob** [comment]
Hey @mtth, I've been busy on these days, answering your question...
We use webpack to compile our client code.
Anyway, we've been trying to figure out the source of our problem and we cannot be sure it's this avro library, we added an http GET request, sending the params via query string and we are still receiving some events with null information in some fields in this request... so maybe it's a cache problem somewhere, we are still looking into it

**Comment by mtth** [comment]
Thanks @juanpjacob. Closing since it seems unrelated to `avsc`; feel free to reopen otherwise.
